### ISSUE TITLE
Make requests module part of the image

### ISSUE THREAD

**Issue by amigthea** [JonnyWong16/plexpy#1508]
## Desired Behavior
I need to use a very [useful script](https://github.com/blacktwin/JBOPS/tree/master/killstream) that requires the requests module installed, could be it implemented in the image?

## Current Behavior
requests module need to be installed manually

**Comment by JonnyWong16** [comment]
Python `requests` is already included.

Link: https://github.com/Tautulli/Tautulli/tree/master/lib/requests

**Comment by amigthea** [comment]
this is the beheaviour of a fresh container:

**root@tautulli:/app# /opt/script/kill_stream.py**
Traceback (most recent call last):
  File "/opt/script/kill_stream.py", line 60, in <module>
    from requests import Session
**ModuleNotFoundError: No module named 'requests'**
**root@tautulli:/app# pip install requests**
Collecting requests
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 871 kB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 7.7 MB/s
Collecting idna<4,>=2.5
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 19.0 MB/s
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.5-py3-none-any.whl (37 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     |████████████████████████████████| 145 kB 45.2 MB/s
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2021.5.30 charset-normalizer-2.0.5 idna-3.2 requests-2.26.0 urllib3-1.26.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
**root@tautulli:/app# /opt/script/kill_stream.py**
usage: kill_stream.py [-h] --jbop {stream,allStreams,paused} [--userId USERID] [--username USERNAME] [--sessionId SESSIONID] [--notify NOTIFY] [--limit LIMIT] [--interval INTERVAL]
                      [--killMessage KILLMESSAGE [KILLMESSAGE ...]] [--richMessage {discord,slack}] [--serverName SERVERNAME] [--plexUrl PLEXURL] [--posterUrl POSTERURL] [--richColor RICHCOLOR] [--debug]
kill_stream.py: error: the following arguments are required: --jbop
root@tautulli:/app#

**Comment by JonnyWong16** [comment]
You should not be modifying anything inside the container.

GitHub is not the place for support. Please use the [Discord server](https://tautulli.com/discord) for script support.

**Comment by amigthea** [comment]
I know, it's for this exact reason that I need the image to be provided with that module that's missing, as you can read from my previous shell logs message

edit: my fault, I realized what was wrong, thank you anyway
