### ISSUE TITLE
Set media to only allow one playback at a time

### ISSUE THREAD

**Issue by nmjohnson** [JonnyWong16/plexpy#1509]
### Is your feature request related to a problem?

I have yet to find a plex or plex alternative that allows me to restrict media playback to one viewer at a time. Or on other words, set the limit on concurrent streams to one (or any number I guess). This would allow me to legally lend the media I own to others provided I have obtained the media via legal means.

### What is your feature request?

To allow admins to set a max number of concurrent streams per media item. If the max number of concurrent streams has been achieved, notify other users that the playback of the media item is temporarily unavailable.

### Are there any workarounds?

Not that I've found, otherwise I would be using them.

**Comment by JonnyWong16** [comment]
Automatically restricting streams is outside the scope of Tautulli and not something I ever plan on implementing.

If you want to achieve something like that, then look into custom script notifications.
