### ISSUE TITLE
{year} does not work for recent content

### ISSUE THREAD

**Issue by markettepigeon** [JonnyWong16/plexpy#1513]
### Describe the Bug

Good evening, 

I have configured the notifications for Telegram and everything works except a few times for the variable {year}.  
Sometimes the date is not displayed. 
Yet Plex and tautulli have the date of recording.  
I tried on two series of 2019-2918 and Telegram gives me the date.  
However for series which have been released very recently this does not work.  
Example of a series: Squid Game or nine perfect strangers.  

Thank you

My notification :

Nouveau contenu pour : 
{show_name}
Année de sortie : {year}
Synopsis :  
{themoviedb_url} 
{imdb_url}
{thetvdb_url}
{tvmaze_id}

### Steps to Reproduce

Nouveau contenu pour : 
{show_name}
Année de sortie : {year}
Synopsis :  
{themoviedb_url} 
{imdb_url}
{thetvdb_url}
{tvmaze_id}

### Tautulli Version

VERSION V2.7.6

### Git Branch

Master

### Git Commit Hash

db90b8ad18023fe5cfc3d8e302b45d3db6ff2387

### Platform and Version

Windows 10 (10.0.14393)

### Python Version

3.8.10

### Browser and Version

Brave

### Link to Logs

.

**Comment by JonnyWong16** [comment]
Season notifications don't always have a year depending on the Plex metadata.
