### ISSUE TITLE
Support for Teams Notifications

### ISSUE THREAD

**Issue by JReich2609** [JonnyWong16/plexpy#1514]
### Is your feature request related to a problem?

N/A

### What is your feature request?

Would like to add the ability to send notifications natively through the Tautulli application to Microsoft Teams channels.

### Are there any workarounds?

Yes, you can use other notification methods. But MS Teams has become a fairly common/popular option in many software packages for notification-based messages and has become our option for many other things. Using a different environment is just not something we'd like to do for one application.

### Additional Context

N/A - Can provide more insight if needed.

**Comment by JReich2609** [comment]
If there is an alternative way to accomplish this goal I am open to it as well. Thanks.

**Comment by Arcanemagus** [comment]
This can be accomplished using the raw Webhook notification agent right now. A Teams specific one (similar to how Discord has one) _could_ be done though.

**Comment by JonnyWong16** [comment]
Reference:

https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook
https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#office-365-connector-card

**Comment by JReich2609** [comment]
Thank you. This solution **has** worked and the test was completed successfully. Having the native feature in there would be handy but either way good to go for now!
