### ISSUE TITLE
API set_notifier_config wipes Script Folder/Path

### ISSUE THREAD

**Issue by blakeoli34** [JonnyWong16/plexpy#1516]
### Describe the Bug

When using the api to set a notification agent's settings, the script folder and path are wiped (even if defined with parameter 'notifier_config', resulting in a broken script notifier agent.

### Steps to Reproduce

1. Setup a notification agent with a script folder and path
2. Try to alter the configuration of that notification agent using the api
3. Notice that the script folder and path fields are reset

### Expected Behavior

If 'notifier_config' parameter is not defined in the api request, the fields should not be altered. If it is defined in the api request, the fields should be updated to whatever is in the request.

### Tautulli Version

v2.7.6

### Git Branch

master

### Git Commit Hash

db90b8ad18023fe5cfc3d8e302b45d3db6ff2387

### Platform and Version

Linux 5.4.0-88-generic

### Python Version

3.6.9

### Browser and Version

Safari 15

### Link to Logs

https://gist.github.com/blakeoli34/192c17b9558939aadf5494a435db61a4

**Comment by JonnyWong16** [comment]
Unable to reproduce the issue.

The `set_notifier_config` requires _all settings_ to be provided. It cannot update a single setting. This is already explicitly specified in the API documentation. I understand that providing all settings when you only want to change one setting may not be the most intuitive behaviour, but that is the way the API works.

Before:
![image](https://user-images.githubusercontent.com/9099342/135687087-cb998cd5-49bc-4cf1-991e-0c6f1a7faa9b.png)

Postman:
![image](https://user-images.githubusercontent.com/9099342/135687230-25efcb93-cb37-472d-bb43-ecb911287ff1.png)

After:
![image](https://user-images.githubusercontent.com/9099342/135687260-24705891-aeb5-4bc5-953f-4b25554b18bb.png)

**Comment by blakeoli34** [comment]
I did not know the parameters for the script fields were different than shown in the database. I am seeing expected behavior now, thank you for your screenshot.
