### ISSUE TITLE
macOS Notification Agent error

### ISSUE THREAD

**Issue by srevn** [JonnyWong16/plexpy#1518]
### Describe the Bug

Tautulli Notifiers :: macOS failed: Cannot locate Python representation of bundleIdentifier

Tautulli notification agent for macOS stopped working since version 2.5. It may be some sort of misconfiguration on my part.

### Steps to Reproduce

Upon restarting Tautulli, the first macOS notification works, the next one ends as error.

### Tautulli Version
V2.7.6
### Git Branch
master
### Platform and Version
macOS Catalina 10.15.7
### Python Version
3.9.7
### Browser and Version
Brave Browser 1.30.87
### Link to Logs
https://gist.github.com/hypnosu/426fbd8cc9473fa4c968bcc05203c72f

**Comment by JonnyWong16** [comment]
This will take me a long time to track down. I don't own any macs do anytime I need to check macOS features I need to use a virtual machine and it's very challenging.

**Comment by Gnorkie** [comment]
Same problem here :(
macOS Big Sur 11.6.3

**Comment by jcpoyser** [comment]
Same issue here macOS Catalina 10.15.7 & Python 3.9.12

**Comment by ghost** [comment]
Same issue.

**Comment by Cow47** [comment]
Same issue here on an intel mac running 13.4
