### ISSUE TITLE
Display information about Transcode Reason

### ISSUE THREAD

**Issue by badi95** [JonnyWong16/plexpy#1525]
### What is your feature request?

Add information about transcode reason to stream info.

### Are there any workarounds?

Manually looking at the logs

### Additional Context

I'd like to be able to let remote users know when they haven't configured their client properly or if their streaming device is just old and they should get a new one. Transcode reason would help me able to alert them to that.

Duplicate of https://github.com/Tautulli/Tautulli/issues/1030 but that featurehub link doesn't seem to work anymore, and it was 4 years ago...

**Comment by JonnyWong16** [comment]
I don't know what "transcode reason" you're referring to.

**Comment by badi95** [comment]
Here's a log snippet with some of the info I'm talking about
```
grep "MDE:" Plex\ Media\ Server*.log -a | more
Plex Media Server.1.log:Oct 15, 2021 18:33:50.366 [0x7f59cde6fb38] DEBUG - [Transcode] MDE: Selected protocol http; container: mp3
Plex Media Server.1.log:Oct 15, 2021 18:33:50.366 [0x7f59cde6fb38] DEBUG - [Transcode] MDE: analyzing media item 42052
Plex Media Server.1.log:Oct 15, 2021 18:33:50.366 [0x7f59cde6fb38] DEBUG - [Transcode] MDE: tv.plex.agents: Direct Play is disabled
Plex Media Server.1.log:Oct 15, 2021 18:33:50.366 [0x7f59cde6fb38] DEBUG - [Transcode] MDE: tv.plex.agents: Audio Direct Streaming is disabled, so video's audio stream will be transcoded
Plex Media Server.1.log:Oct 15, 2021 18:33:50.366 [0x7f59cde6fb38] DEBUG - [Transcode] MDE: Cannot direct stream audio stream due to profile or setting limitations
Plex Media Server.1.log:Oct 15, 2021 18:33:50.366 [0x7f59cde6fb38] DEBUG - [Transcode] MDE: tv.plex.agents: selected media 0 / 42052
Plex Media Server.3.log:Oct 15, 2021 12:48:13.564 [0x7fabe0742b38] WARN - MDE: unable to find a working transcode profile for video stream
Plex Media Server.3.log:Oct 15, 2021 12:48:13.565 [0x7fabe0742b38] WARN - MDE: unable to find a working transcode profile for video stream
```

**Comment by JonnyWong16** [comment]
Tautulli doesn't read the Plex log file. So this will not be added to Tautulli until Plex provides that info through the API.
