### ISSUE TITLE
Nullrefer anonymizer service down

### ISSUE THREAD

**Issue by SmoothAdmin** [JonnyWong16/plexpy#1526]
### Describe the Bug

When I click on the "new release (v2.7.7) or click on the download link it tries to take me to www.nullrefer.com which doesn't resolve on any of the public DNS servers such as cloudfair, Level3, Google and OpenDNS. 

Actually having a second look at it while typing this I notice the link in the App points to:
https://www.nullrefer.com/?https://github.com/Tautulli/Tautulli/releases/tag/v2.7.7

If I use the https://github.. link it works but just wanted to let you know the first part of the link doesn't work becuase www.nullrefer.com isn't resolvable on the internet. 

### Screenshots

![image](https://user-images.githubusercontent.com/37107447/137586138-6e085a08-9e4c-4823-8a21-a559b02b97c2.png)

### Tautulli Version

v2.7.6

### Git Branch

master

### Git Commit Hash

db90b8ad18023fe5cfc3d8e302b45d3db6ff2387

### Platform and Version

Windows Server 2019

### Python Version

3.8.10

### Browser and Version

MS Edge Chrome, Chrome

### Link to Logs

C:\Users\SVC.Plex\AppData\Local\Tautulli\logs\tautulli.log

**Comment by JonnyWong16** [comment]
`nullrefer.com` comes and goes.

You can change your Settings > Web Interface > Anonymous Redirect (show advanced) to `https://nullreferer.com/?` or another service of your choice that is working.

**Comment by supermarkert** [comment]
Note: nullrefer.com links are still included in the Tautulli "News" section, and so any links in each of those posts is broken. Example: "Plex Feature Request for External Guids"

**Comment by samwiseg0** [comment]
> Note: nullrefer.com links are still included in the Tautulli "News" section, and so any links in each of those posts is broken. Example: "Plex Feature Request for External Guids"

Thanks for the report. In the future please use the discord server. This is a non issue as the links are pulled from tautulli.com and they are automatically updated.
