### ISSUE TITLE
Filter Intros Detected

### ISSUE THREAD

**Issue by JacquelineHyde** [JonnyWong16/plexpy#1531]
### What is your feature request?

It would be really awesome to filter on TV Series where intro detection has been (or hasn't been) completed. It would be great to see this at the episode, season, and series level.

### Are there any workarounds?

None that I'm aware of.

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli/wiki/Exporter-Guide

`episode.hasIntroMarker`
