### ISSUE TITLE
Newsletter does not capture album groups

### ISSUE THREAD

**Issue by jkunst830** [JonnyWong16/plexpy#1559]
### Describe the Bug

The recently added newsletter is not capturing new albums that are one of the new album group categories. Examples are live albums, complications, and soundtracks. Any new album that isn't in the generic "Albums" group is omitted from the newsletter.

### Steps to Reproduce

Enable groups under Plex Library settings
Add a new album that is in a group such as a live album.
Run a newsletter showing  newly added albums.

### Expected Behavior

All newly added albums should be included in the newsletter if they are a part of an included library.

### Screenshots

![11 04 2021](https://user-images.githubusercontent.com/45106821/140313865-1a34371c-f079-436f-93a2-cf01d5f2a881.PNG)

### Tautulli Version

V2.7.7

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

[Docker] Linux 4.4.180+ (#41890 SMP Thu Jul 15 03:37:40 CST 2021 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.6 (default, Aug 17 2021, 02:29:16) [GCC 10.2.1 20210110]

### Browser and Version

Chrome 95

### Link to Logs

2021-11-04 07:21:00 - INFO    :: CP Server Thread-10 : Tautulli Newsletters :: Generating newsletter preview. 2021-11-04 07:23:52 - DEBUG   :: Thread-70 : Tautulli ActivityHandler :: Session 133 watched. 2021-11-04 07:23:56 - DEBUG   :: Thread-70 : Tautulli ActivityHandler :: Session 133 stopped. 2021-11-04 07:23:56 - DEBUG   :: Thread-70 : Tautulli ActivityProcessor :: Fetching metadata for item ratingKey 180651 2021-11-04 07:23:56 - DEBUG   :: Thread-70 : Tautulli ActivityHandler :: Removing sessionKey 133 ratingKey 180651 from session queue

**Comment by jkunst830** [comment]
This doesn't seem to have been fixed. I had had two newsletters go out after the fix including one where I added albums after the fix. They were soundtrack and compilation albums, but were not included in the newsletter.

**Comment by samwiseg0** [comment]
> This doesn't seem to have been fixed. I had had two newsletters go out after the fix including one where I added albums after the fix. They were soundtrack and compilation albums, but were not included in the newsletter.

Please use discord for support. Issues is not the place for support. 
Thanks
