### ISSUE TITLE
Telegram Notifications Not working anymore after update

### ISSUE THREAD

**Issue by spsanderson** [JonnyWong16/plexpy#1560]
### Describe the Bug

My Telegram notifications stopped working when I updated on 11-02-2021

### Relevant Settings

All agent notifications set for Telegram

 Branch: | master

Git Commit Hash: | v2.7.7
Configuration File: | /config/config.ini
Database File: | /config/tautulli.db \| Status
Log File: | /config/logs/tautulli.log
Backup Directory: | /config/backups
Cache Directory: | /config/cache
Export Directory: | /config/exports
Newsletter Directory: | /config/newsletters
Arguments: | ['--datadir', '/config']
Platform: | [Docker] Linux 4.15.0-161-generic (#169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021)
System Timezone: | America/New_York (UTC-0400)
Python Version: | 3.8.10 (default, May 6 2021, 00:05:59) [GCC 10.2.1 20201203]
tml>

### Tautulli Version

2.7.7

### Git Branch

master

### Git Commit Hash

nullrefer not working

### Platform and Version

Ubuntu Server 18.04 LTS

### Python Version

3.8.10

### Browser and Version

MS Edge Version 95.0.1020.40 (Official build) (64-bit)

### Link to Logs

https://gist.github.com/spsanderson/ca48d4dae0004fb791c22044b4324d7e

**Comment by JonnyWong16** [comment]
What exactly isn't working? It seems like you sent some test Telegram notifications and it was successful.

I don't see any update on 2021-11-02. You've been on v2.7.7 since the beginning of your log file which goes back to 2021-10-29.

Have you simply tried restarting Tautulli? I don't see any restarts or attempts at restarting in your logs at all.

**Comment by spsanderson** [comment]
Actually they were not successful. I did not restart Tautulli I will try that.

Wonder why my log file only goes back that far, been using Tautulli for years

Love the program btw

**Comment by spsanderson** [comment]
Restart worked
