### ISSUE TITLE
Emby Support for Tautulli

### ISSUE THREAD

**Issue by Skyfay** [JonnyWong16/plexpy#1563]
### Is your feature request related to a problem?

Not really, but there is no comparable software for Emby

### What is your feature request?

It would be cool if you could also connect an Emby server to display data.

### Are there any workarounds?

I use Tautulli to send messages about new films and series on Discord.
Currently I have to have the Plex server installed separately so that Tautulli reports the most recently added films and series on discord. If this worked directly through Emby, it would be a lot easier for me.

**Comment by TheMeanCanEHdian** [comment]
Duplicate of #1120 

There is currently no plans to support anything besides Plex.
