### ISSUE TITLE
Incorrect `z-index` for warning message

### ISSUE THREAD

**Issue by napei** [JonnyWong16/plexpy#1567]
### Describe the Bug

The warning message for `/config` mount issues and perhaps similar messages have an incorrect `z-index` (or something else does) making them overlap modals.

### Screenshots

![image](https://user-images.githubusercontent.com/8946502/143397843-0fb1644f-b648-48e2-a0e0-99efa2292066.png)

### Tautulli Version

2.7.7

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

Docker on Ubuntu 21

### Python Version

3.9.6

### Browser and Version

Chrome Latest

### Link to Logs

N/A

**Comment by JonnyWong16** [comment]
Already fixed in `nightly` a month ago. 

5a5e6b2f4e13dabebfd01a99a45e16b41f44493b
