### ISSUE TITLE
Update to v2.8 beta -> bad magic number in 'argparse'

### ISSUE THREAD

**Issue by meepmeep** [JonnyWong16/plexpy#1578]
### Describe the Bug

I updated my install of Tautulli to v2.8.0.-beta, after 120sec, it did not come back online.
With the cli, I try to restart it :
```

Traceback (most recent call last):
  File "/home/meepmeep/RAID/Tautulli/PlexPy.py", line 20, in <module>
    from Tautulli import main
  File "/home/meepmeep/RAID/Tautulli/Tautulli.py", line 29, in <module>
    import argparse
ImportError: bad magic number in 'argparse': b'\x03\xf3\r\n'

```

Roll back with `git checkout refs/tags/v2.7.7`, it works again.

### Steps to Reproduce

1. Choose the beta channel to update tautulli.
2. Save & fetch new version
3. click on "update" 
4. wait ... it crashes.
5. Unable to manually restart it

### Expected Behavior

Update to V2.8.0-beta

### Tautulli Version

v2.7.7

### Git Branch

master to beta

### Git Commit Hash

 5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

Ubuntu 20.04.3 LTS

### Python Version

3.8.10

### Browser and Version

Firefox 78 ESR

### Link to Logs

https://gist.github.com/meepmeep/a5640e80f68447ee122195a696b76632

**Comment by samwiseg0** [comment]
https://github.com/Tautulli/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29#notes-2
