### ISSUE TITLE
Support for Gotify notification agent

### ISSUE THREAD

**Issue by LargeTalons** [JonnyWong16/plexpy#1584]
### Is your feature request related to a problem?

No

### What is your feature request?

Would like to add support for sending push notifications to Gotify

### Are there any workarounds?

There is support for a number of other notification agents already. However, Gotify allows users to self host their own notification server if they want to keep their usage more private or want a rich set of features without having to pay a fee to get them. The way Gotify works is very similar to pushover, but its self hosted and free. 

### Additional Context

https://gotify.net/

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli/releases/tag/v2.8.0-beta

**Comment by LargeTalons** [comment]
Sweet! Thank you guys for the work you do :)
