### ISSUE TITLE
Motorola Edge 20 Fusion Android with Chrome recognised as Microsoft Edge browser

### ISSUE THREAD

**Issue by jesserockz** [JonnyWong16/plexpy#1586]
### Describe the Bug

My Motorola Edge 20 Fusion Android with Chrome is recognised as a Microsoft Edge browser

My phones user agent is: `Mozilla/5.0 (Linux; Android 11; motorola edge 20 fusion) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36` and I suspect it is because it has `edge` in it.

### Screenshots

![Screenshot_20211207-191015-832](https://user-images.githubusercontent.com/3060199/144977647-1bc029e1-6c05-482c-b2db-c80871662155.jpg)

### Tautulli Version

V2.7.7

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

[Docker] Linux 5.10.0-9-amd64 (#1 SMP Debian 5.10.70-1 (2021-09-30) - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.6 (default, Aug 17 2021, 02:29:16) [GCC 10.2.1 20210110]

### Browser and Version

Chrome 96

### Link to Logs

N/A

**Comment by JonnyWong16** [comment]
Tautulli/Tautulli-Issues/issues/264
