### ISSUE TITLE
Tags missing on notification with PLEX TV Series agent

### ISSUE THREAD

**Issue by sk8er000** [JonnyWong16/plexpy#1588]
### Describe the Bug

I'm using Tautulli to notify on a private Telegram channel new additions to the Plex server. Since the TV series database is become pretty big and sometimes Plex need a lot of time to sync series with a lot of episodes I switched o the faster Plex TV series Agent.

Using that agent Tautulli doesn't report some tags, like {release_date} {air_date} and {year} that previously were working and still work for other libraries that uses older agents like movies (with themoviedb).

The strange part is that tags are shown in both Plex and Tautulli but tautulli does't report hem on the notifications

### Steps to Reproduce

- Set the TV series agent to "Plex TV series"
- Insert {year} tag to recently added content notification on Tautulli
- Add a new episode on Plex

### Expected Behavior

Some tags like {year} aren't reported on the notification agent

### Tautulli Version

v2.7.7

### Git Branch

master

### Git Commit Hash

v2.7.7

### Platform and Version

[Docker] Linux 5.10.60-qnap (#1 SMP Fri Nov 19 09:22:05 CST 2021)

### Python Version

3.8.10 (default, May 6 2021, 00:05:59) [GCC 10.2.1 20201203]

### Browser and Version

Chrome

### Link to Logs

https://gist.github.com/sk8er000/7c21236324c162206ba2fe11b89beace.js

**Comment by thunder2k** [comment]
Same here, this issue broke my trakt scrobble script sending empty year!

**Comment by JonnyWong16** [comment]
Release Date and Air Date work for episodes. Plex doesn't provide a "year" for episodes (see #1513). Can you just use `{air_date}` for the episode year?

**Comment by sk8er000** [comment]
using {air_date} is not working for me unfortunately, it behave like {year}

**Comment by JonnyWong16** [comment]
Make sure the Plex XML has the `originallyAvailableAt` date for the episode.

Go to the episode in Plex Web > Click the three dots overflow menu > Get Info > View XML.

![image](https://user-images.githubusercontent.com/9099342/145868409-411660bf-58dd-495d-88a6-37f37063233e.png)

You can also see that `year` is not in the XML (Ctrl+F `year`) therefore it is not available.

**Comment by sk8er000** [comment]
you are right, if that part is present {air_date} it's working, and a possible workaround is to set the tautulli date to show only YYYY instead of YYYY-MM-DD. The only problem is when a aired date is not present. So is it a Plex Agent issue and not a Tautulli related one? 
If i browse a series from Tautulli on the "general" series page the aired year is present and if I open a Season the year is still present (different for each season) like before with the previous agent so I thougt that was a notification bug..

**Comment by JonnyWong16** [comment]
That is a Plex issue.
