### ISSUE TITLE
Tautuilli SSL termination issues

### ISSUE THREAD

**Issue by nachopants** [JonnyWong16/plexpy#1589]
### Describe the Bug

We have built an SSL termination proxy in AWS as a forwarding server to external environments. This system is running the latest nginx with plenty of resources. It acts as a forwarding proxy for roughly 15 services with Tautulli itself being the only target system experiencing issues, as has been the case for over a year.

I expected this would be an issue suffered by most, hence patiently waited for a fix, but with none coming I thought perhaps it's on me to put the effort into a bug report, so here I am :)

On every reload, Tautulli gives either 200s or 502s for various artifacts on load. This is entirely random (i.e. different artifacts succeed/fail on any given page load)

### Steps to Reproduce

1. AWS ELB with SSL termination
2. AWS EC2 nginx proxy instance

    server {
        listen       80;
        listen       [::]:80;
        server_name  <___redacted___>;

        location / {
                proxy_set_header    Host                $host;
                proxy_set_header    X-Real-IP           $remote_addr;
                proxy_set_header    X-Forwarded-Host    $server_name;
                proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto   $scheme;
                proxy_set_header    X-Forwarded-Ssl     on;
                proxy_connect_timeout 30;
                proxy_read_timeout 90;
                proxy_buffer_size 256k;
                proxy_buffers 4 512k;
                proxy_busy_buffers_size 512k;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;
                proxy_pass <___redacted___>;
        }
    }

### Expected Behavior

Consistent loading of assets

### Screenshots

![image](https://user-images.githubusercontent.com/2382665/145693786-e1f16390-3256-4e84-8abb-2003828f84c3.png)

![image](https://user-images.githubusercontent.com/2382665/145693889-8c999f83-0893-47b7-a30a-9e77be37a16e.png)

### Relevant Settings

![image](https://user-images.githubusercontent.com/2382665/145693946-34b389d3-01a9-4120-b075-73f51992d568.png)

### Tautulli Version

All versions

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

OSX

### Python Version

3.8.12

### Browser and Version

All Browsers

### Link to Logs

https://gist.github.com/nachopants/cc132d1fd49e8414f5c70d517c335607

**Comment by JonnyWong16** [comment]
I haven't looked into the details of your bug report yet, but can you try increasing the webserver thread pool size?

See #1425.

**Comment by nachopants** [comment]
Increased nginx workers to 4096

Increased Tautulli http_thread_pool to 128

No improvement unfortunately

**Comment by JonnyWong16** [comment]
Logs after changing it?

**Comment by nachopants** [comment]
https://gist.github.com/nachopants/7adf209c3a6f9032b497cea1976a49dd

**Comment by JonnyWong16** [comment]
I don't see the thread pool being changed.

```
2021-12-14 20:24:37 - INFO    :: MainThread : Tautulli WebStart :: Thread Pool Size: 10.
```

You cannot edit the config file while Tautulli is still running.

**Comment by nachopants** [comment]
Apologies sir.

https://gist.github.com/nachopants/cb27ed6b2823e33a470f38c8e1e20d53

2021-12-15 11:54:58 - INFO    :: MainThread : Tautulli WebStart :: Thread Pool Size: 128.

No improvement.

**Comment by JonnyWong16** [comment]
Can you start Tautulli in dev mode which will provide more verbose logs?

From the terminal:

```
/Applications/Tautulli.app/Contents/MacOS/./Tautulli --dev
```
