### ISSUE TITLE
nullrefer.com on v2.8.0 download link

### ISSUE THREAD

**Issue by petebocken** [JonnyWong16/plexpy#1594]
### Describe the Bug

I got the notification in the bottom right corner for v2.8.0. The download link is: https://www.nullrefer.com/?https://github.com/Tautulli/Tautulli/releases/tag/v2.8.0 which is broken.

### Steps to Reproduce

1. Open Tautulli website
2. Click on Download link in bottom right "new release" popup.

### Expected Behavior

A link that loads a download page or a direct download for the version update.

### Tautulli Version

2.7.7

### Git Branch

master

### Git Commit Hash

5f22ad26ad52fbf7881aac988a59853a2bde9887

### Platform and Version

Windows 10

### Python Version

3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

### Browser and Version

Firefox 95

### Link to Logs

can supply if needed

**Comment by samwiseg0** [comment]
Duplicate of https://github.com/Tautulli/Tautulli/issues/1526
