### ISSUE TITLE
Can we get Jellyfin support?

### ISSUE THREAD

**Issue by Kayizoku** [JonnyWong16/plexpy#1597]
### Is your feature request related to a problem?

It's so troubling that I cannot log my content and see the past when I want to. It would be so awesome to have the support of Tautulli, which I absolutely loved for Plex too. But now I use Jellyfin, which is becoming more popular everyday. It would be much appreciated for support for it to be implemented.

### What is your feature request?

I want Jellyfin support. Same as Plex

### Are there any workarounds?

Not that I know of, sorry.

**Comment by samwiseg0** [comment]
This has been asked many times. At this time no one who actively develops for Tauttulli uses or has any desire to start using Jellyfin. Secondly, it would not make sense to simply "add support for Jellyfin" as it would require a complete re-write of the entire application. Given all those factors. We have no plans to implement this currently.
