### ISSUE TITLE
Eliminate Users From History View

### ISSUE THREAD

**Issue by ndoggac** [JonnyWong16/plexpy#1598]
### Is your feature request related to a problem?

In the "History" view, you can view all users, and you can select a single user to view.  It would be nice to have the ability to eliminate users from the view as well.  In other words, view all users except the ones I've selected.  My own user is typically the most active on my server, but there are times when I want to review only what other shared (remote) users are doing, and my own activity makes the list too busy to easily review the data.

### What is your feature request?

Ability to eliminate specific users from the "History" list view.

**Comment by JonnyWong16** [comment]
Duplicate #1557
