### ISSUE TITLE
Stream count + breakdown of type in Android/iOS app

### ISSUE THREAD

**Issue by jaretclifton** [JonnyWong16/plexpy#1608]
### Is your feature request related to a problem?

No

### What is your feature request?

Similar to the PlexDash native app, it would be great to see a total count of streams and the breakdowns of direct stream/direct play/transcode etc. at the top of the Tautulli Mobile App.

### Are there any workarounds?

N/A

### Additional Context

N/A

**Comment by JonnyWong16** [comment]
The mobile app is a different Github repository.

Duplicate https://github.com/Tautulli/Tautulli-Remote/issues/126
