### ISSUE TITLE
Sync Watched Status between Plex Users

### ISSUE THREAD

**Issue by Ltek** [JonnyWong16/plexpy#1610]
### Is your feature request related to a problem?

In order to take advantage of Home Automation and (separately) tracking and notification of usage, I have each Plex instance be a different Plex User. This is really the only way to accomplish these things - unfortunately.  But since each device is a different user, it maintains separate watched status. This is not desirable. 

Since Tautulli fills many (most) gaps in Plex I'm hoping it can address this one also.

### What is your feature request?

Ability to sync all watched/unwatched status between multiple plex users on a single please server.

### Are there any workarounds?

none known

**Comment by samwiseg0** [comment]
Are you saying you have multiple plex servers and would like to track multiple plex servers with one instance of Tautulli?

**Comment by dgriffinzero** [comment]
This would be useful for a situation like mine where my kids are all getting old enough to migrate off of the main shared account and onto their own accounts, but don't want to lose their viewing data.

**Comment by Arcanemagus** [comment]
This is something you can accomplish using the [sync_watch_status.py](https://github.com/blacktwin/JBOPS/blob/master/utility/sync_watch_status.py) script over in the [JBOPS](https://github.com/blacktwin/JBOPS) repo. Tautulli itself will not be implementing manipulation of watch history on your Plex server like this.
