### ISSUE TITLE
Option to import user history from Plex

### ISSUE THREAD

**Issue by tdeverx** [JonnyWong16/plexpy#1611]
### What is your feature request?

I noticed that there was once a feature request for this **[HERE](https://github.com/Tautulli/Tautulli/issues/53)**, but ultimately, it wasn't implemented and I would love to revisit this topic and discuss possible options for something, even if very basic?

- The first option I have which I highly doubt is feasible, maybe Plex have changed what they save? The original request was quite a while ago now so maybe things have changed on that front? 

- The second option I have, which is totally feasible! How about a "dumb" import? I'm talking a basic import without all the bells and whistles, without the ability to sync, just a standard import that fills in the gaps that are left by Plex?

I don't personally care if it's correctly tagged with Transcoded / Direct Play etc or if the time spent watching isn't perfectly accurate. I'd be more than happy with estimates for time spent by referencing the Movie / Show runtime. 

The reason I'd like this, even if a "dumb" import, is because Overseerr are implementing Tautulli to include watch stats on user profiles and as I've only recently reinstalled Tautulli, its lacking the true watch history for my users.

**Comment by samwiseg0** [comment]
Unfortunately this has been asked and discussed many times. Partial data import is not something we intend to implement as then it would make the data in Tautulli highly inaccurate. 

Plex watch data is inaccurate at best and they use an entirely different metric to consider something “watched”.
