### ISSUE TITLE
Breaking changes: Remove get_settings API command

### ISSUE THREAD

**Issue by tfonfara** [JonnyWong16/plexpy#1616]
### Is your feature request related to a problem?

Commit "Remove get_settings API command": https://github.com/Tautulli/Tautulli/commit/c39f89356c235820362c461e0d3e7809d430541f

### What is your feature request?

Is there any specific reason why you introduce this breaking change to the api?

There are plenty of features I'm using in my app that are using a subset of get_settings command e.g.:
- Info the connected plex service instance (incl. the auth token being used) in order to apply direct communication options
- Info about Tautulli update status
- Info about Plex server update status
- Info about the git config of Tautulli (used for example to request the release notes from GitHub)

The feature request would be to undo the above mentioned commit https://github.com/Tautulli/Tautulli/commit/c39f89356c235820362c461e0d3e7809d430541f, as this would make a lot of users unhappy :)

### Are there any workarounds?

No workarounds, as there is no other way to get this kind of information.

**Comment by JonnyWong16** [comment]
> Info the connected plex service instance (incl. the auth token being used) in order to apply direct communication options

I was ask by Plex to specifically remove any ability to retrieve the Plex token.

There are also other secrets inside inside the config that should not be exposed through the API.

Unfortunately I cannot add this API command back. I can add other API commands to retrieve specific info, but not a complete dump of the config file.

**Comment by JonnyWong16** [comment]
I think I can add `get_settings` back with the `pms_token` and other secrets removed.

**Comment by tfonfara** [comment]
> I was ask by Plex to specifically remove any ability to retrieve the Plex token.

Too bad, but I can see the point. Thanks for sharing!


> I think I can add `get_settings` back with the `pms_token` and other secrets removed.

That would be super awesome!
