### ISSUE TITLE
machine_id as column in user|history

### ISSUE THREAD

**Issue by merc1031** [JonnyWong16/plexpy#1619]
### What is your feature request?

Would be nice to have `machine_id` as column in user|history.
Sometimes users access from multiple machines and SOMETIMES it might be useful to know if its a certain device for stream killing process.

### Are there any workarounds?

Can work around by logging in a script. But its not as slick

**Comment by Arcanemagus** [comment]
The `machine_id` is already in the `session_history` table, could you elaborate on what you mean?

**Comment by merc1031** [comment]
Is there a way to view that from the Users or History pages on the gui?
I can always mess with the sql and / the scripts, its just sometimes nice to be able to visualize all those accesses / devices + the ips accessing.

**Comment by Arcanemagus** [comment]
The `Product` + `Player` in the web interface are going to be a unique combo for _most_ users. If you need to get down to the level of the `machine_id` to distinguish between installs then you are probably better off using the API to get the data in the first place.

**Comment by merc1031** [comment]
Sure. I can do that and that's basically what I am currently doing.
Just wanted to suggest adding it as a possible (optionally checked off) column in the gui , especially since the data is available in the api.
For my case i am identifying a malicious user, but the product+ player are identical to non malicious user. 

Fine to close.
Thanks
