### ISSUE TITLE
Tautulli uses default config when run as SYSTEM

### ISSUE THREAD

**Issue by ThePieMonster** [JonnyWong16/plexpy#1622]
### Describe the Bug

When Tautulli executable is run via a script or system account, the application runs with the default config file instead of the typical config that would be used when running via the admin account.

If the application is run via a Administrator, then the process runs as expected. 

![image](https://user-images.githubusercontent.com/11359134/150738178-6a2a1e45-fb91-4cf8-9459-2ce76db2e8f8.png)

### Steps to Reproduce

PowerShell Script
NSSM service pointing to PowerShell script
`Start-Process -FilePath "C:\Program Files\Tautulli\Tautulli.exe"`

This will run a instance of Tautulli as shown in the prior screenshot, however the application will use default config.

### Expected Behavior

Tautulli starts and works as expected. 

### Tautulli Version

2.8.1.1

### Git Branch

master

### Git Commit Hash

2410eb33805aaac4bd1c5dad0f71e4f15afaf742

### Platform and Version

Windows Server 2016

### Python Version

3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]

### Browser and Version

Chrome 97

### Link to Logs

N/A

**Comment by JonnyWong16** [comment]
I don't see how this is a bug. This is expected behaviour. App data is stored per user so running it as a different user will use different app data.

**Comment by Arcanemagus** [comment]
I'm not sure there is a worse thing you could do for the security of a system than running a service as `SYSTEM` that didn't absolutely need those permissions.

**Comment by ThePieMonster** [comment]
With most services @Arcanemagus you are able to specify a user account to run the application as. Tautulli does not have that feature.
@JonnyWong16 with most applications a storage location can usually be specified in a config somewhere. That same storage location would then be used regardless of what user is responsible for running the application. Does Tautulli have anything like this?

**Comment by JonnyWong16** [comment]
Running an application as a specific user is an operating system level configuration, not an application level configuration.

Tautulli has a `--config` (points to the `config.ini` file) and `--datadir` (points to the folder where data is stored) commandline arguments.

**Comment by ThePieMonster** [comment]
@JonnyWong16 is that for Docker only? I don't see a config file in the Windows install.

**Comment by JonnyWong16** [comment]
No, command line options are available for all operating systems.

The default location on Windows is `%LOCALAPPDATA%\Tautulli`.

**Comment by ThePieMonster** [comment]
@JonnyWong16 Got it, however the issue that I am trying to explain is that by having the application (which is in C:\Program Files) point to a %appdata% location to create the initial files and config files is a issue. 
I have in the config to use a non app data location to store content. When I log into that machine, another instance of Tautulli opens and trys running as well, and creates another instance of all this data under the account I logged in with. There is no way for the application to reference back since it keeps looking in the appdata folder which doesn't exist, then creates it, rinse and repeat. 
Would be great to have the config stored in the C:\ProgramsFiles to tell the app not to keep creating new instances.

**Comment by JonnyWong16** [comment]
No it's not. User app data is the default location by design unless you explicitly specify a location using command line arguments.

If you are handling your own Tautulli startup then you need to disable "Run at startup" in the Tautulli settings which creates a startup entry in the Windows registry.

**Comment by ThePieMonster** [comment]
Do you know where in the registry these settings are being saved? Specifically the run on login? @JonnyWong16

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli/blob/master/plexpy/windows.py#L148

**Comment by samwiseg0** [comment]
@ThePieMonster If you need further support please use discord. Issues is not the place for support.
