### ISSUE TITLE
Snap: Writing to /media and /mnt not working 

### ISSUE THREAD

**Issue by cryptochrome** [JonnyWong16/plexpy#1628]
### Describe the Bug

Hello,

the new feature to access /media and /mnt mount points from within the Snap isn't fully working yet. IT can browse directories there, but not write to them. Upon trying to save a backup to a folder on /media, the log reports:

```
2022-01-27 00:08:18 | WARNING | Falling back to backups dir '/root/snap/tautulli/common/Tautulli/backups'
2022-01-27 00:08:18 | ERROR | Cannot write to backups dir '/media/backups/copperhead/tautulli/backups'
```

I suspect it's a permission thing. Not sure what user context Snaps operate under (root?). I think the FAQ should be updated, at least, to clarify this. 

### Tautulli Version

2.8.1

### Git Branch

master

### Git Commit Hash

2410eb33805aaac4bd1c5dad0f71e4f15afaf742

### Platform and Version

	Linux 5.13.0-27-generic (#29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 - Ubuntu Core 18)

### Python Version

3.6.9 (default, Dec 8 2021, 21:08:43) [GCC 8.4.0]

### Browser and Version

Chrome 98.0.4758.66

### Link to Logs

https://gist.github.com/cryptochrome/934ea4d72aa3583c3428793fbff339e5

**Comment by JonnyWong16** [comment]
The snap runs as root, so your mount needs to be writable by root.

I will update the FAQ.

**Comment by samwiseg0** [comment]
Also please verify you are using a version of snapd that supports this feature. 

https://snapcraft.io/docs/removable-media-interface

**Comment by cryptochrome** [comment]
Thanks Jonny. Writing with root works. So not a bug, just not enough info. Updating the FAQ should suffice :) I am closing this. Thanks for all your work on Tautulli!
