### ISSUE TITLE
Synced Items not working

### ISSUE THREAD

**Issue by ning42** [JonnyWong16/plexpy#1632]
### Describe the Bug

When downloading a film on a ipad/iphone etc. it does not show up on the Synced Items page in tautulli

### Steps to Reproduce

Download film item on plex device
My example is a Ipad ios 15.3 with plex 7.27
The plex media server (version 1.25.3.5409) running on a QNAP NAS starts to convert
Then it is dowloaded to the ipad, and is now offline/downloaded/sync local to the ipad

### Expected Behavior

The selected movie would be listed on the Synced Items overview in Tautulli

### Tautulli Version

V2.8.1

### Git Branch

master

### Git Commit Hash

2410eb33805aaac4bd1c5dad0f71e4f15afaf742

### Platform and Version

[Docker] Linux 5.10.60-qnap (#1 SMP Tue Dec 21 01:51:59 CST 2021 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.9 (main, Dec 21 2021, 10:14:07) [GCC 10.2.1 20210110]

### Browser and Version

Crhome 97

### Link to Logs

.

**Comment by samwiseg0** [comment]
If you are using the new download feature then the data is not "synced". This is a Plex limitation not a Tautulli one. Plex has not implemented downloads the same as sync. Thus no record of it will be kept.
