### ISSUE TITLE
Telegram Spoilers don't display correctly

### ISSUE THREAD

**Issue by madotha** [JonnyWong16/plexpy#1635]
### Describe the Bug

Telegram recently added the spoiler feature, to hide text and show it when you click on it. I wanted to add this to my notification agent, as I want descriptions for episodes hidden with this spoiler feature.
Though I couldn't get this to work properly, because in Telegram there's only two ways to format text as Spoilers:
1. Mark the text in Telegram, right-click and select the "Spoiler" format option
2. Adding two pipe symbols ( | ) at the beginning and the end of the text
I've also tried using the <details> HTML tag and crawled through the Telegram source code, though I couldn't find out how they implemented the spoiler feature and didn't get it to work so far.

### Relevant Settings

Notification agent configuration -> Telegram Agent -> Text -> Recently Added

<episode><details>{summary}</details></episode>
or
<episode>||{summary}||</episode>

### Tautulli Version

2.8.1

### Git Branch

master

### Git Commit Hash

2410eb33805aaac4bd1c5dad0f71e4f15afaf742

### Platform and Version

[Docker] Linux 4.4.180+ (#42218 SMP Mon Oct 18 19:16:55 CST 2021 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.9 (main, Dec 21 2021, 10:14:07) [GCC 10.2.1 20210110]

### Browser and Version

Safari 15.2, Chrome 97.0.4692.99

### Link to Logs

https://gist.github.com/madotha/c72d73c0b2c875be89fab57a79ff7fb5

**Comment by JonnyWong16** [comment]
I already fixed this and it will be available in the next release.

b9f04ac71ae8a67e1fc37534cc8d1cf85d8af38b

**Comment by madotha** [comment]
I've been testing the Markdown implementation now since the release of 2.9.1, even though I had to change all my tags in the notification from HTML to Markdown.
The spoilers do work now, but I'm getting constant errors when trying to send a notification containing "-" or "(". It throws the following error every time I contain one of these symbols (even tho I preceed every single one of them with a \\:

```Tautulli Notifiers :: Request response: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\\'"}```

```Tautulli Notifiers :: Request response: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Character '(' is reserved and must be escaped with the preceding '\\'"}```

Might this be a problem with the Markdown implementation or am I being at fault here?
I've attached my header and main body for the notification here:
[telegram_notification.txt](https://github.com/Tautulli/Tautulli/files/8021948/telegram_notification.txt)

**Comment by madotha** [comment]
Sorry, I've attached my previous notifications text (completely HTML).
This was the last used Markdown-infused nofitication text:
[telegram_notifications.md](https://gist.github.com/madotha/ae20c373f5805c91187ee53cdbe0d870)

**Comment by JonnyWong16** [comment]
Cannot reproduce.

![image](https://user-images.githubusercontent.com/9099342/152947169-1a101f7f-7203-4ff4-8bc6-020888c5440a.png)

![image](https://user-images.githubusercontent.com/9099342/152947241-3a9414e4-02ce-44dd-a812-7292035db183.png)

**Comment by madotha** [comment]
Could you maybe try this out with the [text I have](https://gist.github.com/madotha/a3f5e82812db50779de21ab068c54a28)?

As far as I've tested this, it seems that the description of the movies and series I'm testing this with contain characters which I can't exclude from formatting (as they're brought in through parameters). I've also looked at further Markdown explanations and can't find any way to exclude the text I get from the parameters from formatting, except marking the whole parameter as code.

Is this maybe you can solve from your side or is this simply impossible with the use of Markdown so far?

BTW: The latest error I'm getting is the following (even tho I don't have any "." in my text, this is why I assume it's from the description it gets through the parameter):
```Tautulli Notifiers :: Request response: {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\\'"}```

**Comment by JonnyWong16** [comment]
Thanks. So it's inside the parameters. There's no good way to escape all those characters. I think I will just have to revert the change an only support HTML.

**Comment by JonnyWong16** [comment]
MarkdownV2 reverted in Tautulli v2.9.2. Only HTML is supported for Telegram.

Use `<span class="tg-spoiler">spoiler</span>`, or `<tg-spoiler>spoiler</tg-spoiler>` for spoilers.

**Comment by madotha** [comment]
Thank you very much for solving this so quickly, the tg-spoiler class workaround works perfectly so far!
Maybe the problem might lie somewhere similar to this existing issue in the wrapper for the python-telegram-bot ([python-telegram-bot/python-telegram-bot #2371](https://github.com/python-telegram-bot/python-telegram-bot/issues/2371))?
Just wanted to point this out, I really appreciate the work you've been doing on Tautulli in the last couple of years!
