### ISSUE TITLE
Ability to exclude in user filters

### ISSUE THREAD

**Issue by bassterror** [JonnyWong16/plexpy#1645]
### What is your feature request?

Currently, you can see stats (History, Graphs, etc.) for "All users" or for a specific one. 
![Graphs](https://user-images.githubusercontent.com/4514140/152639955-fde36757-abda-4737-a4f5-11223fc76492.png)
![History](https://user-images.githubusercontent.com/4514140/152639956-cca5124a-e29f-4339-ada6-ea2ffeeff89c.png)

It would be nice if you could see stats for all users except some of them. A possible implementation would be a checkbox next to the username.
![Possible implementation](https://user-images.githubusercontent.com/4514140/152639954-92d98e8d-4fe0-46ac-84f5-89da635ffef7.png)
 

### Are there any workarounds?

I see there are other features, kind of related to this.
[User groups](https://github.com/Tautulli/Tautulli/issues/1557)

**Comment by ndoggac** [comment]
Would love this feature.

**Comment by digitalchet** [comment]
This would be great.

**Comment by DevMan01** [comment]
Upvote on this one. I really like the User List w/ Checkbox idea.

**Comment by Emstar** [comment]
Oops, missed the dupe. 

My take on the idea was adding search syntax, like `not("username")`. But I'd take anything.

**Comment by zdimension** [comment]
#2090 fixes this, by making the user selection drop-down multiselect

**Comment by ndoggac** [comment]
Great feature add, thank you!
