### ISSUE TITLE
Tautulli fails to install on 10.14

### ISSUE THREAD

**Issue by ambilzi** [JonnyWong16/plexpy#1650]
### Describe the Bug

The later releases of Tautulli (2.9.3 as an example) fails to install on macOS 10.14.

### Steps to Reproduce

Attempt to install Tautulli 2.9.3 pkg on macOS 10.14

### Expected Behavior

Installs without error

### Screenshots

default	08:24:01.278937 -0500	Tautulli	Failed to execute script 'Tautulli' due to unhandled exception: dlopen(/Applications/Tautulli.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Tautulli.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Tautulli.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so

### Tautulli Version

2.9.3

### Git Branch

master

### Git Commit Hash

cannot acquire

### Platform and Version

macOS 10.14.6

### Python Version

3.8.1

### Browser and Version

n/a

### Link to Logs

https://gist.github.com/ambilzi/e6e53fb8cfa407140dced0437d8f3a9f

**Comment by samwiseg0** [comment]
This was discovered yesterday by another user. Unfortunately, 10.14 is no longer supported by Apple which means that there will no longer be support for it with Tautulli.
2.8.1 is the last version that will run on 10.14.

**Comment by ambilzi** [comment]
I see, thanks for the info.
I was dreading this day, as my beefy classic Mac Pro is running an OS as far as I'm willing to push it, and now the software I use is leaving me behind.
Thanks for this development project. Tautulli is fantastic!
