### ISSUE TITLE
Activity section in the Tautulli app

### ISSUE THREAD

**Issue by DonCaliOni** [JonnyWong16/plexpy#1655]
### Is your feature request related to a problem?

N/A

### What is your feature request?

In the 'Activity' section of the Tautulli mobile app, streams are shown, however there is no immediate indicator as to whether streams are transcoding or direct playing. As such, you have to click into each individual stream to check this. It would be useful to have some sort of indicator for this - there seems to be plenty of space in the box for each stream.

### Are there any workarounds?

Clicking into streams individually to check.

**Comment by JonnyWong16** [comment]
This is the Tautulli issue tracker. The Tautulli Remote issue tracker is separate.

https://github.com/Tautulli/Tautulli-Remote/issues

The Tautulli Remote app uses the same icons to indicate Direct Play, Direct Stream, and Transcode as the Web UI. The icons are on the right side of the activity card.

![image](https://user-images.githubusercontent.com/9099342/153955450-e522105a-b8f8-421d-a1e3-7929cabba080.png)

**Comment by TheMeanCanEHdian** [comment]
Also note that there is already a Tautulli Remote feature request for additional information on the activity page to show transcodes, etc.

https://github.com/Tautulli/Tautulli-Remote/issues/126
