### ISSUE TITLE
Add tautulli for windows to winget repository to allow command line automated update

### ISSUE THREAD

**Issue by ospring** [JonnyWong16/plexpy#1656]
### Is your feature request related to a problem?

Since the windows installer version of tautulli, updating is a pain because you have to browse to download installer source, then stop tautulli, then run the wizzard and restart tautulli ! 

### What is your feature request?

Add Tautulli to the winget repository to allow simple command line updating 
`Winget upgrade Tautulli`

### Additional Context

https://docs.microsoft.com/en-us/windows/package-manager/package/?WT.mc_id=modinfra-34210-thmaure

**Comment by jasonpatrickellykrause** [comment]
⬆️

Seconding request. Being able to ` winget upgrade --all` would save so much time.

**Comment by shadshack** [comment]
I was just about to submit a request for the same thing. This would be SUPER convenient and would let me auto-update Tautulli again with just a scheduled task.

**Comment by JonnyWong16** [comment]
microsoft/winget-pkgs#79230

I'm going to guess it won't work because the installer can't be run 100% silent and it will prompt the user for confirmation due to an unsigned installer.

**Comment by ospring** [comment]
Great news ! Thanks

**Comment by jasonpatrickellykrause** [comment]
Bam, updated via `winget` today. Rad!

**Comment by Soitora** [comment]
Also upgraded via `winget`, I really love this package manager, hopefully it'll keep growing from here, very convenient

**Comment by TheMNSTR** [comment]
Hi. Sorry to dig this up, but it seems that the `--nolaunch` parameter doesn't work. Whether I run the installer manually with a command, or through winget, Tautulli still starts at the end of the installation.

**Comment by JonnyWong16** [comment]
`--nolaunch` is for opening a browser, not for starting Tautulli.

https://github.com/Tautulli/Tautulli/blob/8cb74f74806863abbc47419d85b002abb600ea00/Tautulli.py#L101

**Comment by TheMNSTR** [comment]
> `--nolaunch` is for opening a browser, not for starting Tautulli.
> 
> https://github.com/Tautulli/Tautulli/blob/8cb74f74806863abbc47419d85b002abb600ea00/Tautulli.py#L101

I'm sorry. Looks like I assumed incorrectly.
In that case, is there any installer parameter for not starting Tautulli after installation? If not, would it be possible to add this? Also, if you could also include an installer parameter that would skip the creation of the desktop shortcut, I would really appreciate it. The reason I'm asking for this, is I'm running Tautulli as a service on Windows, and I've recently started to update it with a script that downloads the latest release, and installs it. It'd be great if those two actions didn't get in the way, so to speak.
