### ISSUE TITLE
Active Filters in dark mode are difficult to distinguish

### ISSUE THREAD

**Issue by ohgeetee** [JonnyWong16/plexpy#1663]
### Is your feature request related to a problem?

Difficult to tell which filters are active in dark mode due to closeness of color of the tabs.
There is also no breadcrumb indicating active filters which would also be nice to have.

### What is your feature request?

In the history tab, make filters that are selected more easily distinguished when active/inactive in dark mode (is there only the dark mode?  can't tell if there's a light mode)
Nice to have: breadcrumb displaying active filters as well.

### Are there any workarounds?

just have to look very closely to distinguish diff between shades.

**Comment by JonnyWong16** [comment]
Are you referring to these filters? I've had the same thought.

![image](https://user-images.githubusercontent.com/9099342/154884704-26d25a2a-5fff-463e-9758-64f5ab8d028f.png)

Is this good enough?

![image](https://user-images.githubusercontent.com/9099342/154884667-1d0fe071-2c9c-4c6b-b64a-00a5d6e0d357.png)

No idea what you mean by "breadcrumbs".

**Comment by JDA88** [comment]
@JonnyWong16 The yellow color match the theme, it's perfect imo

**Comment by ohgeetee** [comment]
Yellow works well.  Breadcrumb is just a text indicator of applied
filters/page location you often see when navigating many sites.
