### ISSUE TITLE
Tautulli detected as "Program:Win32/Uwamson.A!ml"

### ISSUE THREAD

**Issue by whinette** [JonnyWong16/plexpy#1666]
### Describe the Bug

Windows Defender detected Tautulli as "Program:Win32/Uwamson.A!ml"

![image](https://user-images.githubusercontent.com/6152660/155382631-3c76315a-eb00-4e0f-993c-989a075b4af3.png)

### Tautulli Version

2.9.4

### Git Branch

master

### Git Commit Hash

cfd1bf445f7f5332b9183d98ea8893f325c5ca92

### Platform and Version

Windows 10 (10.0.19044)

### Python Version

3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]

### Browser and Version

n/a

### Link to Logs

n/a

**Comment by JonnyWong16** [comment]
https://reddit.com/r/Tautulli/comments/sz8wwl/tautulli_flagged_for_win32uwamsonaml_pua/hy2d77i/

**Comment by JonnyWong16** [comment]
Resolved. Update Microsoft Defender virus definitions to 1.359.794.0.
