### ISSUE TITLE
Tautulli Crashes when viewing Media details page

### ISSUE THREAD

**Issue by bigdant** [JonnyWong16/plexpy#1670]
### Describe the Bug

Tautulli loads normally and is logging plays, however when I go to a media details page for example "West Side Story" page.

It hangs loading "Global Stats" and "User Stats" and crashes the system which needs to be restarted (I have Tautulli running in docker on Unraid).

### Screenshots

![screencapture-info-2022-02-25-13_59_27](https://user-images.githubusercontent.com/52113784/155727874-07643377-4a2a-42b7-8e7d-7b6b49c142b0.png)

### Tautulli Version

V2.9.4

### Git Branch

master

### Git Commit Hash

cfd1bf445f7f5332b9183d98ea8893f325c5ca92

### Platform and Version

[Docker] Linux 5.10.28-Unraid (#1 SMP Wed Apr 7 08:23:18 PDT 2021 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.10

### Browser and Version

Chrome

### Link to Logs

https://gist.github.com/bigdant/2427a5cc9e1bd1bfb7d04f38e102f266

**Comment by JonnyWong16** [comment]
Someone else had the same symptoms on the Discord server.

https://discord.com/channels/183396325142822912/946193016291483649/946257946948542534

It was due to their database missing a migration and it was fixed by following this post.

https://old.reddit.com/r/Tautulli/comments/mq4ge4/databaselibrary_errors/gue0zul/

**Comment by bigdant** [comment]
That appears to have fixed it !! thanks alot Jonny.

Tautulli is amazing, keep up the good work.

D.

**Comment by thunder2k** [comment]
> Someone else had the same symptoms on the Discord server.
> 
> https://discord.com/channels/183396325142822912/946193016291483649/946257946948542534
> 
> It was due to their database missing a migration and it was fixed by following this post.
> 
> https://old.reddit.com/r/Tautulli/comments/mq4ge4/databaselibrary_errors/gue0zul/

Hi,
The suggested fix didn't work for me.

Here are my logs:
https://pastebin.com/8H0XhBF5 (password MEYfXXPEYG)

**Comment by samwiseg0** [comment]
> > Someone else had the same symptoms on the Discord server.
> > [discord.com/channels/183396325142822912/946193016291483649/946257946948542534](https://discord.com/channels/183396325142822912/946193016291483649/946257946948542534)
> > It was due to their database missing a migration and it was fixed by following this post.
> > [old.reddit.com/r/Tautulli/comments/mq4ge4/databaselibrary_errors/gue0zul](https://old.reddit.com/r/Tautulli/comments/mq4ge4/databaselibrary_errors/gue0zul/)
> 
> Hi, The suggested fix didn't work for me.
> 
> Here are my logs: [pastebin.com/8H0XhBF5](https://pastebin.com/8H0XhBF5) (password MEYfXXPEYG)

Please stop by discord for support. Thanks

**Comment by thunder2k** [comment]
> > > Someone else had the same symptoms on the Discord server.
> > > [discord.com/channels/183396325142822912/946193016291483649/946257946948542534](https://discord.com/channels/183396325142822912/946193016291483649/946257946948542534)
> > > It was due to their database missing a migration and it was fixed by following this post.
> > > [old.reddit.com/r/Tautulli/comments/mq4ge4/databaselibrary_errors/gue0zul](https://old.reddit.com/r/Tautulli/comments/mq4ge4/databaselibrary_errors/gue0zul/)
> > 
> > 
> > Hi, The suggested fix didn't work for me.
> > Here are my logs: [pastebin.com/8H0XhBF5](https://pastebin.com/8H0XhBF5) (password MEYfXXPEYG)
> 
> Please stop by discord for support. Thanks

**EDIT:**
I re-did the steps and it worked now! The only difference is that this time I also pressed "Close Database" after Write Changes. Please consider adding it to the original post.

Thanks!

The discord link seems to be broken!
![image](https://user-images.githubusercontent.com/43518960/158218945-0def7678-e5d6-4f7e-9cc9-11edc34e3e55.png)

**Comment by mprachar** [comment]
Fixed my weird issue as well - great tip!
