### ISSUE TITLE
Icons under Safari not showing

### ISSUE THREAD

**Issue by drsassafras** [JonnyWong16/plexpy#1678]
### Describe the Bug

Some Icons look fine in Chrome but fail to show in safari
<img width="473" alt="Screen Shot 2022-03-07 at 10 20 47 AM" src="https://user-images.githubusercontent.com/18317850/157063186-8ed508e4-2571-4b25-ba75-3b3cf770eeaf.png">
.

### Steps to Reproduce

Click the gearbox icon on settings to reveal the menu.

### Expected Behavior

The icons should show.

### Screenshots

<img width="473" alt="Screen Shot 2022-03-07 at 10 20 47 AM" src="https://user-images.githubusercontent.com/18317850/157063383-57fec8c3-b5a2-4a61-871d-98a0300a67be.png">

This is how it views under safari 15.1 on a MacOX 10.15.7 system.

### Tautulli Version

V2.9.4

### Git Branch

master

### Git Commit Hash

cfd1bf445f7f5332b9183d98ea8893f325c5ca92

### Platform and Version

FreeBSD 12.2-RELEASE-p12 (FreeBSD 12.2-RELEASE-p12 ec84e0c52a1(HEAD) TRUENAS - FreeBSD 12.2)

### Python Version

3.8.12 

### Browser and Version

Safari 15.1

### Link to Logs

N/A

**Comment by samwiseg0** [comment]
I am unable to replicate this issue. 

Are you using a proxy? Can you test going directly to the container/instance? Also please disable all extensions or use incognito mode to verify something else is not causing the issue. Lastly, check the developer console for errors

Running safari `Version 15.2 (17612.3.6.1.6)`
<img width="226" alt="Screen Shot 2022-03-07 at 12 27 10 PM" src="https://user-images.githubusercontent.com/2241731/157086187-c311db31-e8c1-4a2d-a585-45b9f62616ff.png">

**Comment by drsassafras** [comment]
Hi, I followed you're advice and ended up finding one of my extensions was causing these issues.

Rakuten Button Extension is the culprit here. Funny how something like that could cause the issue. That extension serves no purpose on this page whatsoever. Even still it causes issues.

Thanks for your help. I am closing the issue because it is clearly not a bug with the Tautulli code. It's unfortunate that it affects Tatulli though.

**Comment by drsassafras** [comment]
I submitted a bug report to Rakuten.
