### ISSUE TITLE
Tautulli reports 'no synced items'

### ISSUE THREAD

**Issue by Sc0th** [JonnyWong16/plexpy#1694]
### Describe the Bug

Tautulli reports 'no synced items'

### Steps to Reproduce

1. Sync/Down item in Plex client
2. View synced items page in Tautulli
3. reports 'no synced items'
4. triple click shows "SyncLists /SyncLists" - would have expected a 0 in here if nothing synced.

### Expected Behavior

Show synced items.

### Relevant Settings

Latest Plex server & Tautulli, both official docker.

### Tautulli Version

2.9.4

### Git Branch

master

### Git Commit Hash

don't see this

### Platform and Version

linux docker

### Python Version

3.7

### Browser and Version

Firefox

### Link to Logs

no

**Comment by JonnyWong16** [comment]
Duplicate #1632
