### ISSUE TITLE
Not able to connect to plex https

### ISSUE THREAD

**Issue by christianmerges** [JonnyWong16/plexpy#1695]
### Describe the Bug

When plex runs on https and Port 443 Tautulli still uses http even if I tick "Use Secure Connection". 

Issue happens with manuel hostname as well as choosing from the list of servers in the plex account. 

### Steps to Reproduce

Setup plex server listening to port 443 and enable https.
Setup virgin tautulli instance
Tick "Use Secure Connection"
Choose plex server from provided list. 

### Expected Behavior

Tautulli should use https if "Use Secure Connection" is ticked. 

### Tautulli Version

2.9.4

### Git Branch

master

### Git Commit Hash

cfd1bf445f7f5332b9183d98ea8893f325c5ca92

### Platform and Version

Docker

### Python Version

3.9.10

### Browser and Version

Chrome 99 on Android 11

### Link to Logs

Not needed

**Comment by JonnyWong16** [comment]
Logs are required, please.
