### ISSUE TITLE
Setup wizard allowing user to continue without logging into Plex account

### ISSUE THREAD

**Issue by ReenigneArcher** [JonnyWong16/plexpy#1697]
### Describe the Bug

When setting up Tautulli for the first time there is an AttributeError on the `Plex Media Server` tab when verifying the server. This happens if you don't log in to Plex on the previous tab.

### Steps to Reproduce

1. New instance of Tautulli (or clear config)
2. Don't login to Plex
3. Attempt to verify plex server

### Expected Behavior

Allow user to manually provide Plex token and/or force the user to login to Plex.

### Tautulli Version

2.9.4

### Git Branch

master

### Git Commit Hash

cfd1bf445f7f5332b9183d98ea8893f325c5ca92

### Platform and Version

Windows 11

### Python Version

3.9.6

### Browser and Version

Firefox

### Link to Logs

https://gist.github.com/ReenigneArcher/a1ef35bbebbd48a6ad2f00ade3b76595

**Comment by JonnyWong16** [comment]
The actual bug is the setup wizard allowing you to continue without logging into Plex...
