### ISSUE TITLE
Shutdown command doesn't fully execute

### ISSUE THREAD

**Issue by ReenigneArcher** [JonnyWong16/plexpy#1698]
### Describe the Bug

After a Restart command has been called (either by system tray icon or through the web gui), Shutdown does not fully complete.

I am not 100% sure, I believe this is a bug is due to this issue: https://bugs.python.org/issue19124

### Steps to Reproduce

1. Start Tautulli
2. Restart (from tray icon or gui)
3. Wait for Tautulli to return
4. Shutdown (from tray icon or gui)
5. Command never finishes

### Expected Behavior

Ideally for shutdown to exit the program.

### Tautulli Version

2.9.4

### Git Branch

master

### Git Commit Hash

cfd1bf445f7f5332b9183d98ea8893f325c5ca92

### Platform and Version

Windows 11

### Python Version

3.9.6

### Browser and Version

Firefox

### Link to Logs

https://gist.github.com/ReenigneArcher/a1ef35bbebbd48a6ad2f00ade3b76595

**Comment by JonnyWong16** [comment]
I cannot reproduce this. Tautulli shuts down perfectly fine after restarting.

Running v2.9.4 (and v2.9.5) from source using Python 3.9.7 on Windows 10 (not using the exe).

**Comment by ReenigneArcher** [comment]
Weird... I experience it any program that uses `os.execv` (or `subprocess.Popen`) to restart itself. Not necessarily a Tautulli problem. I am using a virtual environment, so not sure if that has a different behavior or not.

Changing this line to `subprocess.call(args, cwd=os.getcwd())` works, and doesn't spawn a new command line.
https://github.com/Tautulli/Tautulli/blob/9a4ca69590bacbbc5ec0076e078b9e38aea85e35/plexpy/__init__.py#L2651

**Comment by ReenigneArcher** [comment]
I tired not using a venv, but that didn't change anything

**Comment by JonnyWong16** [comment]
`subprocess.call()` is blocking whereas `subprocess.Popen()` is non-blocking. You need it to be non-blocking so that the current process can exit otherwise it will always be waiting for the the new process to exit before it can exit itself. You would end up with a chain of Tautulli processes all waiting for each other every time you restart. The new process should have it's own "command line" since it is independent from the original one.

**Comment by ReenigneArcher** [comment]
Yep, you're right! That certainly wouldn't be good... I'm at a loss

**Comment by ReenigneArcher** [comment]
Same thing in a fresh install of Windows 10 and Python 3.9.11

Here you can see that Tautulli ran all of it's code, but the process is still running. This is when a `restart` was issued at some point.
![image](https://user-images.githubusercontent.com/42013603/160263198-2f4f47c5-dae0-4c1b-ac3f-e803a2d7a56b.png)

This is a quit when a restart was never issued.
![image](https://user-images.githubusercontent.com/42013603/160263236-623ef6bc-1178-421e-b604-fda303dc0346.png)

**Comment by JonnyWong16** [comment]
It's exited. Just press enter in the command window. The prompt `>` is just off the screen.

**Comment by ReenigneArcher** [comment]
> It's exited. Just press enter in the command window. The prompt `>` is just off the screen.

You're right, my mistake... interesting behavior of the shell. Just tried in powershell and it's even more buggy.
