### ISSUE TITLE
Plex Full Name showing under Users tab, No longer Plex Username

### ISSUE THREAD

**Issue by zluckytraveler** [JonnyWong16/plexpy#1710]
### Describe the Bug

Since Plex has added the option to add a customized "Full Name" it now shows as the primary name for all users and when checking under the Users tab in Tautulli the "Full Name" is shown rather than the Plex username.

This can be problematic for using "User Conditions" for Notification Agents as a user can add a Full Name later on and it will then change the Friendly Username making the Condition obsolete, needing constant updating.

### Tautulli Version

v2.9.5

### Git Branch

master

### Git Commit Hash

9a4ca69590bacbbc5ec0076e078b9e38aea85e35

### Platform and Version

Linux 5.10.0-0.bpo.11-amd64

### Python Version

3.8.10

### Browser and Version

Safari v15.3

### Link to Logs

https://gist.github.com/zluckytraveler/f608a12aeb06d1eb4b1eb9b18e060639

**Comment by samwiseg0** [comment]
Unfortunately, this is not a bug. There is a difference between a users plex username and friendly name. You (the admin) can set a friendly name for each user that _will not_ change. When a friendly name is not set in Tautulli then the plex username is used instead.

**Comment by zluckytraveler** [comment]
@samwiseg0 This is in regards to the friendly name not being configured at all, and where Tautulli is using the "Full Name" and not the Username as the default friendly username in the Users tab. 

Please refer to the discord messages and the reference that Swift Panda had specifically requested that a bug report be opened.

https://discord.com/channels/183396325142822912/404107332373708800/961886159426957372

**Comment by samwiseg0** [comment]
> @samwiseg0 This is in regards to the friendly name not being configured at all, and where Tautulli is using the "Full Name" and not the Username as the default friendly username in the Users tab.
> 
> Please refer to the discord messages and the reference that Swift Panda had specifically requested that a bug report be opened.
> 
> [discord.com/channels/183396325142822912/404107332373708800/961886159426957372](https://discord.com/channels/183396325142822912/404107332373708800/961886159426957372)

Ah my apologies. I understand the issue now.
