### ISSUE TITLE
Unable to update latest release in snap again.

### ISSUE THREAD

**Issue by DevMan01** [JonnyWong16/plexpy#1715]
### Describe the Bug

Usually I execute a `sudo snap refresh` to update downloads. However the last version, _2.9.5_ had noted upstream issues with snap. And now I'm not seeing this latest release in snap as well. Wondering if the issue is prevailing. 

### Steps to Reproduce

1. `snap list`
2. `sudo snap refresh`

### Expected Behavior

`sudo snap refresh` should pull latest version, expand and install latest version of the Tautulli software release. 

### Screenshots

_CLI commands in gist._

### Relevant Settings

Tautulli installed and managed by snap

### Tautulli Version

v.2.9.6

### Git Branch

master

### Git Commit Hash

dd389b0

### Platform and Version

Ubuntu 18.04.6 LTS

### Python Version

3.6.9

### Browser and Version

Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (x86_64)

### Link to Logs

https://gist.github.com/DevMan01/6419dfdd83363f438c8989cc285c112a

**Comment by JonnyWong16** [comment]
I was moving to a different build process and it took a day to sort itself out. v2.9.6 should be available in the Snap store now.

**Comment by DevMan01** [comment]
Confirmed, thank you
