### ISSUE TITLE
No socket could be created error

### ISSUE THREAD

**Issue by Lucane** [JonnyWong16/plexpy#1721]
### Describe the Bug

This issue started happening about a month or two ago. Tautulli would occasionally shut down with the following error: `Thread-15 : Tautulli WebSocket :: [WinError 10054] An existing connection was forcibly closed by the remote host.`

Any attempts at restarting Tautulli are unsuccessful and the following error is shown: `No socket could be created -- (('0.0.0.0', 8181): [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions)`

The only thing that works is to restart my PC, but that only remedies the issue for a few days until Tautulli gets forcibly shutdown again. I tried to change the port in the config file, but got the same error. Also checked for port conflicts with netstat, but nothing was using the same port. Also tried wiping my Tautulli settings/database and doing a fresh install, but still received the same error.

This is most likely something on my end, but I can't figure out what's causing this.

### Screenshots

![image](https://user-images.githubusercontent.com/7999446/163693431-fd2c6cb7-e754-48ef-b2ba-acf465ad8bce.png)
![image](https://user-images.githubusercontent.com/7999446/163693432-26c09f0b-37c4-4afa-8870-3e628d6dcd6e.png)

### Tautulli Version

v2.9.5

### Git Branch

master

### Git Commit Hash

Can't check (can't start Tautulli)

### Platform and Version

Windows 10 Pro x64 19044.1645

### Python Version

3.8.10

### Browser and Version

Chrome 100.0.4896.88

### Link to Logs

https://gist.github.com/Lucane/5d42be43aad922121a7cb00817eaf996

**Comment by samwiseg0** [comment]
Unfortunately, this is an issue on your host system. Please use discord for support.
