### ISSUE TITLE
Bring back Live Previews from the dead

### ISSUE THREAD

**Issue by mediacenterkodi84** [JonnyWong16/plexpy#1727]
### Is your feature request related to a problem?

I miss…

### What is your feature request?

I always enjoyed being able to watch where my users are in a movie via LIVE PREVIEW. I realize this isn’t essential, but you took it out without even asking the users if we liked it. I did! So my suggestion, add it back, and in the settings allow the user to choose if they want to use it because I am sure there are many that would.

### Are there any workarounds?

if there was a work around I would not have created the feature suggestion for a feature you used to have.

### Additional Context

Let the user decide, no one likes a god complex.

**Comment by samwiseg0** [comment]
Hi @mediacenterkodi84,
> no one likes a god complex.

I am going to give you the benefit of the doubt here and chalk this up to sarcasm/joking… but for future reference this came across very poorly. 

When asking others to take their personal free time to implement something _you are requesting_ it pays to be polite as no one has any obligation to do so.
