### ISSUE TITLE
Newsletters being generated as 300+ MB

### ISSUE THREAD

**Issue by glassbase** [JonnyWong16/plexpy#1729]
### Describe the Bug

I was troubleshooting why my newsletters have not sent in a couple weeks. Started digging.  

Tried to manually send a test newsletter and noticed an error in logs about `Email notification failed: (552, b'5.3.4 Message size exceeds fixed maximum message size', '********@********')`. 

Noticed the HTML file saved in /newsletters grew exponentially over the last few weeks.

Nothing crazy changed on my end. Did not add a crazy amount of media to Plex, been using Imgur for a long time, etc. 

### Steps to Reproduce

1. Newsletters not sending
2. Manual send newsletter and watch logs
3. Logs mention email too large
4. Browse /newsletter folder
5. Files are 300+ MB

### Expected Behavior

Newsletters send :)

### Screenshots

![newsletters](https://user-images.githubusercontent.com/22662527/165131457-171f2fbf-3b4e-4dc2-98e2-1a585defb762.png)

### Tautulli Version

2.9.7

### Git Branch

master

### Git Commit Hash

v2.9.7

### Platform and Version

[Docker] Linux 5.10.21-Unraid (#1 SMP Sun Mar 7 13:39:02 PST 2021)

### Python Version

3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]

### Browser and Version

Chrome 100.0.4896.127 (Official Build) (64-bit)

### Link to Logs

https://gist.github.com/glassbase/0de819d59060baa81f495543d3b9a254

**Comment by glassbase** [comment]
I opened one of the "oversized" HTML files. Noticed the shows listed (not movies) are showing crazy ratings # of stars and percentage. Wondering if this is the issue. See pics attached.

![newsletters2](https://user-images.githubusercontent.com/22662527/165133777-5b5282c1-993c-43e1-a4eb-d6937a8f40c4.png)
![newsletters3](https://user-images.githubusercontent.com/22662527/165133761-10875428-1901-4ff9-b982-c1ade79f55a0.png)

**Comment by JonnyWong16** [comment]
Check your ratings in Plex.

![image](https://user-images.githubusercontent.com/9099342/165132413-952ddc14-53cf-4b0d-8328-4e027bb86c03.png)

**Comment by glassbase** [comment]
Ok, Plex is showing that crazy high rating, Not sure where it came from and happening on multiple shows. Bad metadata scrapping on Plex's end?

**Comment by glassbase** [comment]
Manually refreshing metadata in Plex makes it go away

**Comment by glassbase** [comment]
Browsed Plex libraries, sorted shows by "critic rating" and manually refreshed all shows that had stupid high ratings, newsletter working again, good to go.

Hopefully they helps someone else.

**Comment by alneven** [comment]
> Hopefully they helps someone else.

I started to manually refresh ~30 tv shows

did this problem solved at your end with the bogus ratings or if you update a show with a new episode or there is a new show you still got those %?

**Comment by alneven** [comment]
Update: sadly it doesnt do anything at my side, I tried to refresh the metadata on the gui (three dots, refresh metadata) and with a script to scan refresh section directed to the series main folder and season folder.

![image](https://user-images.githubusercontent.com/16620485/167562606-3451a87e-5bf7-40b7-a625-06177db472da.png)

> May 10, 2022 08:23:43.069 | DEBUG | Request: [127.0.0.1:36794 (WAN)] OPTIONS /library/metadata/58332/refresh
> May 10, 2022 08:23:50.966 | DEBUG | Notification of new metadata for com.plexapp.agents.thetvdb://398140?lang=en [id=58332] (success=1)
> May 10, 2022 08:23:50.968 | DEBUG | Item 58332 (We Own This City) Scanning metadata graphic elements in XML file 
> May 10, 2022 08:23:51.156 | DEBUG | Done with metadata update for 58332
> May 10, 2022 08:23:51.154 | DEBUG | Loaded metadata for We Own This City (ID 58332) in 186ms

**Comment by alneven** [comment]
I've changed the library setting to the new scanner Plex TV Series and now it has the new look and feel
![image](https://user-images.githubusercontent.com/16620485/167572986-2c344f80-83b3-4e29-97e9-abc18fe7057c.png)

... and even though the plex support [website ](https://support.plex.tv/articles/migrating-a-tv-library-to-use-the-new-plex-tv-series-agent-scanner/) says* it won't scan the whole library it does now...


> At this point a scan will be triggered looking for new items but your existing shows will not be changed until you a.) run a Refresh Metadata (per show or on the entire library) or, b.) new episodes are added to an existing show.


Update:
it didn't scanned the whole library, only a few tv shows and which I'm now manually triggering.

**Comment by samwiseg0** [comment]
@alneven please discord for support

Thank you
