### ISSUE TITLE
Missing vp9.png and opus.png images

### ISSUE THREAD

**Issue by tanimislam** [JonnyWong16/plexpy#1740]
### Describe the Bug

Missing the `data/interfaces/default/images/media_flags/video_codec/vp9.png` (for VP9 video codec) and `data/interfaces/default/images/media_flags/audio_codec/opus.png` (the OPUS audo codec) image files.

### Steps to Reproduce

Information on video files (usually WEBM) that use VP9 and OPUS codecs have a `missing icon` default icon for the video and audio codec, respectively.

### Expected Behavior

Once appropriate VP9 and OPUS codec icons exist, the `missing icon` behavior should end..

### Screenshots

![Screen Shot 2022-05-09 at 12 13 45 PM](https://user-images.githubusercontent.com/747905/167481130-e8283cc9-a071-4f50-8234-30ed1c588331.png)

### Tautulli Version

v2.9.7

### Git Branch

master

### Git Commit Hash

b0950abdd9baf8cfa4edd7549e85401e48529fc1

### Platform and Version

Linux 5.4.0-107-lowlatency (#121-Ubuntu SMP PREEMPT Thu Mar 24 16:45:08 UTC 2022 - Ubuntu 20.04 focal)

### Python Version

3.8.10

### Browser and Version

Chrome v100

### Link to Logs

not applicable?

**Comment by JonnyWong16** [comment]
The icons come from Plex Web, but Plex Web stopped showing the icons over 3 years ago so Plex stopped providing new icons. It is very unlikely that I will create my own icons for Tautulli and it is more likely that I will remove the all icons instead.
