### ISSUE TITLE
Recording History of an Item when using a different playback speed then normal

### ISSUE THREAD

**Issue by codwow** [JonnyWong16/plexpy#1751]
### Is your feature request related to a problem?

- Whenever I adjust the playback speed of something I watch within plex (by using a 3rd party extension) Tautulli fails to record any history of the item being played. Tautulli can see me streaming it but for some reason doesnt keep a record of it when the stream has stopped. I know this is a problem due to no users having any differences in the amount of items they have watched, when comparing to plex.

### What is your feature request?

For Tautulli to properly record when I watch something when using a speed other then normal

### Are there any workarounds?

Watch the item at normal speed

**Comment by samwiseg0** [comment]
Please visit the Tautulli discord as this sounds like an issue with your 3rd party player. More diagnosis is needed to determine if this is something that Tautulli can take into account. All playback is determined from plex. If Plex is not reporting it then there is nothing Tautulli can do. Please have your logs ready as we will need to take a look at them.
