### ISSUE TITLE
Interface to email all users in Plex Media Server

### ISSUE THREAD

**Issue by aronmgv** [JonnyWong16/plexpy#1752]
### What is your feature request?

Hello,

From time to time I have a server maintenance and I am missing a convenient way of notifying all my Plex users about the outage.. I have to manually copy all email addresses and send email separately..

I really think the perfect place for this is Tautulli since it syncs all active users and collect contact information about them. I would imagine a separate component somewhere here:
![image](https://user-images.githubusercontent.com/6546231/170280534-516703c0-b940-47bb-a049-3e73f0557568.png)

In that component you can choose which notification source/account to use (like email server etc.) and checkbox which users to notify (all/none/by one).. and of course inputs for Email header and body.

Thanks, Michal

**Comment by JonnyWong16** [comment]
You can already do this with a notification agent.

**Comment by aronmgv** [comment]
Thanks for reply. I have seen it, but is not very intuitive way of doing it.. Only way to do it as you mention is to configure some dummy `notification agent` and use "test notification" card.. Anyway notification agent is for configuring specific notification matching certain criteria, but not for something generic..

**Comment by aronmgv** [comment]
@JonnyWong16 so if I may to ask to reconsider this feature request please. Thanks

**Comment by JonnyWong16** [comment]
There is nothing to reconsider because this feature already exists in Tautulli.
