### ISSUE TITLE
Notification "Plex Server Back Up" after booting server did not work (QNAP TS-873A) 

### ISSUE THREAD

**Issue by cavadoener** [JonnyWong16/plexpy#1761]
### Describe the Bug

The Email Notification "Plex Server Back Up" to send Email did not work. The Notification "Plex Server down" when shut down the Server, works perfekt, also the Test Notification works great. So there is not more to write down. 

### Relevant Settings

Notification Agent = email
Trigger = Plex Server down
Conditions = nothing

TEXT HEADER:
PLEX ({server_name}) ist ONLINE !!

TEXT CONTENT
Hallo Plex Benutzer <p> Der Plex Media Server (MARCO.PLEX) ist ONLINE <p><p> Happy Watching <br /> Marco <br /><br /><br /><br /> Dies ist eine **automatisch generierte Nachricht**

### Tautulli Version

2.10.1

### Git Branch

No information there

### Git Commit Hash

There is no hash if open the QNAP Tautulli Site

### Platform and Version

Linux 5.10.60-qnap 

### Python Version

3.8.6 

### Browser and Version

safari 15.5

### Link to Logs

https://drive.google.com/file/d/1e2XELedYqy9RsNDmn-X5KNGiGLbpVODC/view?usp=sharing

**Comment by JonnyWong16** [comment]
There is no bug here. Your logs show Tautulli is shut down every at 1:30 am and isn't restarted until the next day. The notification is only sent when the Plex server goes down and comes back up while Tautulli stays running.

**Comment by cavadoener** [comment]
What?? 

First: The Server shut down at 01:30 and wake up on the SAME DAY (manually near 10 am) and not on the NEXT day. 

Second: Tautulli could not running if the server goes down. So why Tautulli send no Notification, if the Server is rebooting? So the Notification names "Plex Server Back Up" and not "Remote Access" - and Back Up means the server is ready again - also after a reboot. And if the server is booting, also the QNAP Tautulli app is restarting.

**Comment by JonnyWong16** [comment]
No, that does not count as "back up".
