### ISSUE TITLE
MQTT JSON message is invalid format

### ISSUE THREAD

**Issue by begunfx** [JonnyWong16/plexpy#1763]
### Describe the Bug

The JSON message that is passed via MQTT contains escaped quotes which are causing issues with other programs that are receiving the message and are expecting properly formatted JSON.  

### Expected Behavior

JSON should not have escape characters as part of its payload.   Can you either please remove the escaped quotes or add an option to turn them on/off?

### Tautulli Version

VERSION V2.10.1

### Git Branch

master

### Git Commit Hash

a2c589fca46a83b0a244fcc59774ca7c51289b71

### Platform and Version

[Docker] Linux 3.10.105 (#25556 SMP Sat Aug 28 02:15:59 CST 2021 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.13 (main, May 28 2022, 14:03:04) [GCC 10.2.1 20210110]

### Browser and Version

Version 102.0.5005.61 (Official Build) (x86_64)

### Link to Logs

<script src="https://gist.github.com/begunfx/b19565fe104136fc821dc2104b0595f6.js"></script>

**Comment by JonnyWong16** [comment]
See #1424.
