### ISSUE TITLE
Docker Backup directory

### ISSUE THREAD

**Issue by trackd** [JonnyWong16/plexpy#1764]
### What is your feature request?

It would make more sense to keep the primary data and backups in different locations in case of hardware failure.

So i would like the option to configure the backup directory individually.

Right now when using docker you can only set the config path for all folders (ie rootfolder for logs, backup, cache, exports etc)

-v "path to data:"/config

Adding more volumes in docker is not an issue, however the fields in tautulli are locked with a note "controlled by docker container"

could add support for
-v "path to backup":/backup

or just unlock the fields in UI so we can specify path.

### Are there any workarounds?

unknown

### Additional Context

https://github.com/Tautulli/Tautulli/wiki/Installation#parameters

**Comment by JonnyWong16** [comment]
This is configured via your docker mount. The locked setting is telling to where to mount it inside the container. 

`-v /path/to/backups:/config/backups`
