### ISSUE TITLE
Add option for notificaiton agent to ignore "Recently Added Notification Delay"

### ISSUE THREAD

**Issue by RDslva** [JonnyWong16/plexpy#1780]
### Is your feature request related to a problem?

I am integrating the plex-utils program to add 4K banners to 4K media. This activity is triggered via a Webhook to that application from Tautulli.

Right now, both the webhook notification agent and the other notification agents I have set up to inform users of new content triggers at the same time. This results in the 4K banner being added after the notification to the users.

### What is your feature request?

I would like the ability to tell a notification agent that triggers off the "New Media Added" event to ignore the delay I have previously set.

### Additional Context

The goal would be:

1. New media added
2. Webhook notification immediately triggers, 4K banner is added to new 4K media
3. After the pre-defined delay, all other notifications trigger

This way, when the user notifications trigger, the embedded image has the 4K banner already included.

**Comment by JonnyWong16** [comment]
This isn't possible with the way server websocket events are handled. It would require a complete rewrite of the recently added event system so this won't be something I will be adding. You are better of using a single script notification agent so can handle both notifications sequentially by yourself or a callback from your first script to trigger the second notification agent.
