### ISSUE TITLE
Tautulli Truenas plugin fails to create b/c tautulli"pkg error: - py38"

### ISSUE THREAD

**Issue by MK00000000000000000000** [JonnyWong16/plexpy#1793]
### Describe the Bug

I am using Truenas 13.0U1 I has truenas already installed and working two week s ago, but removed it. Now I need to put it back but keep getting errors on creation...

Errror Message: tautulli had a failure Exception: RuntimeError Message: pkg error: - py38-openssl : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed

Not 100%, but I've tinkered with creating the jail myself and installing all the prerequisite pgkgs...  I think these python packages should be updated to 3.9, or in that Tautulli needs to be updates to support the newer ones since the old ones aren't available (maybe ?)

Thanks!

### Tautulli Version

2.9.7

### Git Branch

Master

### Git Commit Hash

I dont know

### Platform and Version

Truenas 13.0U1

### Python Version

3.8

### Browser and Version

na

### Link to Logs

na

**Comment by JonnyWong16** [comment]
We didn't create the plugin so you will need to contact the person that created it.

For a manual install into a jail, just replace `py38` with `py39` in the installation instructions.

**Comment by MK00000000000000000000** [comment]
understood. Do you happen to know who is responsible for the plugins? Thanks!

**Comment by JonnyWong16** [comment]
I'm not sure.
