### ISSUE TITLE
Tautulli receives trace dump when Exporting Items

### ISSUE THREAD

**Issue by delize** [JonnyWong16/plexpy#1794]
### Describe the Bug

When trying to export library items, the exporter reports back a Failure.

### Steps to Reproduce

[Go to Export tab on Library](https://domain.org/tautulli/library?section_id=1#tab_tabs-export)
Set Level 3 export for metadata, do not export images
Click Export
Wait ~30 to 45 minutes
Recieve failure and trace dump 

### Expected Behavior

Exports occur successfully

### Screenshots

<img width="1661" alt="Screen Shot 2022-07-14 at 08 04 00" src="https://user-images.githubusercontent.com/4028612/178913148-5a959e6d-8a31-46e0-91a5-ab0bdf42e999.png">

### Relevant Settings

Plex Media Server

### Tautulli Version

v2.10.2

### Git Branch

master

### Git Commit Hash

746d44922e1061040e43f1279cb9f1367ef330cd

### Platform and Version

[Docker] Linux 5.4.0-121-generic (#137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022)

### Python Version

3.9.7

### Browser and Version

Chrome 103.0.5060.114

### Link to Logs

https://gist.github.com/delize/73fcea55a31d597fef8be97b528933c8

**Comment by JonnyWong16** [comment]
Looks like the exporter is overloading your Plex server. 

Refer to this Reddit post. 

https://www.reddit.com/r/Tautulli/comments/jo42xx/failing_to_export_metadata_for_movies_library/gbaw089/

**Comment by delize** [comment]
Hm, the tautulli server runs on the same server as the Plex server. Will give the timeout options a go first, and then try the worker_threads and see how that goes. Thanks for the info. 👍

**Comment by delize** [comment]
Just editing the plexapi.config.ini file was enough to correct the issue. 
```
[plexapi]
timeout = 60
```
