### ISSUE TITLE
Provide an option in the settings to change the UI logo

### ISSUE THREAD

**Issue by ChrisColotti** [JonnyWong16/plexpy#1800]
### What is your feature request?

I run an instance of the app just for external user analytics.  Similar to OMBI the users can log in and see their own plays.  I'd love to be able to easily swap the UI logo on the site.  I have the newsletter template done, but there's no easy way to change the UI logo.

### Are there any workarounds?

The only workaround I can see is to add files to the container folder /app/tautulli/data/interfaces/default/images and rename them to the "original" logo files referenced on the site, but as these are in the container not in /config they will get wiped on an update.  I am not sure if I can just mount that path in the container to a volume and have it work ongoing.  

### Additional Context

OMBI supplies the "custom logo" option for the web UI, would be great if this can too.

**Comment by JonnyWong16** [comment]
No, this is not a feature I will add to Tautulli.
