### ISSUE TITLE
Telegram Notifications Limit Rate

### ISSUE THREAD

**Issue by BradleyRL** [JonnyWong16/plexpy#1803]
### Describe the Bug

After updating to the latest version, I'm getting a lot of 429 errors with my telegram notifications.

### Tautulli Version

v2.10.2

### Git Branch

master

### Git Commit Hash

746d44922e1061040e43f1279cb9f1367ef330cd

### Platform and Version

Ubuntu

### Python Version

3.8

### Browser and Version

Chrome

### Link to Logs

https://gist.github.com/BradleyRL/759be71bc5e59d0cf751fcc8ec868e01

**Comment by samwiseg0** [comment]
Based off the small subset of logs this is not a bug in Tautulli. Telegram has a limit of 20 messages per 60 seconds. You will need to reduce the amount of messages you are sending in your notifiers to comply with their limits. 

If you have further questions or need some help on reducing the number of messages please use discord.
