### ISSUE TITLE
Plex Signin - Redirect 404

### ISSUE THREAD

**Issue by war59312** [JonnyWong16/plexpy#1809]
### Describe the Bug

Upon signing in via Plex I am redirected to /redirect?redirect_uri=/get_recently_added?count=50 which is 404 not found.

Full error:

- 404 Not Found
- The path '/redirect' was not found.

### Steps to Reproduce

1.) Sign out if already signed in
2.) Sign in via plex
3.) Right after signed in it redirects to the bad /redirect link.

### Expected Behavior

Sign in and take back to home page without a 404 error page shown.

### Tautulli Version

2.10.2

### Git Branch

master

### Git Commit Hash

746d44922e1061040e43f1279cb9f1367ef330cd

### Platform and Version

[Docker] Linux 3.10.105 (#25556 SMP Sat Aug 28 02:15:59 CST 2021 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.13

### Browser and Version

Chrome 106

### Link to Logs

n/a

**Comment by JonnyWong16** [comment]
I cannot reproduce this issue. Did you bookmark the login page with a bad redirect so everytime you use the bookmark it is wrong?

**Comment by war59312** [comment]
No, always just sitting on /home when it happens. Will try and get more info for you but it's happened last few times when session timed out.

**Comment by JonnyWong16** [comment]
Is it something in your browser? Maybe a browser extension is causing issues? Try a different browser.

**Comment by war59312** [comment]
Could be, chrome just updated a few hours ago and sure enough no such issue when I just signed out and back in.

So perhaps a chrome bug that is now fixed. I changed nothing else.

**Comment by war59312** [comment]
I'm still awaiting a log out event.

**Comment by war59312** [comment]
OK finally happened. And good news, looks like its been fixed between Aug 7 and now. :)

Dev tool shows a 303 redirect to /auth/redirect?redirect_uri=/home and all works now as expected.
