### ISSUE TITLE
Malwarebytes Flags and quarantines Windows installer v2.10.3

### ISSUE THREAD

**Issue by jonnySim** [JonnyWong16/plexpy#1815]
### Describe the Bug

Malwarebytes flagged and quarentined the installer as soon as I tried to run it. 

### Steps to Reproduce

Download windows installer, attempt to execute it, 

Malwarebytes
www.malwarebytes.com

-Log Details-
Protection Event Date: 8/15/22
Protection Event Time: 12:48 AM
Log File: 80c4d156-1c55-11ed-b2b4-d89ef300152b.json

-Software Information-
Version: 4.5.12.204
Components Version: 1.0.1725
Update Package Version: 1.0.58633
License: Premium

-System Information-
OS: Windows 10 (Build 19044.1889)
CPU: x64
File System: NTFS
User: System

-Blocked Malware Details-
File: 1
Malware.AI.395380878, D:\Jon\Downloads\Tautulli\Tautulli-windows-v2.10.3-x64.exe, Quarantined, 1000000, 0, 1.0.58633, C20BFA1699ED05FF1791088E, dds, 01903864, 2E107CF35C1F99B2A93D6B68951A804A, F59D2FC1D7C6AE7924C51EE85E8EEFA64A00E754626672FECE9D6D686C61283A

(end)

### Expected Behavior

new version to be installed. 

### Tautulli Version

2.10.3

### Git Branch

master

### Git Commit Hash

746d44922e1061040e43f1279cb9f1367ef330cd

### Platform and Version

Windows 10 (Build 19044.1889)

### Python Version

3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

### Browser and Version

Brave 1.42.88 Chromium 104.0.5112.81

### Link to Logs

N/A never executed

**Comment by JonnyWong16** [comment]
Report it to Malwarebytes. 

https://forums.malwarebytes.com/topic/270312-false-positive-tautulli/#comment-1527873

**Comment by JamminR** [comment]
This seems to be a larger issue than just MalwareBytes.
https://www.virustotal.com/gui/file/e90ecf89b44f8f7a22481110e64b3946eedbabcc452a49adf9d07ba3b25b714b
As many of us don't have the development skill to review a great codebase like yours, could you please look into what is setting off multiple vendors (though, only 2-3 'sizeable' ones), and make the code less susceptible to alarms.

**Comment by JonnyWong16** [comment]
The only way is to complete scrap creating a Windows exe.

**Comment by jonnySim** [comment]
That is a strange position considering many other open source projects don't have this problem.

**Comment by JonnyWong16** [comment]
Can you point me to one that uses pyinstaller?
