### ISSUE TITLE
LIBRARY STATISTICS No stats to show

### ISSUE THREAD

**Issue by sappleNN** [JonnyWong16/plexpy#1818]
### Describe the Bug

I have checked all the options for Library Statistics in the home page settings, but the home page still does not show the Library Statistics entry, and it says No stats to show.
I don't have any problems with my All Libraries, they are ready to be refreshed and have the correct number of entries. 
The problem is only with Library Statistics
![QQ截图20220818135735](https://user-images.githubusercontent.com/56980316/185307352-1a5ec02a-41be-4972-93e5-46d000d0480e.png)
![QQ截图20220818135753](https://user-images.githubusercontent.com/56980316/185307359-5b03fd6a-ff68-4285-b6ea-f121d2581772.png)
![QQ截图20220818135824](https://user-images.githubusercontent.com/56980316/185307362-46cb308f-6937-4f4c-8ed4-cc01cd3e1a97.png)

### Expected Behavior

I hope this issues will solve my problem of LIBRARY STATISTICS not showing data.

### Tautulli Version

2.10.3

### Git Branch

master

### Git Commit Hash

444b138e97a272e110fcb4364e8864348eee71c3

### Platform and Version

DSM6.2 Docker Linux 4.4.59+

### Python Version

3.9.13

### Browser and Version

Microsoft EDGE 104.0.1293.54

**Comment by sappleNN** [comment]
Everything is fine      after back to 2.10.2

**Comment by JonnyWong16** [comment]
Thanks, there is a bug that will only show library statistics for libraries that have history.
