### ISSUE TITLE
Ability to Ignore Concurrent Stream Notifications for LAN Users or an IgnoreList

### ISSUE THREAD

**Issue by JamoCA** [JonnyWong16/plexpy#1820]
### Is your feature request related to a problem?

When my family arrives home, the main TV in the home is usually set to my Plex account and used while I'm still working and actively listening to PlexAmp.  When this happens, I tend to get notifications after each song is played.  I'm currently using PushBullet and this overload of local warnings has caused me to receive notifications from PushBullet indicating that I'm close or have exceeded my monthly maximum allotment of notifications.  It also takes me a while to manually delete each message from the app. (There's no easy way to select & bulk delete notifications.)

### What is your feature request?

Could either an option to disregard activity from the LAN or an ignore list of usernames be added to suppress concurrent stream notifications?

### Are there any workarounds?

Manually log in and disable the feature if I'm aware that content is being streaming while I'm actively listening to music and then remember to enable it when I'm done... except that I now have no knowledge of concurrent streams from users outside of my LAN.

**Comment by JonnyWong16** [comment]
That's what the conditions are for...

https://github.com/Tautulli/Tautulli/wiki/Custom-Notification-Conditions

**Comment by JamoCA** [comment]
Thanks!  This provides a lot more functionality than what I was requesting.  (I couldn't find this information before.)
