### ISSUE TITLE
Tautulli API -  Get list of media items in playlist.

### ISSUE THREAD

**Issue by James-S-Thrasher** [JonnyWong16/plexpy#1821]
### What is your feature request?

Looking for an API endpoint to return items of a playlist using the `rating_key` provided by the `get_playlists_table`.

**Comment by JonnyWong16** [comment]
I'm pretty sure `get_children_metadata` works with `media_type=playlist` and the `rating_key`.

**Comment by James-S-Thrasher** [comment]
Jonny,

Thank you for your prompt response. I will try and report back.

Respectfully,

 

James

**Comment by James-S-Thrasher** [comment]
I apologize for not following up.

Thank you for your support as your suggestion did work. 

And thank you for all your hard work.
