### ISSUE TITLE
Library Statistics Incorrrect

### ISSUE THREAD

**Issue by rthomasii** [JonnyWong16/plexpy#1824]
### Describe the Bug

![image](https://user-images.githubusercontent.com/11380714/186568642-dea238f4-13a7-434b-8897-10f9871b9508.png)

### Steps to Reproduce

Home page

Appeared after update to VERSION V2.10.3

### Expected Behavior

Zero is not expected.

### Screenshots

![image](https://user-images.githubusercontent.com/11380714/186568829-cc5e311b-e68c-4c1b-b564-a07344ce1fe5.png)

### Tautulli Version

V2.10.3

### Git Branch

Master

### Git Commit Hash

444b138e97a272e110fcb4364e8864348eee71c3

### Platform and Version

Linux Centos 7

### Python Version

Python 2.7.5

### Browser and Version

Chrome Version 104.0.5112.102 (Official Build) (64-bit)

### Link to Logs

https://gist.github.com/rthomasii/babc2f79891fb09b8097d83ea37f6aa5

**Comment by JonnyWong16** [comment]
https://www.reddit.com/r/Tautulli/comments/wpawbz/possible_bug_showing_0_albums_for_all_music/
