### ISSUE TITLE
Stats about subtitle languages

### ISSUE THREAD

**Issue by Xiticks** [JonnyWong16/plexpy#1826]
### What is your feature request?

Hello !

So I don't really know if those 2 features have already been suggested, and I apologize if so.

The first one (but least important for me) is that I don't know if there is any possibilities to edit the history, like what device was use for example. It could help me sorting things. In my case, I just factory reset my phone and so the new name was different from the old one, I changed it after having watch some movies and I would love to just combine these 2 different device (because it's only one)

The second feature I thought was adding the languages and the subtitles used in the history.

I don't know if that's possible, but I would love to have stats about which language was used, with or without the subtitles, and if the subtitles were on, was it only forced (like to translate other language from the audio language currently playing) or full.

It's my first time writing a feature request so I might not have been concise.
Btw I love Tautulli, it's really amazing !

**Comment by JonnyWong16** [comment]
Editing history will not be implemented.

Subtitle language and forced details added to the stream data modal in the next update.
