### ISSUE TITLE
Invalid `custom_conditions` value in API call results in un-deletable (from the GUI) notification agent

### ISSUE THREAD

**Issue by CollinHeist** [JonnyWong16/plexpy#1846]
### Describe the Bug

If an API call to the `set_notifier_config` method is made via the API with an invalid `custom_conditions` argument - e.g. one whose value is __not__ a list of strings - Tautulli will create a notification agent that cannot be deleted from the GUI, and must be deleted via the `delete_notifier` API method.

### Steps to Reproduce

1. Create Python script with the following:
   ```python
   from requests import get
   from json import dumps
   
   api_key = '' # YOUR API KEY
   url = '' # YOUR API URL
   notifier_id = 10 # YOUR NOTIFIER ID
   
   params = {
    'apikey': api_key,
    'cmd': 'set_notifier_config',
    'notifier_id': notifier_id,
    'agent_id': 15,               # Not relevant
    'custom_conditions': dumps([
      {'parameter': 'username', # Can be any parameter
       'operator': 'is',        # Can be any operator
       'value': 'BAD VALUE'},   # This must not be a list, i.e. ['BAD VALUE']
      ]),
   }
   get(url, params=params)
   ```
2. Fill in `api_key`, `url`, and `notifier_id`
3. Run the python file
4. In the Tautulli GUI, navigate to the Notification Agents list
5. Select the agent associated with the above code
6. Observe the `Conditions` tab will have no Condition entries (nor any place to add them):
    <img src="https://user-images.githubusercontent.com/17693271/192059345-cb0165cd-607c-4d99-9456-d26e246e546d.jpg" width="400"/>
7. Attempt to delete the agent via the GUI (nothing will happen) - with the logs showing:
   ```
   WebUI :: /settings#tabs_tabs-notification_agents : TypeError: e.map is not a function. (settings#tabs_tabs-notification_agents line 2 > injectedScript:3)
   ```

### Expected Behavior

I either expect one of the following:

1. The config is rejected completely if an invalid `custom_condition` `value` is sent
2. The config is accepted, but the invalid `custom_condition` is rejected

### Tautulli Version

v2.10.4

### Git Branch

master

### Git Commit Hash

41b796e007764a95a18bc0779f3ef2e02e943bfa

### Platform and Version

[Docker] Linux 5.15.46-Unraid (#1 SMP Fri Jun 10 11:08:41 PDT 2022 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.13 (main, Aug 23 2022, 09:14:58) [GCC 10.2.1 20210110]

### Browser and Version

Firefox 104.0.2 (64-bit)

### Link to Logs

https://gist.github.com/CollinHeist/28ebd43f80065fc7f6977f172a43616c

**Comment by CollinHeist** [comment]
To add to this, if `type` is not provided in the `custom_condition` element, then a `KeyError` will be raised when processing the handler. Traceback is below:
```python
Tautulli NotificationHandler :: Notification thread exception: 'type'
Traceback (most recent call last):
    File "/app/plexpy/notification_handler.py", line 80, in process_queue
        add_notifier_each(**params)
    File "/app/plexpy/notification_handler.py", line 142, in add_notifier_each
        if manual_trigger or notify_custom_conditions(notifier_id=notifier['id'], parameters=parameters):
    File "/app/plexpy/notification_handler.py", line 280, in notify_custom_conditions
        parameter_type = condition['type']
KeyError: 'type' 
```

**Comment by JonnyWong16** [comment]
Please test the `nightly` branch to make sure my fix works properly.

The following conditions will be accepted:

```json
{"parameter": "user", "operator": "is", "value": "person"}
{"parameter": "user", "operator": "is", "value": ["person1", "person2"]}
```

Providing the `type` is not required and will be determined automatically by the server.

The following conditions will be rejected:

```json
{"parameter": "unknown", "operator": "", "value": ""}  // invalid parameter
{"parameter": "user", "operator": "is greater than", "value": ""}  // invalid operator for parameter
{"parameter": "year", "operator": "is", "value": [1990, [2000]]}  // invalid value, nested list
```

**Comment by CollinHeist** [comment]
Sorry for the delay - just tested the `nightly` branch and wasn't able to reproduce any of the previous bugs, so I believe this is fixed. Thanks!
