### ISSUE TITLE
TMDB percentage data out of bounds, causing newsletters to fail

### ISSUE THREAD

**Issue by jorgy80236** [JonnyWong16/plexpy#1847]
### Describe the Bug

I have a job that runs weekly that sends out a newsletter with the content that has been added during that last week.   Some items in the newsletter have many thousands of star ratings, and causes the newsletter to be unreadable on some mail clients.   I am attaching two different newsletters where this is a problem.   The offending lines in the html seem to be many copies of:

`<td class="star-rating full">★</td>`

### Steps to Reproduce

Create a newsletter, only customization is setting up SMTP server.    The bug seems to be related to certain shows, and not others.  

When looking at the shows that have the problems, I see that the rating percentage is > 100%, sometimes much, much > 100%.

### Expected Behavior

I would expect there to be between 1 and 5 stars for a show/movie.   I would expect the percentage from TMDB to be between 1% and 100%.

### Screenshots

<img width="1055" alt="Screen Shot 2022-09-25 at 1 13 48 PM" src="https://user-images.githubusercontent.com/48571812/192161742-3c3e2b94-282d-4081-9d86-849e2975c88d.png">

![Screen Shot 2022-09-25 at 1 26 44 PM](https://user-images.githubusercontent.com/48571812/192161877-449df0ca-7cef-484b-8885-c1119530267f.png)

![Screen Shot 2022-09-25 at 1 26 13 PM](https://user-images.githubusercontent.com/48571812/192161881-71719cde-a525-4592-a83b-6a5734b068b0.png)

### Tautulli Version

v2.10.4

### Git Branch

master

### Git Commit Hash

41b796e007764a95a18bc0779f3ef2e02e943bfa

### Platform and Version

 	[Docker] Linux 4.18.0-372.19.1.el8_6.x86_64 (#1 SMP Tue Aug 2 16:19:42 UTC 2022 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.13 (main, Aug 23 2022, 09:14:58) [GCC 10.2.1 20210110]

### Browser and Version

Firefox 104.0.2 on MacOS Monterey 12.6 x86

### Link to Logs

(notes above say newsletter logs aren't helpful).   Gist is an HTML newsletter example with the problem.    https://gist.github.com/jorgy80236/a89686060261bc49a5740a67a4f5a6c4

**Comment by JonnyWong16** [comment]
Duplicate #1729.
