### ISSUE TITLE
Gotify blank poster image

### ISSUE THREAD

**Issue by Generator** [JonnyWong16/plexpy#1850]
### Describe the Bug

Notification agent for Gotify with 'Include Poster Image' enabled only sends a generic image

NOTES:
Tested with Plex server on local ip (10.0.x.x:32400) and remote address (https://remoteserver.tld:443)

### Steps to Reproduce

1. Create new notification agent (Gotify)
2. Enable 'Include Poster Image'
3. Play any media on Plex

### Expected Behavior

Send/upload the correct poster image

### Screenshots

![Screenshot 2022-09-29 at 14-10-54 Gotify](https://user-images.githubusercontent.com/44146/193046132-1ad266ef-565f-4f92-adb1-a8edbb9c9c30.png)

### Relevant Settings

Plex Media Server 10.0.0.40:32400

### Tautulli Version

v2.10.4

### Git Branch

master

### Git Commit Hash

41b796e007764a95a18bc0779f3ef2e02e943bfa

### Platform and Version

 	Linux 5.15.32-v8+ (#1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 - Debian GNU/Linux 11 bullseye)

### Python Version

 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

### Browser and Version

Firefox 104.0.2

### Link to Logs

https://gist.github.com/Generator/7eaef40f17a20229cc638304d57f4ce7

**Comment by JonnyWong16** [comment]
You don't have image hosting set up. 

https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions#notifications-q7
