### ISSUE TITLE
Notification agent {poster_url} parameter returns empty value

### ISSUE THREAD

**Issue by Generator** [JonnyWong16/plexpy#1851]
### Describe the Bug

Using {poster_url} on a notification agent returns empty

### Steps to Reproduce

1. Create a new notification agent
2. Enable trigger 'Playback Start'
3. Add custom parameter  text ``Poster: {poster_url}`` 
4. Play any media

### Expected Behavior

Show poster URL ex: https://plexserver.tld/../poster.jpg

### Tautulli Version

v2.10.4

### Git Branch

master

### Git Commit Hash

41b796e007764a95a18bc0779f3ef2e02e943bfa

### Platform and Version

Linux 5.15.32-v8+ (#1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]

### Browser and Version

Firefox 104.0.2

### Link to Logs

https://gist.github.com/Generator/7eaef40f17a20229cc638304d57f4ce7

**Comment by JonnyWong16** [comment]
Same as #1850.
