### ISSUE TITLE
Library page requested but no section_id received

### ISSUE THREAD

**Issue by soco1980** [JonnyWong16/plexpy#1852]
### Describe the Bug

In tautulli home page, when I push (in movie or show box) over a section, an error appears: "Error retrieving library information. Please see the logs for more details"
Checking the log it says: "Library page requested but no section_id received"
I didn´t find any information about how to solve the problem, i tried reinstalling but keeps happening.

It happens with all sections, what could be wrong?

### Steps to Reproduce

In home page
Click on any section in movies or tv shows 
Get a "Error retrieving library information. Please see the logs for more details"
Log says "Library page requested but no section_id received"

### Expected Behavior

Loading the page correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/67749247/193250197-86fdfff5-aa76-4bbd-86e7-d5b4c15c339c.png)
![image](https://user-images.githubusercontent.com/67749247/193250258-9a32e12a-38ac-4395-b07a-9e638dcc74a9.png)
![image](https://user-images.githubusercontent.com/67749247/193250345-f895e8f9-5a1c-455a-8d55-bfbcdc124bd5.png)

### Tautulli Version

V2.10.4

### Git Branch

master

### Git Commit Hash

v2.10.4

### Platform and Version

[Docker] Linux 5.10.142+truenas (#1 SMP Mon Sep 26 18:20:46 UTC 2022 - Alpine Linux 3.16.2)

### Python Version

3.10.5 (main, Jul 25 2022, 15:52:08) [GCC 11.2.1 20220219]

### Browser and Version

Chrome Versión 105.0.5195.127 (Build oficial) (64 bits)

### Link to Logs

https://gist.github.com/soco1980/4cb03aba5b7da9c09a11e6bf8bee9f02

**Comment by JonnyWong16** [comment]
I already fixed this. It will be in the next update. 

0f872ab440c186a376d663c2e3394dd70c966f79
