### ISSUE TITLE
404 when accessing library item through the Media Info tab of a library

### ISSUE THREAD

**Issue by sbeck14** [JonnyWong16/plexpy#1863]
### Describe the Bug

While using the Media Info tab of a library, most of the my listed library items link to a dead page instead of the actual media item. 

Searching for the item works fine and viewing the item via the History page works fine. 

For the example library item, the `rating_key` of the real item is `29242` but the key in the link is `22946`.

I'm guessing this has something to do with a screwed up Plex library or something... not sure exactly how to fix this.

### Steps to Reproduce

1. From the Tautulli home page, click on the Libraries tab in the top right hand corner
2. Select a library
3. Select `Media Info` under the library name
4. Hover over a library item without play data to view the invalid thumbnail, and click on it to be taken to a 404 page

### Expected Behavior

I expect that the library item is referenced correctly so that the link works and play metadata is correctly shown

### Screenshots

<img width="1040" alt="Issue Page" src="https://user-images.githubusercontent.com/28632549/195512646-95606541-0b44-44ea-8503-d620c2b5309e.png">

<img width="1044" alt="Error Page" src="https://user-images.githubusercontent.com/28632549/195512662-9dc0981e-8b74-4b35-8677-5d65c275202c.png">

### Relevant Settings

Running in Docker - `inuxserver/tautulli:latest` (`v2.10.4-ls52`)

Tautulli version is `v2.10.4`. I was originally running `v2.1.28` and updated, but the issue persists.

### Tautulli Version

v2.10.4

### Git Branch

master

### Git Commit Hash

v2.10.4

### Platform and Version

[Docker] Linux 4.19.0-22-amd64 (#1 SMP Debian 4.19.260-1 (2022-09-29))

### Python Version

3.10.5 (main, Jul 25 2022, 15:52:08) [GCC 11.2.1 20220219]

### Browser and Version

Firefox 103

### Link to Logs

https://gist.github.com/sbeck14/49157ac96fb6d75eca3be7f45e645ce7

**Comment by samwiseg0** [comment]
This happens when media has been moved/deleted or libraries have been changed/recreated in Plex. 

Please see https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions#move-media

If you need further assistance please use discord for support.
