### ISSUE TITLE
Read http_proxy config from env varibale

### ISSUE THREAD

**Issue by keriati** [JonnyWong16/plexpy#1866]
### Is your feature request related to a problem?

Right now a fresh deployment behind a reverse proxy like Caddy in docker is rather problematic as Tautulli seems to not load in such case until HTTP_PROXY configuration is set to 1.
I couldn't find a way to provide the value for this configuration as an environment variable or as a default.

### What is your feature request?

Add an option to override http_proxy configuration value from environment variables. 

### Are there any workarounds?

RIght now a post init script for a custom docker image could override the default configuration and set http_proxy to 1.

**Comment by JonnyWong16** [comment]
You can pre-create the `config.ini` file.

```ini
[General]
http_proxy = 1
```
