### ISSUE TITLE
Multiple database query errors

### ISSUE THREAD

**Issue by jonleopard** [JonnyWong16/plexpy#1875]
### Describe the Bug

Global/User stats not available on both movie/tv series detail page.  Logs show some errors & warnings returned from the database. 

### Screenshots

<img width="1693" alt="Screenshot 2022-10-27 at 16 22 13" src="https://user-images.githubusercontent.com/2111234/198415701-7ae7c658-685f-44d4-94ca-cae6f54347b6.png">

### Tautulli Version

v2.10.4

### Git Branch

master

### Git Commit Hash

v2.10.4

### Platform and Version

[Docker] Linux 5.4.0-131-generic

### Python Version

3.10.5

### Browser and Version

Firefox v106.0.1 

### Link to Logs

https://gist.github.com/jonleopard/e2a6c4853d12b31cc9f783e21e316176

**Comment by jonleopard** [comment]
Some additional context: This has likely been happening for awhile, I've just never noticed it. I added Tautulli to my Overseerr instance to grab view stats and noticed that the data wasn't getting populated.

**Comment by JonnyWong16** [comment]
Duplicate #1670.
