### ISSUE TITLE
Send a notification if server is overloaded

### ISSUE THREAD

**Issue by ericswpark** [JonnyWong16/plexpy#1881]
### Is your feature request related to a problem?

No notification for server overload exists. If a stream buffers, the user needs to figure out whether it’s because of their Internet or if it’s because the server can’t keep up with the transcode. 

### What is your feature request?

If any of the streams currently being transcoded do not have the minimum value of 1, send a “server overloaded, can’t keep up” warning to notification agents.

### Are there any workarounds?

Manually check the transcode speed.

**Comment by samwiseg0** [comment]
Unfortunately using the buffering trigger is very unreliable. Buffering events are sent for various reasons by the clients.

There are many other ways to deal with a server overload/not being able to keep up with transcodes.

One example would be to know how many streams your server can transcode and use the kill stream script and some well crafted conditions to limit the amount of transcode sessions.

If you would like some more help on trying to solve your particular use cases please feel free to stop by the discord server.

**Comment by ericswpark** [comment]
@samwiseg0 

> Unfortunately using the buffering trigger is very unreliable. Buffering events are sent for various reasons by the clients.

Yes, I've noticed that. But I don't care about the clients buffering because that's on their end (poor connection). That's something that only they can fix and therefore I don't even have the notification trigger enabled for buffering.

I only care about the server not being able to keep up with all the transcode sessions which the users cannot deal with. Only I can fix that, but streaming needs change rapidly hour by hour depending on users online and media type being transcoded. I'd like a notification whenever the server can't keep up, which seems rather simple enough. 

> There are many other ways to deal with a server overload/not being able to keep up with transcodes.
> 
> One example would be to know how many streams your server can transcode and use the kill stream script and some well crafted conditions to limit the amount of transcode sessions.

But again, depending on the media type being transcoded this number of "how many concurrent streams can the server handle" changes. My server can handle downsizing several 1080p streams, but it may choke if it's fed HEVC codecs or if multiple clients stream 4K. 

It'd be great if Tautulli could continuously monitor the transcode speed for me and warn me if any one of them fall below 1.

**Comment by samwiseg0** [comment]
> But again, depending on the media type being transcoded this number of "how many concurrent streams can the server handle" changes. My server can handle downsizing several 1080p streams, but it may choke if it's fed HEVC codecs or if multiple clients stream 4K.

> It'd be great if Tautulli could continuously monitor the transcode speed for me and warn me if any one of them fall below 1.

As I mentioned, you can create custom conditions to meet multiple/many criteria. It will take work on your end but Tautulli is more than capable of doing that kind of customization specific to your environment. 

To your point, defining what dictates "overloading" can/will be different from environment to environment. To my knowledge, Plex does not offer much insight to know if a Plex server is "overloaded". 

In that case I point you back to building that functionality with the very capable tools built into Tautulli.

**Comment by ericswpark** [comment]
> As I mentioned, you can create custom conditions to meet multiple/many criteria. It will take work on your end but Tautulli is more than capable of doing that kind of customization specific to your environment.

I did look at the custom notifications trigger page, but I don’t see an option to monitor the transcode speed. Am I missing something?

> To your point, defining what dictates "overloading" can/will be different from environment to environment. To my knowledge, Plex does not offer much insight to know if a Plex server is "overloaded".

That’s true. But I think starting with “transcode speed falls below 1 on any stream” is a good indicator that the server is “overloaded,” in the sense that it isn’t able to keep up with the clients. 

Sure, there are more “overloaded” situations: maybe the hard drives don’t spin fast enough incurring `iowait`, or maybe the server’s bandwidth can’t handle that many streams at once. But I think a good idea is to start with the first transcode speed criteria and add others as uses come up. 

> In that case I point you back to building that functionality with the very capable tools built into Tautulli.

True, but it would be great if this could be a built-in option that users could enable without the hassle of setting it up.
