### ISSUE TITLE
In "WATCH STATISTICS" cards on home page, retrieve an item from history instead of the Plex Media Server

### ISSUE THREAD

**Issue by acolpan** [JonnyWong16/plexpy#1882]
### Is your feature request related to a problem?

no

### What is your feature request?

In "WATCH STATISTICS" cards (i.e. Most Watched Movies or Recently Watched) on home page, if metadata of an item listed in a card can't be found because it does not exist in the Plex Media Server library or it has been moved, retrieve them from the history. With this change, when an item is deleted from the Plex Media Server, it could be a much better experience than seeing a page where it says " Tautulli cannot find this item's metadata. Either this media item is not available in the Plex Media Server library or it has been moved. Please select the correct match below to update the Tautulli database."

I believe this can easily be achieved by simply appending the "source=history" param to the URL of an item. In fact, this is how it's being done when you go to a user's page and select the History tab, the URLs of the items listed in the Title column in the user's watch history have this additional param "source=history".

**Comment by JonnyWong16** [comment]
I had a reason for not linking to the history years ago, but I don't remember my reasoning anymore. All I remember is that this was intentional.

**Comment by acolpan** [comment]
I am typically deleting any movies I watch in the Plex Media Server. So, unfortunately, all of the links in the cards are being broken not displaying any info or history about the movies deleted while we know these can be reached from the history. If you had a good and intentional reason you can't recall,  can you please make this change configurational and set its behavior to how it's  now by default but providing the opportunity to change it so they're reached from the history? For example, you can add a checkbox option to the bottom of the "WATCH STATISTICS" cards list in "Settings/Homepage" with a label such as "Fetch metadata from history where applicable" so that when it's checked the item links in the relevant cards are generated with an additional param "source=history" otherwise they're generated without (default behavior).
