### ISSUE TITLE
Users > Notes Field & Export

### ISSUE THREAD

**Issue by bombz88** [JonnyWong16/plexpy#1901]
### Is your feature request related to a problem?

Method to add specific notes to user management & export 'All Users' to .csv

### What is your feature request?

I am suggesting a possible 'notes' field or a field area that allows additional information to be entered per user, within the user management section of Tautulli to allow admins to make specific notes relating to the user.

Additional feature possibility
Export 'Users' information columns including notes to a .csv

### Are there any workarounds?

At the time the only method to add additional information is to use the 'edit' username and add all information into the one line, which doesn't fit all specific notes related to the user.

### Additional Context

Dev's to take the lead regarding this request

**Comment by JonnyWong16** [comment]
Duplicate #1566.
