### ISSUE TITLE
Error in disabling trigger for recently added discord notification

### ISSUE THREAD

**Issue by kaitallaoua** [JonnyWong16/plexpy#1905]
### Describe the Bug

When I try to uncheck the box for disabling the recently added trigger and click save, I get the message "There was an error". Looking at the log, it seems to be an internal python error. I have not adjusted this agent for a while in between a few Tautulli and plex updates. Notifications still seem to be working though. I've tried restarting Tautulli and verified the server address. A few other triggers I've tried on my other agents uncheck and save as expect 

Here is a snippet from my logs

2022-11-21 18:30:53 - ERROR   :: ('CP Server Thread-11',) : [21/Nov/2022:18:30:53] HTTP 
Traceback (most recent call last):
  File "cherrypy\_cprequest.py", line 638, in respond
  File "cherrypy\_cprequest.py", line 697, in _do_respond
  File "cherrypy\lib\encoding.py", line 223, in __call__
  File "cherrypy\lib\jsontools.py", line 59, in json_handler
  File "cherrypy\_cpdispatch.py", line 54, in __call__
  File "plexpy\helpers.py", line 83, in wrapper
  File "plexpy\webserve.py", line 3565, in set_notifier_config
  File "plexpy\notifiers.py", line 650, in set_notifier_config
  File "plexpy\notifiers.py", line 736, in validate_conditions
UnboundLocalError: local variable 'parameter_type' referenced before assignment
2022-11-21 18:30:53 - ERROR   :: ('CP Server Thread-12',) : WebUI :: /settings#tabs_tabs-notification_agents : Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON. (settings#tabs_tabs-notification_agents:1)

### Steps to Reproduce

1. Click settings
2. Click "Notification agents
3. Click my discord notification agent settings (agent #1)
4. Click "Triggers" tab
5. Uncheck "Recently Added" box
6. Click save

### Expected Behavior

The save to be successful.

### Relevant Settings

- Discord notification agents
    -  Plex Server Down, Plex Server Back Up, Plex Remote Access Down, Plex Remote Access Back Up: uses discord webhook with default settings
    - Recently Added: discord webhook with default settings
    - Playback Error, Plex Update Available, Buffer Warning, Tautulli Update Available, Tautulli Database Corruption: discord webhook with default settings
- Script agent
    - Playback Pause: kill paused streams, using the "kill_stream.py" script on the wiki, 
    - Playback Start, Playback Pause, Playback Resume, Transcode Decision Change: kill 4k streams using the "kill_stream.py" script on the wiki
    - Plex Server Down: restart plex when it crashes

### Tautulli Version

V2.10.5

### Git Branch

master

### Git Commit Hash

d7f6a1b186250bedbd46ae61888d80597b8ba976

### Platform and Version

Windows 10

### Python Version

3.9.13

### Browser and Version

Chrome 107

### Link to Logs

https://gist.github.com/kaitallaoua/3a2d4d845777666e1fb94c09243da6d9

**Comment by JonnyWong16** [comment]
Check that you don't have an extra blank/unused condition set for the agent.

Try removing and re-adding your conditions.

**Comment by kaitallaoua** [comment]
I have no conditions for this agent. However I do notice that the operator field is empty and I can't click the "-- Operator --" option (does nothing) to restore it to the default. On other working agents that "-- Operator --" place holder is there.

This is what it looks like now
https://ibb.co/PmMfnxd

edit: I just tried removing then adding the empty condition so the placeholder is there, but when saving I get the same error

**Comment by JonnyWong16** [comment]
The missing placeholder is the issue. I don't know how you got into a that state with a blank operator. I can't reproduce it.

Can you save with any random condition? Can you then remove that random condition and save again?

**Comment by kaitallaoua** [comment]
> Can you then remove that random condition and save again?

Tried it already but tried it again and it worked. Not sure what the issue was, but ill close this now.
