### ISSUE TITLE
Add a "recently removed/deleted" notification trigger

### ISSUE THREAD

**Issue by mackiser** [JonnyWong16/plexpy#1906]
### Add a "recently removed/deleted" notification trigger

would be nice to have this option alongside the "Recently Added" trigger

### Are there any workarounds?

not that I know of

### Additional Context

![recently_removed](https://user-images.githubusercontent.com/2199450/203393249-70a58072-8b13-4ce8-bd93-b59435c2bceb.PNG)

**Comment by JonnyWong16** [comment]
This has already been brought up before and it isn't feasible. Tautulli would need to store a copy of your entire Plex database in order to determine what has been removed.

**Comment by mackiser** [comment]
Roger that! Thanks for the response
