### ISSUE TITLE
Newsletter header does not point to correct image

### ISSUE THREAD

**Issue by DCarlson12** [JonnyWong16/plexpy#1919]
### Describe the Bug

Editing the path of the newsletter header image in the recently_added.html after pointing the config.ini to get custom newsletter template data from data/interfaces/custom-newsletter does not produce the desired header image in the **emailed** newsletter. The preview newsletter however **does** show the correct header image. Trying to point the backup image directory (the Tautulli web URL header image) in the html to the full path of the resource produces a blank image.

### Steps to Reproduce

1. Create a custom newsletter directory in ./Tuatulli/data/interfaces
2. Copy the template html files from the original newsletters directory into the new directory.
3. Edit the custom html files to point to the name of the new header image.
4. Stop Tautulli
5. Edit the config.ini file(s) newsletter_templates parameter to the name of the custom newsletter directory folder.
6. Start Tautulli
7. Generate a newsletter -> Correct header image
8. Test a newsletter -> Tautulli image or no image is the header image

### Expected Behavior

The custom header image should be used when an actual newsletter is sent.

### Screenshots

Custom Newsletter File Preview Newsletter
![image](https://user-images.githubusercontent.com/64709964/206048324-e38e52e8-d291-491f-b14f-4e1a28a96756.png)

Same custom newsletter file but using the test newsletter button. The emailed html, backup header image URL is Tautulli website (default)
![image](https://user-images.githubusercontent.com/64709964/206048191-1fe7ba63-f374-4dc2-b037-ff0f9e2d325e.png)

Same custom newsletter file but using the test newsletter button. The emailed html, backup header image URL is local path to image.
![image](https://user-images.githubusercontent.com/64709964/206048264-41debcb3-a3ac-4f67-af73-9ef830c69b4d.png)

### Tautulli Version

2.10.5

### Git Branch

master

### Git Commit Hash

d7f6a1b186250bedbd46ae61888d80597b8ba976

### Platform and Version

Windows 11

### Python Version

3.9.13

### Browser and Version

Chrome 108.0.5359.94

### Link to Logs

https://gist.github.com/DCarlson12/855975e161b422ef247895b99fb558c7#file-tautulli-log

**Comment by samwiseg0** [comment]
For future reference. We do not provide support with custom newsletters and this is not a bug since the default template works as expected. 

This is almost always an error in the custom template.
