### ISSUE TITLE
export Metadata with more than 1000 items in Library not possible

### ISSUE THREAD

**Issue by djmarc75** [JonnyWong16/plexpy#1927]
### Describe the Bug

I am using JSON from my Libraries to visualize in other Applications. Since yesterday i´ve reached a "level" with more than 1000 items in my Library.
Today i tried to export Metadata again and the Process stopped at 99% with an error (see log).

Deleted some Movies to have less than 1000 Items - no Error and Export was succesful !

### Steps to Reproduce

1. Go to "Libraries" and select the Library.
2. Select "Export"
3. Select "Export metadata"
4. Select your favorite Format and your favorite Metadata to export (in my case JSON)
5. Click "Export"

### Screenshots

![Screenshot 2022-12-16 093930](https://user-images.githubusercontent.com/59453843/208063469-e8cbb45e-23f3-48f3-9af5-26970dc4da26.png)
![Screenshot 2022-12-16 094832](https://user-images.githubusercontent.com/59453843/208063471-dc614d3c-fcb0-460f-90c3-fa0c136fb23d.png)
![Screenshot 2022-12-16 095637](https://user-images.githubusercontent.com/59453843/208063473-4e4b35e1-cbff-42f3-8cef-902eba806904.png)

### Tautulli Version

V2.10.5

### Git Branch

master

### Git Commit Hash

d7f6a1b186250bedbd46ae61888d80597b8ba976

### Platform and Version

Linux 5.15.61-v8+ (#1579 SMP PREEMPT Fri Aug 26 11:16:44 BST 2022 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.2

### Browser and Version

Firefox 108.0

### Link to Logs

https://gist.github.com/djmarc75/145bb3f83f4b084a3d85a82aa1154e02

**Comment by JonnyWong16** [comment]
Duplicate #1794.
