### ISSUE TITLE
Unable to start -  AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by martijngoorman** [JonnyWong16/plexpy#1947]
### Describe the Bug

After update to the latest version, Tautulli is not able to start.

### Expected Behavior

Service starting

### Relevant Settings

 systemd: Started Tautulli - Stats for Plex Media Server usage.
 python3: Traceback (most recent call last):
 python3: File "/opt/Tautulli/Tautulli.py", line 39, in <module>
 python3: import plexpy
 python3: File "/opt/Tautulli/plexpy/__init__.py", line 67, in <module>
 python3: from plexpy import activity_handler
 python3: File "/opt/Tautulli/plexpy/activity_handler.py", line 37, in <module>
 python3: from plexpy import activity_processor
 python3: File "/opt/Tautulli/plexpy/activity_processor.py", line 32, in <module>
 python3: from plexpy import database
 python3: File "/opt/Tautulli/plexpy/database.py", line 31, in <module>
 python3: from plexpy import helpers
 python3: File "/opt/Tautulli/plexpy/helpers.py", line 24, in <module>
 python3: import arrow
 python3: File "/opt/Tautulli/lib/arrow/__init__.py", line 2, in <module>
 python3: from .api import get, now, utcnow
 python3: File "/opt/Tautulli/lib/arrow/api.py", line 12, in <module>
 python3: from arrow.arrow import TZ_EXPR, Arrow
 python3: File "/opt/Tautulli/lib/arrow/arrow.py", line 35, in <module>
 python3: from arrow import formatter, locales, parser, util
 python3: File "/opt/Tautulli/lib/arrow/formatter.py", line 10, in <module>
 python3: from arrow import locales
 python3: File "/opt/Tautulli/lib/arrow/locales.py", line 20, in <module>
 python3: from typing_extensions import Literal
 python3: File "/opt/Tautulli/lib/typing_extensions.py", line 193, in <module>
 python3: class _FinalForm(typing._SpecialForm, _root=True):
 python3: AttributeError: module 'typing' has no attribute '_SpecialForm'
 systemd: tautulli.service: main process exited, code=exited, status=1/FAILURE
 systemd: Unit tautulli.service entered failed state.
 systemd: tautulli.service failed.

### Tautulli Version

v2.11.1

### Git Branch

master

### Platform and Version

CentOS Linux release 7.9.2009 (Core)

### Python Version

Python 3.6.8

### Typing-extensions
pip3 show typing-extensions
Name: typing-extensions
Version: 4.1.1
Summary: Backported and Experimental Type Hints for Python 3.6+
Home-page: None
Author: None
Author-email: "Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Michael Lee" <levkivskyi@gmail.com>
License: None
Location: /usr/local/lib/python3.6/site-packages
Requires:

-

**Comment by JonnyWong16** [comment]
Duplicate #1946
