### ISSUE TITLE
Add Option to disable "Tautulli Updated to xx.xxx" login prompt after updates

### ISSUE THREAD

**Issue by ghost** [JonnyWong16/plexpy#1950]
### Is your feature request related to a problem?

I run Tautulli in docker and use WatchTower to automatically keep it up-to-date. I don't need to see a prompt after a new version is installed, I use the Docker/WatchTower mechanism for a seamless patching experience and I find that this prompt is more an annoyance, if I want to review the patch notes I will seek these out.

### What is your feature request?

An option under **Settings** -> **General** -> **UPDATES**: "**Show Update Prompts**"
_Enable to show Release Notes prompt at login when Tautulli is updated._

This can be enabled by default, and then users can choose from there.

### Are there any workarounds?

None that I've been able to find.

**Comment by JonnyWong16** [comment]
I won't be changing the behaviour of the update changelog modal.
