### ISSUE TITLE
History filter... by list or by no included

### ISSUE THREAD

**Issue by jpneergaard** [JonnyWong16/plexpy#1952]
### Is your feature request related to a problem?

It is difficult to look at the history of only others who are using the plex server.  It would be very helpful to filter by everyone except me, or everyone except these people. 

### What is your feature request?

When looking at the history page, there is the pulldown to select ALL USERS or an individual users.  My request is to be able to select a list of users (add check boxes next to the names).  Or, perhaps have an option to show everyone EXCEPT the selected user.

**Comment by JonnyWong16** [comment]
Duplicate #1645.
