### ISSUE TITLE
websocket communication not using https

### ISSUE THREAD

**Issue by andrasg** [JonnyWong16/plexpy#1953]
### Describe the Bug

I have a Plex setup with a custom URL, custom publicly valid cert matching the URL, remote access disabled in Plex and an nginx proxying all connections to Plex.

The setup is working as expected with all Plex clients, no issues with playing content and I am seeing successful websocket communications to Plex.

When setting up Tautulli, I am selecting my Plex server from the dropdown, ensuring use secure connection is enabled and clicking verify. I get an error message that says Plex server is found but unable to communicate with websocket.

In the https publishing logs (nginx), I am seeing an initial successful call to /identity

```
[02/Jan/2023:00:09:40 +0100] 172.17.0.1 -> https://plex.mydomain.eu:443 -> 192.168.20.80:32400 "GET /identity HTTP/1.1" 200 rt:0.004 ct:0.002 urt:0.004 sb:169 ua:"python-requests/2.28.1" u:-
```

But afterwards http 400 bad requests when trying the websocket:

```
[02/Jan/2023:00:10:52 +0100] 172.17.0.1 -> http://plex.mydomain.eu:443 -> - "GET /status/sessions HTTP/1.1" 400 rt:0.000 ct:- urt:- sb:255 ua:"python-requests/2.28.1" u:-
[02/Jan/2023:00:10:52 +0100] 172.17.0.1 -> http://plex.mydomain.eu:443 -> - "GET /:/websockets/notifications HTTP/1.1" 400 rt:0.000 ct:- urt:- sb:255 ua:"-" u:-
```

Notice here that nginx replies with a http 400 (bad request) as a wrong combination of port and scheme (http) is used. 

At the same time, Tautulli logs show:

```
Websocket connection test failed: Handshake status 400 Bad Request
Testing secure websocket connection...
Tautulli Config :: Writing configuration to file
Tautulli PlexTV :: Requesting resources for server...
IP Checker :: Resolved plex.mydomain.eu to 192.168.20.33.
```

Why is tautulli not using https to obtain sessions and communicate with the websocket?

### Steps to Reproduce

1. disable remote access in plex
2. use custom url
3. use custom, publicly valid cert
4. use nginx to proxy https requests to plex's IP:32400
5. select plex server in tautulli and click verify server

### Expected Behavior

Tautulli uses secure connection (https) to talk to Plex and successfully verifies the connection

### Relevant Settings

- Plex: 192.168.20.80:32400 - running in an LXC container
- nginx IP: 192.168.20.33 (plex.mydomain.eu points to this)
- nginx proxying everything arriving to https://plex.mydomain.eu:443 to https://192.168.20.80:32400
- nginx correctly setup to proxy websocket connections

### Tautulli Version

v2.11.1

### Git Branch

master

### Git Commit Hash

v2.11.1

### Platform and Version

[Docker] Linux 5.15.0-56-generic (#62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 - Alpine Linux 3.17.0)

### Python Version

3.10.9 (main, Dec 12 2022, 17:52:15) [GCC 12.2.1 20220924]

### Browser and Version

Safari latest

### Link to Logs

https://gist.github.com/andrasg/419ac4103c8226b047a6ab5714cade1c

**Comment by andrasg** [comment]
Interestingly, the `config.ini` file of tautulli also contains the wrong URL `http://plex.mydomain.eu:443`. If I edit the file and change the scheme to https, start Tautulli, all is fine, Tautulli connects to Plex successfully.

**Comment by JonnyWong16** [comment]
Have you added your custom server access URL (with https) in your Plex server settings > Network?

**Comment by andrasg** [comment]
Verified in `resources.xml` that the connection is supposed to be https:

```xml
<Device name="Plex" product="Plex Media Server" productVersion="1.30.1.6497-5fc2e0894" platform="Linux" platformVersion="22.04.1 LTS (Jammy Jellyfish)" device="PC" clientIdentifier="<id>" createdAt="1575326508" lastSeenAt="1672609829" provides="server" owned="1" accessToken="<accesstoken>" publicAddress="<publicip>" httpsRequired="1" synced="0" relay="0" dnsRebindingProtection="0" natLoopbackSupported="0" publicAddressMatches="1" presence="1">
<Connection protocol="https" address="plex.mydomain.eu" port="443" uri="https://plex.mydomain.eu" local="0"/>
</Device>
```

**Comment by andrasg** [comment]
> Have you added your custom server access URL (with https) in your Plex server settings > Network?

Yes, custom url set to `https://plex.mydomain.eu`

**Comment by JonnyWong16** [comment]
Check "Use manual connection" (show advanced) in the Tautulli settings to use a custom domain.

**Comment by andrasg** [comment]
Thanks, worked. Any idea why the automatic detected access details fail?

**Comment by JonnyWong16** [comment]
It only checks for secure `*.plex.direct` addresses.
