### ISSUE TITLE
Docker repository not updating frequently

### ISSUE THREAD

**Issue by SpookyUSAF** [JonnyWong16/plexpy#1972]
### Describe the Bug

ghcr.io/tautulli/tautulli is still pulling 2.10.5 as the current version. Is this expected?

### Steps to Reproduce

Update container

### Expected Behavior

Container should be updated to most current version

### Tautulli Version

2.10.5

### Git Branch

master

### Git Commit Hash

d7f6a1b186250bedbd46ae61888d80597b8ba976

### Platform and Version

	[Docker] Linux 4.4.180+ (#42962 SMP Tue Oct 18 15:07:03 CST 2022 - Debian GNU/Linux 11 bullseye)

### Python Version

3.9.15 (main, Oct 25 2022, 05:49:37) [GCC 10.2.1 20210110]

### Browser and Version

Edge Version 108.0.1462.76 (Official build) (64-bit)

### Link to Logs

not relevant

**Comment by JonnyWong16** [comment]
Nope, Docker image is fine. 

https://github.com/Tautulli/Tautulli/pkgs/container/tautulli/60253060?tag=v2.11.1
