### ISSUE TITLE
Support for Jellyfin

### ISSUE THREAD

**Issue by matkeith** [JonnyWong16/plexpy#1999]
### What is your feature request?

as a user I'd like to be able to view my plex and jellyfin activity in Tautulli as a centralized place. Can you implement support for Jellyfin's API to gather watch data?

Their API is documented here:
https://api.jellyfin.org/

### Additional Context

I run plex and jellyfin simultaneously but would like to see viewing history and data from both applications in the same place as they share the same purpose. Eventually i'd like to move to just using jellyfin

**Comment by JonnyWong16** [comment]
Duplicate #1597.
