### ISSUE TITLE
Cannot run exporter with Snap package

### ISSUE THREAD

**Issue by aylvisaker** [JonnyWong16/plexpy#2007]
### Describe the Bug

Permission issue. Possibly snap related. Cannot export a media library (large or small) to csv.

### Steps to Reproduce

1. Export a movie library to csv with all default values.
2. Progress stuck at 0%.
3. Permission error appears in log.
4. After reset of Tautulli via web interface, export shows as failed.

### Expected Behavior

A csv file of movies with default values of metadata and media info.

### Tautulli Version

v2.11.1

### Git Branch

master

### Git Commit Hash

3c996f01a9fe15466978781022fdbb00d1e189a9

### Platform and Version

Linux 5.15.0-60-generic (#66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 - Ubuntu Core 20)

### Python Version

3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]

### Browser and Version

Firefox 109.0.1 (snap)

### Link to Logs

https://gist.github.com/aylvisaker/842bf7434831bced6b16e066524a044b

**Comment by JonnyWong16** [comment]
Reference: https://forum.snapcraft.io/t/python-multiprocessing-permission-denied-in-strictly-confined-snap/15518/2

**Comment by JonnyWong16** [comment]
Fixed ref: 993909fa089dcbb21b7d80c46d9f784ad6aeefe9
