### ISSUE TITLE
Show the reason for transcode

### ISSUE THREAD

**Issue by goellnjh** [JonnyWong16/plexpy#2008]
### Is your feature request related to a problem?

I'm annoyed when a file is being transcoded for a player client. Many times player client operators are non-technical and don't realize that they're putting perhaps an undue load on the server. I'd like to know the reason WHY a transcode is occurring and have that in the history information so server operators can evaluate what is causing transcodes to happen and then make adjustments or corrections to server settings or media to relieve the extra load.

### What is your feature request?

In active sessions listed on the "home" tab, I'd like to see a transcode reason in either a hover-over information icon near transcode word or on it's own line why a transcode is happening - such as "Transcode due to burning subtitles" or "Transcode due to incompatible codec" or "Transcode due to client bandwidth limitations" or "Transcode due to server bandwidth limitations".

On the history tab, when clicking on the device in the "Player" column, I'd like to see detailed information in the drill down dialog that shows the reason for the transcode here also.  You can see in this example, it "seems" like there should not be a transcode happening, so why did the server transcode this media file?
![image](https://user-images.githubusercontent.com/95938343/221217007-7b67ab50-77bb-4f00-a4c3-25428715d657.png)

**Comment by samwiseg0** [comment]
> In active sessions listed on the "home" tab, I'd like to see a transcode reason in either a hover-over information icon near transcode word or on it's own line why a transcode is happening - such as "Transcode due to burning subtitles" or "Transcode due to incompatible codec" or "Transcode due to client bandwidth limitations" or "Transcode due to server bandwidth limitations".

Unfortunately this information is not provided by Plex in their API. You would have to comb the logs to determine the exact reason a particular session has been transcoded. This happens at the time when the stream is started. 

This is not something Tautulli would be able to do in general as there are no good ways to pull that information today. 

In most cases you can deduce why something is being transcoded.

**Comment by samwiseg0** [comment]
> You can see in this example, it "seems" like there should not be a transcode happening, so why did the server transcode this media file?

If you look at the quality section under transcode  you will see that the quality profile is set to 4Mbps. The source file is _over_ that limit so the server decided to transcode the stream down to fit into a 4Mbps stream. 

Feel free to use discord when you have questions like these.

**Comment by goellnjh** [comment]
Ok thanks

**Comment by seth586** [comment]
This would be a valuable feature if tautulli was running on the same machine, it could monitor logs. Even remote servers could just grep the appropriate log info and forward.

**Comment by samwiseg0** [comment]
> This would be a valuable feature if tautulli was running on the same machine, it could monitor logs. Even remote servers could just grep the appropriate log info and forward.

This would be considered a "hack" and not something we would consider putting in Tautulli. 

Proper support by plex is what would be needed.

**Comment by paulverbeke** [comment]
> In most cases you can deduce why something is being transcoded.

If we can deduce the transcode reason in most cases using the data available, could Tautulli be doing the preliminary homework for us and display a "probable reason for video transcode is...":
- resolution not supported
- subtitle not supported, burning necessary
- video codec not supported

With a preemptive warning for other reasons we may be missing data for, like:
- client bandwidth
- server bandwidth setting
- client settings (remote/data/home)
- quality profile in player

I'm sure I'm wrong and you'll explain me what I'm missing here.
Thanks a lot
