### ISSUE TITLE
errors after upgrading to latest sqlite3 (which disabled DSQ by default)

### ISSUE THREAD

**Issue by mvanbaak** [JonnyWong16/plexpy#2015]
### Describe the Bug

Latest sqlite3 disabled DSQ by default. Now parts of tautulli have errors:
```
2023-03-06 11:11:20 - ERROR   :: ('CP Server Thread-7',) : Tautulli Database :: Database error: no such column: movie
2023-03-06 11:11:20 - WARNING :: ('CP Server Thread-7',) : Tautulli DataFactory :: Unable to execute database query for get_home_stats: top_movies: no such column: movie.
```

Also, history wont load (same error)

### Steps to Reproduce

- Update to latest sqlite3 with DSQ disabled (the default in latest FreeBSD for example)
- Open tautulli webinterface
  - What I noticed is that I needed to login again
- Go to `History` using the menu at the top

### Expected Behavior

- history populated
- no errors in log about missing column movie

### Tautulli Version

v2.10.3

### Git Branch

tags/2.10.3

### Git Commit Hash

444b138e97a272e110fcb4364e8864348eee71c3

### Platform and Version

FreeBSD 13.1 amd64

### Python Version

3.9.16

### Browser and Version

Safari Version 16.3 (18614.4.6.1.6)

### Link to Logs

https://gist.github.com/mvanbaak/ae3536fc3718777f24c8f740264df09f

**Comment by mvanbaak** [comment]
Updated tautulli to latest stable (2.11.1) and still a problem. I updated the gist to include the logs of the new tautulli version as well.

**Comment by clausecker** [comment]
See https://www.sqlite.org/quirks.html#dblquote for an explanation of the DQS misfeature.  To fix this problem, either enable DQS in your database connection or better fix the code not to use double quoted strings.

**Comment by JonnyWong16** [comment]
Could you just confirm your sqlite version for me?

```
python -c "import sqlite3; print(sqlite3.sqlite_version)"
```

**Comment by clausecker** [comment]
We currently [ship](https://www.freshports.org/databases/sqlite3) sqlite3 version 3.41.0.  Please wait for @mvanbaak to confirm.

**Comment by mvanbaak** [comment]
```bash
root@tautulli:~ # python3.9 -c "import sqlite3; print(sqlite3.sqlite_version)"
3.41.0
root@tautulli:~ # pkg info sqlite3
sqlite3-3.41.0,1
Name           : sqlite3
Version        : 3.41.0,1
Installed on   : Wed Mar  8 08:32:13 2023 CET
Origin         : databases/sqlite3
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : databases
Licenses       : PD
Maintainer     : pavelivolkov@gmail.com
WWW            : https://www.sqlite.org/
Comment        : SQL database engine in a C library
Options        :
        ARMOR          : off
        DBPAGE         : on
        DBSTAT         : on
        DIRECT_READ    : off
        DQS            : off
        EXAMPLES       : on
        EXTENSION      : on
        FTS3_TOKEN     : on
        FTS4           : on
        FTS5           : on
        GEOPOLY        : off
        ICU            : off
        LIBEDIT        : on
        LIKENOTBLOB    : off
        MEMMAN         : off
        METADATA       : on
        NORMALIZE      : off
        NULL_TRIM      : off
        OFFSET         : off
        RBU            : off
        READLINE       : off
        RTREE          : on
        RTREE_INT      : off
        SECURE_DELETE  : on
        SESSION        : off
        SORT_REF       : off
        SOUNDEX        : off
        STAT3          : off
        STAT4          : off
        STATIC         : off
        STMT           : off
        STRIP          : on
        TCL            : off
        THREADS        : on
        TRUSTED_SCHEMA : off
        TS0            : off
        TS1            : on
        TS2            : off
        TS3            : off
        UNICODE61      : on
        UNKNOWN_SQL    : off
        UNLOCK_NOTIFY  : on
        UPDATE_LIMIT   : off
        URI            : on
        URI_AUTHORITY  : off
Shared Libs required:
        libedit.so.0
Shared Libs provided:
        libsqlite3.so.0
Annotations    :
        FreeBSD_version: 1301000
        build_timestamp: 2023-03-06T11:10:15+0000
        built_by       : poudriere-git-3.3.99.20220831
        flavor         : default
        port_checkout_unclean: no
        port_git_hash  : 47912ce2e613
        ports_top_checkout_unclean: no
        ports_top_git_hash: aa5ab230785d
        repo_type      : binary
        repository     : poudriere
Flat size      : 5.61MiB
Description    :
SQLite is an SQL database engine in a C library. Programs that link the SQLite
library can have SQL database access without running a separate RDBMS process.
The distribution comes with a standalone command-line access program (sqlite3)
that can be used to administer an SQLite database and which serves as an
example of how to use the SQLite library.

WWW: https://www.sqlite.org/
root@tautulli:~ #
```

**Comment by Jon87** [comment]
I also have this issue. Last night's update to v2.12 seems to have made it worse as Tautulli won't start afterwards and is giving errors about the database missing table SDR and on_intro.

**Comment by mvanbaak** [comment]
https://cgit.freebsd.org/ports/commit/?id=5fd5f3398b665540ed77893b792e7372f8087f2f

I can confirm this 'fixes' the issue.
Tautulli should still make changes so it works with this disabled, but it's a little less urgent now.

**Comment by JonnyWong16** [comment]
Thanks. It will take quite some time to fix all the SQL queries in Tautulli.

**Comment by JonnyWong16** [comment]
Is someone able to test the changes in #2057 to make sure I didn't miss anything.

I have been unsuccessful in attempting to test my changes. I cannot figure out a way to downgrade the `sqlite3` port and compiling from source fails in a TrueNAS 13.1 jail. I cannot test on Windows because the precompiled `sqlite3.dll` has DQS on.

**Comment by Jon87** [comment]
Think my last comment was marked off topic but is related to this issue.
I can test if you're looking for someone with current sqlite? Or did you mean you wanted someone with the previous version running where DQS is off as downgrading is an issue in truenas?

**Comment by JonnyWong16** [comment]
I need to test with DQS off. We already know Tautulli works with DQS on.

**Comment by clausecker** [comment]
@JonnyWong16 What's the error when compiling in the TrueNAS jail?  Did you update the ports tree to the latest commit?  You should be able to just turn the DQS option on in the port and then build it (`make all deinstall install` as root).

**Comment by JonnyWong16** [comment]
Yes, my ports tree is up-to-date.

I have the exact same error as this post:
https://www.truenas.com/community/threads/problems-with-dtrace-in-poudriere-jail.101107/

```zsh
root@tautulli-dqs:/usr/ports/databases/sqlite3 # make all deinstall install
===>   sqlite3-3.41.0,1 depends on executable: tclsh8.6 - not found
===>  Building for tcl86-8.6.13
/usr/sbin/dtrace -h  -o tclDTrace.h -s /usr/ports/lang/tcl86/work/tcl8.6.13/generic/tclDTrace.d
dtrace: failed to compile script /usr/ports/lang/tcl86/work/tcl8.6.13/generic/tclDTrace.d: "/usr/lib/dtrace/ipfw.d", line 1: syntax error near "in_addr_t"
*** [tclDTrace.h] Error code 1

make[4]: stopped in /usr/ports/lang/tcl86/work/tcl8.6.13/unix
1 error

make[4]: stopped in /usr/ports/lang/tcl86/work/tcl8.6.13/unix
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[3]: stopped in /usr/ports/lang/tcl86
*** Error code 1

Stop.
make[2]: stopped in /usr/ports/lang/tcl86
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/databases/sqlite3
*** Error code 1

Stop.
make: stopped in /usr/ports/databases/sqlite3
```

Edit: Never mind, I got it. Needed `pkg install tcl86`.
