### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by JSouthGB** [JonnyWong16/plexpy#2020]
### Describe the Bug

The 'new release available' pop up in the lower right of the browser window directs to a 404 page. In both the pop up for v2.12.0 and v2.12.1.

### Steps to Reproduce

1. Have upgrade to v2.12.0 or v2.12.1 available.
2. Click the "new release (v2.12.x)" link in the notification pop up.
3. Be redirected to `https://nullreferer.com/?https://github.com/Tautulli/Tautulli/releases/tag/v2.12.1`

### Expected Behavior

Expect to be redirected to a valid page, i.e. `https://github.com/Tautulli/Tautulli/releases/tag/v2.12.1`

### Screenshots

![tautulli upgrade popup](https://user-images.githubusercontent.com/22480336/225166470-62a17f99-2839-47b6-bb39-70c0eb11d447.png)
![nullreferrer link](https://user-images.githubusercontent.com/22480336/225166480-946a32e3-081a-484b-80a7-4995cd0c3294.png)

### Tautulli Version

v2.12.0

### Git Branch

master

### Git Commit Hash

41f935e

### Platform and Version

Docker

### Python Version

Docker

### Browser and Version

Firefox 110

### Link to Logs

Not relevant, nothing showing in logs.

**Comment by JonnyWong16** [comment]
Seems like an issue on your end.

This URL works fine: https://nullreferer.com/?https://github.com/Tautulli/Tautulli/releases/tag/v2.12.1

**Comment by JSouthGB** [comment]
> Seems like an issue on your end.
> 
> This URL works fine: https://nullreferer.com/?https://github.com/Tautulli/Tautulli/releases/tag/v2.12.1

Interesting, I'll look into it on my side some more.

*edit* You're absolutely correct. I spaced on a network change I made. Apparently that domain is on a blacklist. Apologies for the erroneous report.

**Comment by mturcich24** [comment]
When I hlight over the download link this is what I get:
![image](https://user-images.githubusercontent.com/73649270/231363884-a749ee1c-a06e-433d-9b7f-714224fdf261.png)

So it can't be something on my end if it is coming out of the application itself
