### ISSUE TITLE
Mac Scaling Bug

### ISSUE THREAD

**Issue by purevertigo** [JonnyWong16/plexpy#2033]
### Describe the Bug

Chromium-based browsers on certain Macs, 'Now Playing Box' scrolls when it shouldn't.

Discussed here 
https://www.reddit.com/r/Tautulli/comments/11tpa9p/weird_now_playing_bug/
and definitely NOT my system as evidence has suggested.

Happy to provide any needed files or logs.

 

### Steps to Reproduce

Go to webpage
http://10.0.0.2:8181/home
when anything is playing.
Now Playing Box does not stretch but scrolls.

### Expected Behavior

'Now Playing Box' should stretch.

### Screenshots

https://pasteboard.co/lOsnVZpQHORb.jpg

### Relevant Settings

Plex Version 1.31.3.6868
Tautulli Version V2.12.2

### Tautulli Version

2.12.2

### Git Branch

master

### Git Commit Hash

7836dc84033130367be7b28673417abb514e7ffe

### Platform and Version

Windows 10 (10.0.22621)

### Python Version

3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

### Browser and Version

Chrome 111

### Link to Logs

https://gist.github.com/purevertigo/7a94ca57686ca6fecb2de9d1b5717bdc

**Comment by tgrosst** [comment]
Experiencing the same issue in Chrome 116.0.5845.187 on macOS 13.6.

<img width="372" alt="TautulliScrolling" src="https://github.com/Tautulli/Tautulli/assets/597871/323cda30-460b-4739-a4e9-246aa2c6ad2b">

What additional info is needed to troubleshoot this?

**Comment by JonnyWong16** [comment]
I don't own a Mac so I don't have any way to reproduce the issue. I need someone to tell me exactly what is causing the issue and how to fix it.

**Comment by purevertigo** [comment]
I wish I could @JonnyWong16. 

I don't know, could be that Mac uses a different and not generic screen resolution, unlike windows? I'm maybe guessing.

**Comment by purevertigo** [comment]
-

**Comment by purevertigo** [comment]
bump

**Comment by JonnyWong16** [comment]
I was finally able to reproduce this with a high resolution display. This will be fixed.

**Comment by purevertigo** [comment]
> I was finally able to reproduce this with a high resolution display. This will be fixed.

great! thanks for looking further into it.
