### ISSUE TITLE
Download link for update has gone down

### ISSUE THREAD

**Issue by mturcich24** [JonnyWong16/plexpy#2039]
### Describe the Bug

When clicking download in the update notification it redirects to https://nullreferer.com/?https://github.com/Tautulli/Tautulli/releases/tag/v2.12.2 that website is not longer active.

![image](https://user-images.githubusercontent.com/73649270/230704981-fce9f30b-b926-4ff8-af09-242d991913dc.png)

### Screenshots

![image](https://user-images.githubusercontent.com/73649270/230704984-9f2c9762-26dd-4b02-b1fb-5fc0e463e0ce.png)

### Tautulli Version

2.12.2

### Git Branch

master

### Git Commit Hash

7836dc84033130367be7b28673417abb514e7ffe

### Platform and Version

Windows 10

### Python Version

	3.9.13

### Browser and Version

Chrome, Edge, Firefox

### Link to Logs

NA

**Comment by JonnyWong16** [comment]
The link is `nullreferer` which is working fine. Your screenshot shows `nullrefer`.

Duplicate #2020.

**Comment by mturcich24** [comment]
When I highlight over the download link on my other server that monitors Plex this is what I get:
![image](https://user-images.githubusercontent.com/73649270/231363884-a749ee1c-a06e-433d-9b7f-714224fdf261.png)

This is version 2.12.1

So it can't be something on my end if it is coming out of the application itself

**Comment by mturcich24** [comment]
This is from version v2.12.2 on my actual plex server mousing over the name master

![image](https://user-images.githubusercontent.com/73649270/231366678-1000817c-bfe8-417e-b8a7-3112d0a5dd74.png)

**Comment by JonnyWong16** [comment]
Make sure Settings > Web Interface > Use Dynamic Anonymous Redirect Service is enabled, otherwise you need to manually update the anonymous redirect service setting yourself.

I changed the default from `nullrefer` to`nullreferer` back in 2021.

https://github.com/Tautulli/Tautulli/releases/tag/v2.8.0

`nullreferer.com` _is working_. So if `nullreferer.com` is not loading for you, then it is an issue in your end.

**Comment by JonnyWong16** [comment]
I'm closing this issue becuase it isn't a bug report.
