### ISSUE TITLE
Bulk Edit Shared Libraries and Users

### ISSUE THREAD

**Issue by tonhe** [JonnyWong16/plexpy#2066]
### Is your feature request related to a problem?

When adding a library or making changes to your server, it's always a huge pain to edit each user individually. Having a place to bulk edit these would be amazing.

### What is your feature request?

Create a way to bulk edit library shares by user, or visa versa.

### Are there any workarounds?

Only workaround I've found is external-- i.e. using a python script such as https://github.com/blacktwin/JBOPS/blob/c52df7c5eec866acc8d8f4c8cfcd847450abc586/utility/plex_api_share.py#L40

**Comment by JonnyWong16** [comment]
I have no intention to add any type of share management to Tautulli.
