### ISSUE TITLE
Local Extras, Featurettes, Behind The Scenes, etc. 

### ISSUE THREAD

**Issue by iankaufmann** [JonnyWong16/plexpy#2067]
### What is your feature request?

It seems that playing locally hosted media that is organized into ["Local Files for TV Show Trailers and Extras"](https://support.plex.tv/articles/local-files-for-tv-show-trailers-and-extras/) do not show up in the watch history on Tautulli.

I searched the issues for "extras" and "featurettes" and don't see anybody else discussing this.

Not sure if there is a technical reason for this, but just wanted to put it out there.  I was surprised to not see plays for these items listed in the history.

**Comment by JonnyWong16** [comment]
This is intentional. Any `clip` type media is ignored. There are no plans to change this behaviour.
