### ISSUE TITLE
List if transcode was cpu or gpu (hardware)

### ISSUE THREAD

**Issue by mrjohnpoz** [JonnyWong16/plexpy#2087]
### Is your feature request related to a problem?

no not really

### What is your feature request?

When you view plays in history, it shows if transcoded or direct play/direct stream, but when transcoded does not show if it was done with software (cpu) or hardware (gpu).  This info would be nice to see.

### Are there any workarounds?

You can view in the plex dashboard if hardware is being used for the transcode via the (hw) listed in in the transcode info.  But it is limited to real time plays only, no way to see history of past plays.

### Additional Context

In the graphs under stream type it does list amount direct play/stream, the ability to see amount of plays transcode via cpu or hardware vs just total of transcoded.

**Comment by JonnyWong16** [comment]
Click on the player in the history table for stream details.

**Comment by mrjohnpoz** [comment]
yeah but it doesn't show if was transcoded via cpu or gpu.. Just gives that it was transcoded and to what.. Not how it was transcoded. Don't get me wrong it provides lots of details which love.. Just that little hw or not little tag that the dashboard does would be icing on the cake.

So for example - here is player in history showing yes it was transcoded.

https://i.imgur.com/b5u7mFk.jpg

But see if look in dashboard on plex while playing it says if using hardware (gpu) vs if no hw then in software.  I only bothered to look because current version of plex broke hardware transcode - and was trying to look back in history when last worked with hardware.. 

So I updated plex to an engineer build and this fixed the hardware transcode - see snip in the above image where dashboard shows its doing hardware transcode.

**Comment by samwiseg0** [comment]
>yeah but it doesn't show if was transcoded via cpu or gpu..

It does. If you do not see `(HW)` then it was CPU. 

![2023-06-11_12-04](https://github.com/Tautulli/Tautulli/assets/2241731/aeb999ee-96a2-469e-9a16-989741a18ce1)

**Comment by mrjohnpoz** [comment]
DOH!!! I must be blind - yeah I just double checked.. And you are right it does show it.. I just looked at active running something.. And then went back long enough to before it broke, and you are right it does show it..

I had to just go farther back in the history.. Seems it broke way back on like version released on 5/9 - if I go back before then, pages and pages of history ;)  It does show the HW..

I am an idiot - closing.. ;)

**Comment by mrjohnpoz** [comment]
already does this - I am just stupid..

**Comment by samwiseg0** [comment]
> already does this - I am just stupid..

No worries! Always feel free to grab us on discord if you have any questions!
