### ISSUE TITLE
Add search syntax to allow concealing certain search results on the History page

### ISSUE THREAD

**Issue by Emstar** [JonnyWong16/plexpy#2091]
### Is your feature request related to a problem?

I am always frustrated when I look at the History view and am unable to easily assess the activity of friends & family users, because my own use creates so many more history entries. My only interest in the History page is what _other_ people are doing. 

### What is your feature request?

What about adding some kind of history page search syntax that allows excluding search results? 

For example if my Plex account name is `johndoe`, I could enter `not("johndoe")` into the search field and it would knock out all of my data from view, leaving the other users. 

I am sure there would be other uses for other users. 

### Are there any workarounds?

You can edit a user's profile to eliminate logging for them entirely, but I do not want to discard my usage stats, just conceal my activity on the History page. 

### Additional Context

For my needs it doesn't matter if the means to conceal my activity from History is via search, config, or some other means. It doesn't matter if it is some kind of time-of-use input or a config change that sticks around. I just want to hide my account in the History view while not discarding the data. Search is just what came to mind as a viable option when I found old posts where config options for this exact thing had already been proposed and rejected as counter to the intended use of Tautulli.

**Comment by JonnyWong16** [comment]
Duplicate #1645.
