### ISSUE TITLE
Tautulli service canb't start

### ISSUE THREAD

**Issue by KMASnake** [JonnyWong16/plexpy#2094]
### Describe the Bug

Hello,

i have a docker version running on Synology NAS.

Since i have updated it, i have this message in the terminal in loop :

                            
Traceback (most recent call last):                                               
  File "/app/tautulli/Tautulli.py", line 39, in <module>                         
    import plexpy                                                                
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>                  
    from apscheduler.schedulers.background import BackgroundScheduler            
  File "/app/tautulli/lib/apscheduler/__init__.py", line 1, in <module>          
    from pkg_resources import get_distribution, DistributionNotFound             
ModuleNotFoundError: No module named 'pkg_resources'   

When i enter ctrl+c i have this message :                          
^Cs6-rc: warning: unable to start service svc-tautulli: command crashed with sign
al 2      

Thanks 

### Tautulli Version

latest

### Git Branch

master

### Git Commit Hash

latest version

### Platform and Version

docker on NAS Synology

### Python Version

ocker embedded

### Browser and Version

all

### Link to Logs

1

**Comment by Roxedus** [comment]
Not a tautilli issue.
https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by KMASnake** [comment]
Thanks Reoxedus

**Comment by andrewgould** [comment]
As this result is pretty high up on Google, doesn't have an actual answer (linking to linuxserver.io that says "not my problem" is thoroughly unhelpful) and I experienced the same problem, my solution was this:

From a Docker console, run `python3 -m ensurepip` - it should then come good.

This was based on a freshly updated version of the linuxserver.io Tautulli container.

Best of luck to @KMASnake and anyone else who experiences this problem.

**Comment by nemchik** [comment]
> As this result is pretty high up on Google, doesn't have an actual answer (linking to linuxserver.io that says "not my problem" is thoroughly unhelpful) and I experienced the same problem, my solution was this:
> 
> From a Docker console, run `python3 -m ensurepip` - it should then come good.
> 
> This was based on a freshly updated version of the linuxserver.io Tautulli container.
> 
> Best of luck to @KMASnake and anyone else who experiences this problem.

Your recommended fix isn't a proper long term fix. Your container will likely break the next time there is an update to the container image. Currently the only known workaround is to remove the container entirely and create a new one (not just a regular recreate or restart).

The root of the problem is how Synology and portainer handle updating containers, and there is not a viable fix we can put in place to negate their non standard handling of container updates.

We're not trying to be unhelpful. The best thing you as a user of Synology or portainer can do is ask them to fix their non standard container update process.

**Comment by KMASnake** [comment]
Hello,

i've reinstalled the docker in a project and with this YAML configuration : 

`services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1031
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /volume1/docker/tautulli:/config
    ports:
      - 8181:8181
    network_mode: bridge
    restart: unless-stopped`

I have restored my config.ini file and database backup.
I have successfully update from 2.12.4 ti 2.12.5 without any issue.
I don't have if it will be the case for the next updates.

Hope it helps.
