### ISSUE TITLE
Notification active stream count

### ISSUE THREAD

**Issue by ADYoungberg** [JonnyWong16/plexpy#2095]
### Describe the Bug

Notifications to the android app show more active streams than are actually active. Number increases over time. Must flush active sessions to correct the active streams number in notifications. Active streams page shows correct streams count. Issue only with notifications.

### Expected Behavior

Notifications sent from computer to Android app for buffering with parameter to show active streams in the notification.

### Screenshots

![Screenshot_20230701-181934~2](https://github.com/Tautulli/Tautulli/assets/36788667/1a50f433-2d9a-4290-b403-dfc12913f5c7)
![Screenshot_20230701-182157-121](https://github.com/Tautulli/Tautulli/assets/36788667/0a0067f3-2fee-431f-9ef3-c7efba9ea8c6)

### Tautulli Version

V2.12.4

### Git Branch

Master

### Git Commit Hash

ea6c6078df410f333a060016dfce18c21ad134c9

### Platform and Version

Windows 10

### Python Version

3.9.1 (tags/v3.9.1:1e5d33e, Dec 7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]

### Browser and Version

Chrome 88

### Link to Logs

https://gist.github.com/ADYoungberg/40ab661ffbfc3d71684b66f80895132f#file-gistfile1-txt

**Comment by JonnyWong16** [comment]
Complete logs please.

https://github.com/Tautulli/Tautulli/wiki/Asking-for-Support#how-can-i-share-my-logs

**Comment by ADYoungberg** [comment]
Apologies, log has been updated.

**Comment by JonnyWong16** [comment]
Your logs a too noisy with too many streams going on at the same time.

I want you to

1. Make sure there are no active streams.
2. Disable all notification agents.
3. Create a new notification agent with _only_ "Playback Start" and "Playback Stop" triggers.
4. Do not set up any conditions for the notification agent.
5. Set the "Playback Start" text to `Start streams: {streams}` and the "Playback Stop" text to `Stop streams: {streams}`.
6. Start playing a single stream, make sure the notification text is `Start streams: 1`.
7. Start playing a second stream, make sure the notification text is `Start streams: 2`.
8. Stop one of the streams, make sure the notification text is `Stop streams: 1`.
9. Stop the second stream, make sure the notification text is `Stop streams: 0`.
10. Upload a new set of Tautulli logs.
11. Upload a new set of notification logs.
