### ISSUE TITLE
Not accessible over IPv6

### ISSUE THREAD

**Issue by ghost** [JonnyWong16/plexpy#2099]
### Describe the Bug

As mentioned in #1476, Tautulli does not seem to have IPv6 support. I have it running on an IPv6-only host, and it is not reachable. When trying to change `HTTP_HOST` to `::` (as shown in https://github.com/Tautulli/Tautulli/blob/b953b951fb46400f7d30a22cdc2791faa8d6e233/plexpy/helpers.py#L1195), it simply resets to `0.0.0.0` on the next start. It is confirmed running though as I am able to reach it from the Tautulli host via localhost. Am I missing some obvious setting?

### Steps to Reproduce

1. Install Tautulli (as described in the wiki) on a Linux host without an IPv4 address
2. Try to reach Tautulli from outside localhost

### Expected Behavior

Tautulli should be reachable via IPv6.

### Tautulli Version

v2.12.6

### Git Branch

master

### Git Commit Hash

b953b951fb46400f7d30a22cdc2791faa8d6e233

### Platform and Version

Debian Bookworm

### Python Version

3.11.2

### Browser and Version

Firefox 115, curl

### Link to Logs

https://gist.github.com/ruhrscholz/644de20d6700a5d3123b8c42467e0796

**Comment by JonnyWong16** [comment]
Tautulli needs to be shut down when editing the config file.

**Comment by ghost** [comment]
Sorry, I somehow missed that completely! Thanks for your response!
