### ISSUE TITLE
sync_lists url is not found.

### ISSUE THREAD

**Issue by bendog** [JonnyWong16/plexpy#2100]
### Describe the Bug

Sync lists do not work, when I triple click the synced items header and authenticate, I get a 404.
Is there a configuration which needs to be enabled for my server? 

### Steps to Reproduce

go to synced items
click three times on synced items header
click on the sign in button 
authenticate
get sent to a 404 page

### Expected Behavior

get sent to an XML document with details of synced items 

### Screenshots

<img width="672" alt="Screenshot 2023-07-18 at 12 19 11 pm" src="https://github.com/Tautulli/Tautulli/assets/894916/40a37d40-09ef-4837-8c91-71cfb4d40c1c">

### Relevant Settings

Plex server seems to work in every other capacity 

### Tautulli Version

VERSION V2.12.5

### Git Branch

master

### Git Commit Hash

b953b951fb46400f7d30a22cdc2791faa8d6e233

### Platform and Version

Linux 5.15.0-76-generic (#83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 - Ubuntu Core 20)

### Python Version

3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0]

### Browser and Version

Safari Version 16.5.2 (18615.2.9.11.10)

**Comment by JonnyWong16** [comment]
Not really a bug. Plex deprecated sync last year.

**Comment by bendog** [comment]
Thanks @JonnyWong16 , good to know thats why it's not accessible. 
is there an alternative way to access this?
