### ISSUE TITLE
Remote availability not detected correctly after plex update

### ISSUE THREAD

**Issue by ServerGuyHK** [JonnyWong16/plexpy#2101]
### Describe the Bug

I just upgraded to the latest Plex on my Windows 11 PC.

The upgrade worked fine, but when Plex came back up, my AV blocked the new .exe from the internet.

It was detected that Plex was back up and running as shown in the logs, but nothing about remote access being down.

Plex was showing as remote was not contactable, but no notifications went out.

I know having the AV block the internet access is the issue, but I still think that a notification should be sent.

As soon as I manually changed the firewall rule (which now does not list the actual .exe just the port) a notification saying remote access was available got sent.

### Steps to Reproduce

Block internet access to Plex during an upgrade and when the server comes back up, remote access not being available is not detected.

### Expected Behavior

When remote access is not available, a notification should be sent.

### Tautulli Version

v2.12.5

### Git Branch

Master

### Git Commit Hash

b953b951fb46400f7d30a22cdc2791faa8d6e233

### Platform and Version

Windows 11 Pro

### Python Version

3.9.13

### Browser and Version

Edge

### Link to Logs

https://gist.github.com/ServerGuyHK/905722e023d708040933e30077829317

**Comment by JonnyWong16** [comment]
Not enough logs to come to any conclusion.
