### ISSUE TITLE
users_watched returning empty string

### ISSUE THREAD

**Issue by RaunoT** [JonnyWong16/plexpy#2103]
### Describe the Bug

The `users_watched` value seems to always return an empty string.

### Steps to Reproduce

1. Make a request to the API. For example `cmd=get_home_stats&stat_id=top_tv`
2. Observe the output, `users_watched` value will be an empty string:

```
{
  "title": "MasterChef (US)",
  "year": "",
  "total_plays": 49,
  "total_duration": 110520,
  "users_watched": "",
  "rating_key": 122856,
  "grandparent_rating_key": 122856,
  "last_play": 1690479122,
  "grandparent_thumb": "/library/metadata/122856/thumb/1688389969",
  "thumb": "/library/metadata/122856/thumb/1688389969",
  "art": "/library/metadata/122856/art/1688389969",
  "section_id": 2,
  "media_type": "episode",
  "content_rating": "TV-PG",
  "labels": [],
  "user": "",
  "friendly_name": "",
  "platform": "",
  "live": 0,
  "guid": "plex://episode/5d9c111f46115600200cb3d7",
  "row_id": 2302
},
```

### Expected Behavior

`users_watched` contains user id/names that have watched the content.

### Tautulli Version

2.12.5

### Git Branch

master

### Git Commit Hash

b953b951fb46400f7d30a22cdc2791faa8d6e233

### Platform and Version

Windows 10 (10.0.22621)

### Python Version

3.9.13

### Browser and Version

Chrome 115.0.5790.102

### Link to Logs

Tautulli Libraries :: Loaded media info from cache for section_id 2 (43 items).

**Comment by JonnyWong16** [comment]
That's by design. 

`top_movies` and `top_tv` count plays/duration.

`popular_movies` and `popular_tv` count users.

The blank keys are there to keep the response the same for all stats.

**Comment by RaunoT** [comment]
Thank you for the fast response @JonnyWong16

What I'm trying to achieve is get `top_tv` in a certain period (e.g past 30 days, past year) and display how many users have viewed each item in that given period. 

I can fetch `popular_tv` for the same period and map the `users_watched` based on `rating_key`. However, `popular_tv` and `top_tv` won't always match up, obviously, due to plays/duration and users being different measures for ranking. I want the `stats_count` to be limited. I can always raise it for the `popular_tv` query to some obscure higher number, but just wondering if there's a cleaner/more proper way to do this? I've read the API reference, but couldn't find a better method atm. Would be greatful if you could point me in the right direction, or even just say that this isn't possible at the moment.

Thanks again 🙏
