### ISSUE TITLE
Watched, Trigger for video stream also sends notification on Audio

### ISSUE THREAD

**Issue by Drallas** [JonnyWong16/plexpy#2104]
### Describe the Bug

Under NOTIFICATION AGENTS I checked:

**Watched** 
_Trigger a notification when a video stream reaches the specified watch percentage_

Unfortunatly it's also sending notification for each played song from the Plex server.

### Steps to Reproduce

1. Settings
2. Notification Agents
3. Click Settings (opens Tautulli Remote App Settings)
4. Triggers Tab
5. Scroll to 'Watched'
6. Check Watched

### Expected Behavior

Only notifications on Watched Video Streams.

### Tautulli Version

V2.12.5

### Git Branch

master

### Git Commit Hash

v2.12.5

### Platform and Version

[Docker] Linux 5.15.0-78-generic (#85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 - Alpine Linux 3.17.4)

### Python Version

3.10.12 (main, Jun 9 2023, 02:29:43) [GCC 12.2.1 20220924]

### Browser and Version

Safari latest

### Link to Logs

https://docs.google.com/document/d/1X1GuZyoy3yj7MoNGbDXt46eaCIgufRofqbGhS4XaCmg/edit?usp=share_link

PS: I'm aware I can use conditions to filter them out!

**Comment by JonnyWong16** [comment]
That's just a typo in the trigger description.

**Comment by samwiseg0** [comment]
The intended behavior is all streams regardless of media type. You will want to filter out music and clips to receive "normal" watched content.

The description will be updated.

**Comment by Drallas** [comment]
Thanks, I already used a filter, but I didn't know the intention behind the trigger.
