### ISSUE TITLE
Missing IP address for failed logins

### ISSUE THREAD

**Issue by cyberbrix** [JonnyWong16/plexpy#2105]
### Describe the Bug

In a docker container, testing failed login attempts, seeing

CP Server Thread-6 : Tautulli WebAuth :: Invalid user login attempt from '<username>'.

no IP address is listed. (checked the entire log folder)

### Expected Behavior

attempt to log in with incorrect credentials

### Relevant Settings

Running from Docker

### Tautulli Version

2.12.5

### Git Branch

master

### Git Commit Hash

b953b951fb46400f7d30a22cdc2791faa8d6e233

### Platform and Version

 	[Docker] Linux 4.4.180+ (#42962 SMP Tue Oct 18 15:07:03 CST 2022 - Debian GNU/Linux 11 bullseye

### Python Version

3.9.16 (main, Mar 1 2023, 15:47:56) [GCC 10.2.1 20210110]

### Browser and Version

Firefox

### Link to Logs

https://gist.github.com/cyberbrix/5a1609532c293bbaf5a3f77ca92eee4e

**Comment by JonnyWong16** [comment]
Not sure what you mean. The attempted username is shown in the main logs (blank if you don't enter a username on the login form).

https://github.com/Tautulli/Tautulli/blob/b953b951fb46400f7d30a22cdc2791faa8d6e233/plexpy/webauth.py#L419

Detailed login logs are under the Settings menu > View Logs > Login Logs.

**Comment by cyberbrix** [comment]
Correct, but I am trying to identify the IP address of the failed login so I can use fail2ban or other tools to alert on multiple failed logins. I don't see the IP in any log in the log file.

**Comment by JonnyWong16** [comment]
There are no IP addresses in the log file. There is no bug here.

**Comment by cyberbrix** [comment]
Apologies, I'll submit a feature request

**Comment by JonnyWong16** [comment]
I have no intention to add IP address to the log file.

**Comment by cyberbrix** [comment]
Any specific reason?

**Comment by JonnyWong16** [comment]
fail2ban wouldn't be able to parse IP addresses anyways since all IP addresses are automatically masked in the log file for privacy for when users share their logs with us.
