### ISSUE TITLE
Add login details to logs including failure/success and IP

### ISSUE THREAD

**Issue by cyberbrix** [JonnyWong16/plexpy#2106]
### Is your feature request related to a problem?

I am trying to identify failed login attempts so I can alert or ban that IP. This would allow me to use tautulli from outside my home but keep it secure.

### What is your feature request?

Please add more detailed login information to the log files including:
success/failure
IP
device type/user agent

### Are there any workarounds?

A notification trigger for when multiple failed login attempts occur from a specific IP.

**Comment by JonnyWong16** [comment]
Duplicate #2092
