### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by GlenNicholls** [JonnyWong16/plexpy#2108]
### Is your feature request related to a problem?

I'm Looking for dev info/dev documentation for running Tautulli standalone. While my objective is Jellyfin integration, I'm just trying to find the quickstart "how-to" for ingress/egress metadata and the associated API docs for reproducing Tautulli's "special sauce" with Plex, if that makes sense. Currently, all I care about is watch history and statistics.

I see that Jellyfin support is not in the roadmap ([1](https://github.com/Tautulli/Tautulli/issues/1597), [2](https://github.com/Tautulli/Tautulli/issues/1999)) which I have no problem with. I'm just trying to understand the API better so I can (hopefully) write a custom Jellyfin plugin for the features I'm looking for. 

I have looked through the [wiki](https://github.com/Tautulli/Tautulli/wiki) and haven't been able to find the API info for what I'm looking for. I see [3rd Party APIs Guide](https://github.com/Tautulli/Tautulli/wiki/3rd-Party-APIs-Guide) and [Tautulli API Reference](https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference), but none of those are helping me understand how I can interface with the application standalone. The [Custom Scripts](https://github.com/Tautulli/Tautulli/wiki/Custom-Scripts) is sort of close to what I'm looking for, but I'm struggling to adapt those examples to a high-level use-case of a generic API to meet my needs.

Anyways, the Plex integrations I've seen are awesome btw - I'm sure your users love this app!

### What is your feature request?

Tautulli's standalone API docs. I've probably missed it, so feel free to point me closer if I've missed them.

### Are there any workarounds?

N/A

### Additional Context

N/A

**Comment by samwiseg0** [comment]
I am not quite sure I understand what you are asking for? 

Tautulli is entirely built on the plex API. That is why it simply cannot be adapted. Beyond looking at the source code and seeing how Tautulli handles things. I am not sure what you are looking for?
