### ISSUE TITLE
Show downloading items on activity

### ISSUE THREAD

**Issue by itschasa** [JonnyWong16/plexpy#2120]
### Is your feature request related to a problem?

I find it a little irritating to not know who’s downloading the file. At the moment, using the Plex dashboard, all you can see is what is being downloaded. No info on who or how the video is being transcoded.

### What is your feature request?

Currently, downloads using the Plex mobile app aren’t shown in the activity section, even if the download is being transcoded.

**Comment by JonnyWong16** [comment]
Duplicate #1451
