### ISSUE TITLE
[Notification] Email contain multilple recently added

### ISSUE THREAD

**Issue by moi15moi** [JonnyWong16/plexpy#2137]
### Is your feature request related to a problem?

I'm always frustrated when I received a bunch of email for the ``recently added`` notification.

### What is your feature request?

Be able to include multiple recently added movies/series in 1 email.

It could work by having a parameter ``time``.
Ex: If the time would be 1000 seconds, then the email would contain all the last 1000 seconds recently added movies/series.

**Comment by JonnyWong16** [comment]
Do you mean the newsletter feature?

**Comment by moi15moi** [comment]
I am talking about the ``notification agents``

![image](https://github.com/Tautulli/Tautulli/assets/80980684/6c4d2e4f-a483-4b3d-a320-5aa36067ab03)

**Comment by JonnyWong16** [comment]
I know, but the newsletter does exactly what you are asking for - send one email for all new additions within the last X time.

**Comment by moi15moi** [comment]
Oh right. I didn't know about this feature.
It totally resolve my issue.

Thank you
