### ISSUE TITLE
API - get_library_media_info, seasons, episodes, missing data?

### ISSUE THREAD

**Issue by nebb00** [JonnyWong16/plexpy#2144]
### Describe the Bug

Should the below data exist per season and episode via the API? Here is an example;

https://tautulli.domain.com/api/v2?apikey=APIKEY&cmd=get_library_media_info&rating_key=72398&media_type=show
```
section_id             : 0
section_type           : 
added_at               : 1674151907
media_type             : season
rating_key             : 72399
parent_rating_key      : 72398
grandparent_rating_key : 
title                  : Season 2
sort_title             : Season 2
year                   : 
media_index            : 2
parent_media_index     : 1
thumb                  : /library/metadata/72398/thumb/1691373606
container              : 
bitrate                : 
video_codec            : 
video_resolution       : 
video_framerate        : 
audio_codec            : 
audio_channels         : 
file_size              :  <---------------------------- This
last_played            :  <---------------------------- This
play_count             :  <---------------------------- This
```

then we can go down one more level to the episode data
https://tautulli.domain.com/api/v2?apikey=APIKEY&cmd=get_library_media_info&rating_key=72399&media_type=episode
```
section_id             : 0
section_type           : 
added_at               : 1674151907
media_type             : episode
rating_key             : 72400
parent_rating_key      : 72399
grandparent_rating_key : 72398
title                  : Grandmother of All Reunions
sort_title             : Grandmother of All Reunions
year                   : 2023
media_index            : 1
parent_media_index     : 2
thumb                  : /library/metadata/72400/thumb/1674670422
container              : mkv
bitrate                : 5861
video_codec            : h264
video_resolution       : 1080
video_framerate        : 24p
audio_codec            : aac
audio_channels         : 2
file_size              : 1851776799
last_played            :  <---------------------------- This
play_count             :  <---------------------------- This
```

### Steps to Reproduce

Run API commands

### Tautulli Version

v2.13.1

### Git Branch

master

### Git Commit Hash

couldnt find it

### Platform and Version

Docker

### Python Version

3.11.5

### Browser and Version

Firefox

### Link to Logs

Not needed

**Comment by JonnyWong16** [comment]
Have you refreshed the media info? Either click the button in the UI, or add `refresh=true` to the API URL parameters.

**Comment by nebb00** [comment]
I just did both methods. Same results.

**Comment by JonnyWong16** [comment]
Logs please.

**Comment by nebb00** [comment]
> Logs please.

Which ones are you interested in?
![image](https://github.com/Tautulli/Tautulli/assets/43903113/8043afe3-1887-4e9c-a92b-6ee5ef2f7a21)

**Comment by JonnyWong16** [comment]
https://github.com/Tautulli/Tautulli/wiki/Asking-for-Support#how-can-i-share-my-logs

**Comment by nebb00** [comment]
https://gist.github.com/nebb00/274bb38358dad2ab3525059a766301df

**Comment by JonnyWong16** [comment]
Can you show me a screenshot of the media info table in the UI where it shows the play count for that season and episode? Can you then click on the season and episode and show me a screenshot of the history table on the media info page?

**Comment by nebb00** [comment]
![image](https://github.com/Tautulli/Tautulli/assets/43903113/dd499e90-ab63-450b-a235-3b9ff0fef939)
![image](https://github.com/Tautulli/Tautulli/assets/43903113/b0d577f5-ccec-4f4d-95ab-b7c6d3fd6e68)
![image](https://github.com/Tautulli/Tautulli/assets/43903113/6017e320-3af5-4d07-ab37-a6849407c5f3)

Also it appears no seasons or episodes have this data

**Comment by JonnyWong16** [comment]
I want to see the media info table.

You probably unlinked the media from Plex by moving it. 

https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions#move-media

**Comment by nebb00** [comment]
I did run the update_all_metadata.py script yesterday, as I noticed lots didnt have last played and plays here. It appeared to fix it.

![image](https://github.com/Tautulli/Tautulli/assets/43903113/d3565690-060e-4525-8a49-e971d949077a)
![image](https://github.com/Tautulli/Tautulli/assets/43903113/6f71fc8c-8d73-47c5-8393-378240a81c36)

**Comment by nebb00** [comment]
Do i need to purge my DB and start afresh?

**Comment by JonnyWong16** [comment]
Show me the season and episode on the media info table.

**Comment by nebb00** [comment]
![image](https://github.com/Tautulli/Tautulli/assets/43903113/1a517ab6-12e5-4415-9850-30b3c5a4a152)

**Comment by JonnyWong16** [comment]
You're missing the `section_id` and `section_type` URL parameters.

```
https://tautulli.domain.com/api/v2?apikey=APIKEY&cmd=get_library_media_info&rating_key=72398&section_id=Y&section_type=season
```
```
https://tautulli.domain.com/api/v2?apikey=APIKEY&cmd=get_library_media_info&rating_key=72399&section_id=Y&section_type=episode
```

**Comment by nebb00** [comment]
oh nice, i will give that a go in a few hours. While i have you, when i run update_all_metadata.py, I get a number of these. Anything I can do to fix?

```python3 update_all_metadata.py
Dry run enabled. No changes will be made to the Tautulli database.
Retrieving all history items from the Tautulli database...
        Unsupported guid for 'Battlestar Galactica' in the Tautulli database [Guid: local://94458]. Skipping...
        Unsupported guid for 'Battlestar Galactica' in the Tautulli database [Guid: local://94458]. Skipping...
        Unsupported guid for 'Battlestar Galactica' in the Tautulli database [Guid: local://94458]. Skipping...
        xxxx
(DRY RUN) No match found for 942 Tautulli items on the Plex server:
```

**Comment by JonnyWong16** [comment]
`local://` is unmatched media.

It was watched when the media was unmatched in Plex, and Tautulli recorded it as such in your history. The only way to relink your history with your Plex server is to do it manually in the UI as mentioned in the FAQ.

I'm closing this issue since there isn't a bug.
