### ISSUE TITLE
CSV Export error

### ISSUE THREAD

**Issue by MasothU** [JonnyWong16/plexpy#2154]
### Describe the Bug

When importing a csv export of my library into Excel, one record get's not properly parsed.
The problem seems to be that inside the summary, there are " " used. Result is, that summary data gets split and shifted to next column. All subsequent columns are shifted and data is the incorrect.

I guess one could overcome this problem by using a more "exotic" delimiter for csv exports, like '|' .  Idea would be to at least give the option to change the delimiter when creating csv exports.

### Steps to Reproduce

1. Import in Excel, either via double click on csv file and then Data->Text to columns or importing the data via Data->From Text/CSV

### Screenshots

<img width="368" alt="2023-09-15_14h00_28" src="https://github.com/Tautulli/Tautulli/assets/17427639/c6186bc1-cb63-45f5-85ac-5f4c835bafd7">
<img width="466" alt="2023-09-15_13h59_45" src="https://github.com/Tautulli/Tautulli/assets/17427639/5d0f08a1-e979-4d71-8244-2bafc5d77321">

[export.csv](https://github.com/Tautulli/Tautulli/files/12619252/export.csv)

### Tautulli Version

v2.13.1

### Git Branch

master

### Git Commit Hash

6d858367a4367e204f1cc02467c99546a5d8bc23

### Platform and Version

Windows 10

### Python Version

 	3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]

### Browser and Version

Firefox 117.0.1 (64-Bit

### Link to Logs

https://gist.githubusercontent.com/MasothU/35f51a964e24f5c435f54b6f7d00855d/raw/0cdcd927293d32afa0d1db332afc4c42a23d0564/gistfile1.txt

**Comment by samwiseg0** [comment]
@MasothU, Did you see SwiftPanda's response in your last issue? https://github.com/Tautulli/Tautulli/issues/2153#issuecomment-1720557287

You _must open_ the csv file with excel. Not _copy paste_ the text in. 

The exported data is using a python library that exports the data properly formatted and escaped. 

If you need further assistance please use discord.

**Comment by MasothU** [comment]
I did open it with excel.
Two different ways. As I wrote in my bug report under "Steps to reproduce"
Did you try my example csv?

**Comment by MasothU** [comment]
Why do you always close tickets before waiting for the reporter to answer?! This is not very nice

**Comment by samwiseg0** [comment]
> Why do you always close tickets before waiting for the reporter to answer?! This is not very nice

We use github exclusively for bug reports. Unfortunately, this is not a bug in tautulli. We have tested using your exact description on multiple types of installs and cannot reproduce. Thus something else maybe going on. 

Since this falls under support we would kindly ask if you could please open a support thread on discord so we can help you get to the bottom of this issue. 

Thanks

Export using your description:
[Movie - GoldenEye [54744].csv](https://github.com/Tautulli/Tautulli/files/12622317/Movie.-.GoldenEye.54744.csv)

Properly escaped CSV:
![2023-09-15_13-49](https://github.com/Tautulli/Tautulli/assets/2241731/a85a81ce-4068-4c5c-b270-e3dd6c01568c)

**Comment by MasothU** [comment]
Understood. Thank you. Still I don't understand why this can't be a bug report since the csv I uploaded came exactly in this manner from Tatutulli export

**Comment by JonnyWong16** [comment]
The file you posted is not the original file exported by Tautulli. Your logs show you exported a library with 10 items.

```
2023-09-15 10:59:33 - INFO    :: Thread-30 : Tautulli Exporter :: Starting export for 'Library - Movies - All [36]'...
2023-09-15 10:59:38 - INFO    :: Thread-30 : Tautulli Exporter :: Exporting 10 item(s).
2023-09-15 11:01:53 - INFO    :: Thread-30 : Tautulli Exporter :: Successfully exported to 'D:\Tautulli\Export\Library - Movies - All [36].20230915105933'
```

The file you posted is a modified/redacted file. Please provide the original unmodified file.

**Comment by MasothU** [comment]
I redacted the exported csv and removed the entries which worked. But I did that using notepad++ and checked the original file and the one I redacted and it was the same.
