### ISSUE TITLE
History screen watch percentage icon

### ISSUE THREAD

**Issue by chumbawumba** [JonnyWong16/plexpy#2156]
### Is your feature request related to a problem?

No. It's purely a feature request.

### What is your feature request?

At a glance it's hard to see how much of a given program is actually being watched until the watch breaks 50%. 

Would it be possible for the history page to use the version of circle-three-quarters-stroke, circle-half-stroke, and circle-quarter-stroke for .25 and .75 when indicating watch times from FA 6.4.2.

![image](https://github.com/Tautulli/Tautulli/assets/8107428/f11896c2-7759-430c-83e7-7f7cc08d5f1c)

If there are license concerns, I would be willing to purchase an FA6 pro license for Tautulli to use if that is an easier drop-in replacement. If the FA license for use aren't compatible with Tautulli, another option is the CC Davo Sime set @ the noun project (https://thenounproject.com/browse/collection-icon/harvey-balls-21789/?p=1). 

Or, if that also doesn't work, I am also willing to design SVGs to your spec license free.

### Are there any workarounds?

Not that I'm aware of. 

### Additional Context

n/a

**Comment by JonnyWong16** [comment]
Custom CSS is an option. 

https://codepen.io/txreplay/pen/aBVEow

**Comment by TheMeanCanEHdian** [comment]
Perhaps a better feature request would be a way to toggle between the icon representation and the percent value instead.

While this would add another setting or toggle it would remove any issues with paid licenses.

**Comment by chumbawumba** [comment]
> Custom CSS is an option.

My apologies. I assumed there was some reason the font mechanism was chosen.
