### ISSUE TITLE
Add NTFY to list of Notification Options

### ISSUE THREAD

**Issue by hevel86** [JonnyWong16/plexpy#2160]
### Is your feature request related to a problem?

No, it is just a feature request.

### What is your feature request?

I would like to have [ntfy](https://github.com/binwiederhier/ntfy) added to the list of notification options.

### Are there any workarounds?

I currently use other notification options as well, but ntfy is my favorite as it can be self-hosted.

### Additional Context

Here's their main website: https://ntfy.sh/

**Comment by samwiseg0** [comment]
This can be done today with webhooks. https://github.com/Tautulli/Tautulli/wiki/Notification-Agents-Guide#webhook

If you need help please use discord for further assistance.

**Comment by hevel86** [comment]
I took your advice and used webhooks.  I now have a working configuration that I'm fairly pleased with and I plan to share the example, but I'm not sure the best way to submit that.


- Under the **Configuration** tab
  -  The **Webhook URL** is your ntfy root URL
     -  Important note "To publish as JSON, you must PUT/POST to the ntfy root URL, not to the topic URL. Be sure to check that you're POST-ing to" per [ntfy documentation](https://docs.ntfy.sh/publish/#publish-as-json).
   - The **Webhook Method** is _POST_
- Under the **Data** tab in the  _Recently Added_ section, **JSON Headers** were not used in this example:

**JSON Data**
```html
<movie>
{
	"topic": "tautulli",
	"icon": "{poster_url}",
	"message": "{summary}",
	"tags": ["tautulli", "popcorn"],
	"title": "{title} was recently added to {library_name} on {server_name}"
}
</movie>
<show>
{
	"topic": "tautulli",
	"icon": "{poster_url}",
	"message": "{summary}",
	"tags": ["tautulli", "tv"],
	"title": "{title} was recently added to {library_name} on {server_name}"
}
</show>
<season>
{
	"topic": "tautulli",
	"icon": "{poster_url}",
	"message": "{summary}",
	"tags": ["tautulli", "tv"],
	"title": "{title} Season {season_num00} recently added to {library_name} on {server_name}"
}
</season>
<episode>
{
	"topic": "tautulli",
	"icon": "{poster_url}",
	"message": "{summary}",
	"tags": ["tautulli", "tv"],
	"title": "{title} (S{season_num00}:E{episode_num00}) was recently added to {library_name} on {server_name}"
}
</episode>
```
- I used the Tautulli parameters as described [here](https://github.com/Zefau/ioBroker.tautulli/blob/master/tautulli-parameters.json).  @samwiseg0 is there an official reference that could be used instead?

**Comment by JonnyWong16** [comment]
![image](https://github.com/Tautulli/Tautulli/assets/9099342/bab5dbf7-0ccf-409d-b3ce-ee824e7e9c6f)

**Comment by samwiseg0** [comment]
@hevel86 thank you for providing an example. I think here is the best place. Folks can always search GitHub and find it here. You could also post it in discord in the general channel if you would like.

**Comment by hevel86** [comment]
@JonnyWong16 Doh! Thanks for pointing out something obvious 😆
@samwiseg0 Glad to give back in some small way!  Would it be worthwhile to add a section to [the wiki](https://github.com/Tautulli/Tautulli/wiki/Notification-Agents-Guide#webhook)?  I feel that section is a bit broad (I get that Webhooks in general are a bit broad), but it references Slack and Discord webhooks which already have official integrations.  The general examples on the [Slack webhooks](https://api.slack.com/messaging/webhooks) can give some kind of reference, but looking for a directly applicable example in Tautulli would have helped me when first looking into this project, and I imagine it could help others as well.

**Comment by JonnyWong16** [comment]
Added to the wiki.

**Comment by Proximus888** [comment]
> I took your advice and used webhooks. I now have a working configuration that I'm fairly pleased with and I plan to share the example, but I'm not sure the best way to submit that.
> 
>     * Under the **Configuration** tab
>       
>       * The **Webhook URL** is your ntfy root URL
>         
>         * Important note "To publish as JSON, you must PUT/POST to the ntfy root URL, not to the topic URL. Be sure to check that you're POST-ing to" per [ntfy documentation](https://docs.ntfy.sh/publish/#publish-as-json).
>       * The **Webhook Method** is _POST_
> 
>     * Under the **Data** tab in the  _Recently Added_ section, **JSON Headers** were not used in this example:
> 
> 
> **JSON Data**
> 
> ```
> <movie>
> {
> 	"topic": "tautulli",
> 	"icon": "{poster_url}",
> 	"message": "{summary}",
> 	"tags": ["tautulli", "popcorn"],
> 	"title": "{title} was recently added to {library_name} on {server_name}"
> }
> </movie>
> <show>
> {
> 	"topic": "tautulli",
> 	"icon": "{poster_url}",
> 	"message": "{summary}",
> 	"tags": ["tautulli", "tv"],
> 	"title": "{title} was recently added to {library_name} on {server_name}"
> }
> </show>
> <season>
> {
> 	"topic": "tautulli",
> 	"icon": "{poster_url}",
> 	"message": "{summary}",
> 	"tags": ["tautulli", "tv"],
> 	"title": "{title} Season {season_num00} recently added to {library_name} on {server_name}"
> }
> </season>
> <episode>
> {
> 	"topic": "tautulli",
> 	"icon": "{poster_url}",
> 	"message": "{summary}",
> 	"tags": ["tautulli", "tv"],
> 	"title": "{title} (S{season_num00}:E{episode_num00}) was recently added to {library_name} on {server_name}"
> }
> </episode>
> ```
> 
>     * I used the Tautulli parameters as described [here](https://github.com/Zefau/ioBroker.tautulli/blob/master/tautulli-parameters.json).  @samwiseg0 is there an official reference that could be used instead?

I also add:

```
        "attach": "{server_url}{poster_thumb}",
```
Then it adds the poster of the movie/series to the notification.

**Comment by Feramance** [comment]
Just adding the missing piece of info which took me a while to gather to this issue, you also need to add the below in the JSON header field:
```
{
	"Authorization": "Bearer tk_yourPrivateToken"
}
```

**Comment by hevel86** [comment]
> Just adding the missing piece of info which took me a while to gather to this issue, you also need to add the below in the JSON header field:
> 
> ```
> {
> 	"Authorization": "Bearer tk_yourPrivateToken"
> }
> ```

That's interesting @Feramance, I didn't have to do that in my config.
![firefox_cOr3znQY0b](https://github.com/Tautulli/Tautulli/assets/2089595/e73a8d80-cfe6-4576-acf5-5f41243ae13c)

**Comment by Feramance** [comment]
I wasn't receiving notifications with an authentication error until I added that

**Comment by madchr1st** [comment]
Instead of adding authorization to every single data item, you can also use the [query parameter](https://docs.ntfy.sh/publish/#query-param) in your Webhook-URL: 

`http(s)://<ntfy-hostname>:<port>/?auth=<authParam>`

To create your auth parameter, use the following commands:

- For `Basic Auth`:

    ```bash
    $ echo -n "Basic `echo -n 'testuser:fakepassword' | base64`" | base64 | tr -d '='
    QmFzaWMgZEdWemRIVnpaWEk2Wm1GclpYQmhjM04zYjNKaw
    ```

- For `Bearer Token Auth`:

    ```bash
    $ echo -n "Bearer faketoken" | base64 | tr -d '='
    QmVhcmVyIGZha2V0b2tlbg
    ```

Examples for the Webhook-URL:

- Hosted on ntfy.sh: `https://ntfy.sh/?auth=QmFzaWMgZEdWemRIVnpaWEk2Wm1GclpYQmhjM04zYjNKaw`
- Self-hosted on K8s: `http://ntfy.ntfy.svc.cluster.local:10222/?auth=QmVhcmVyIGZha2V0b2tlbg`


Edit: Use `topic` in the JSON data and not in the Webhook-URL.
