### ISSUE TITLE
Show whether transcode was hardware or CPU in graphs

### ISSUE THREAD

**Issue by johnmaguire** [JonnyWong16/plexpy#2168]
### Is your feature request related to a problem?

I want to know whether hardware transcoding is generally working, and how many of my users are taking advantage of it.

### What is your feature request?

<img width="1677" alt="Screenshot 2023-09-26 at 8 14 43 PM" src="https://github.com/Tautulli/Tautulli/assets/440033/5bb8a48d-1038-411b-9f63-d0a6540690e5">

Separate CPU and HW transcodes on a graph on this page.

**Comment by herby2212** [comment]
So you propose a split of the `Transcode` line into `Transcode (Software)` and `Transcode (Hardware)` or `Transcode (CPU)` and `Transcode (HW)`?

**Comment by samwiseg0** [comment]
> So you propose a split of the `Transcode` line into `Transcode (Software)` and `Transcode (Hardware)` or `Transcode (CPU)` and `Transcode (HW)`?

I do not think there would be a good way to do this in general? 

Transcode decision is decided by plex and it can consider something a transcode if it is a video remux and an audio transcode with a container change. 

Hardware transcode is only really determined by video transcodes but plex may show the stream is being transcoded even if the video itself is not being transcoded. This graph does not capture these instances. 

IMO there would need to be a separate graph to show statistics on video transcoding only. I do not think making changes to this graph would make sense in this case.

**Comment by herby2212** [comment]
> > So you propose a split of the `Transcode` line into `Transcode (Software)` and `Transcode (Hardware)` or `Transcode (CPU)` and `Transcode (HW)`?
> 
> I do not think there would be a good way to do this in general?
> 
> Transcode decision is decided by plex and it can consider something a transcode if it is a video remux and an audio transcode with a container change.
> 
> Hardware transcode is only really determined by video transcodes but plex may show the stream is being transcoded even if the video itself is not being transcoded. This graph does not capture these instances.
> 
> IMO there would need to be a separate graph to show statistics on video transcoding only. I do not think making changes to this graph would make sense in this case.

Interesting point. I'm not certain if audio transcoding is handled via hardware transcoding by Plex, but as far as I know HW transcoding is only used for videos as you already mentioned.

IMO you could still use the existing graph and check explicitly if the video got transcoded to count for the new line `Transcode (HW)`. The data for this is present in the Tautulli database.

Having a seperate graph would also be an option, but what should be shown besides the video transcode and maybe the audio transcode decision?

**Comment by samwiseg0** [comment]
Yes audio transcoding is handled via CPU not GPU. 

> IMO you could still use the existing graph and check explicitly if the video got transcoded to count for the new line Transcode (HW). The data for this is present in the Tautulli database.

Sure but in a properly working system all video should be HW transcoded?

> IMO you could still use the existing graph and check explicitly if the video got transcoded to count for the new line Transcode (HW). The data for this is present in the Tautulli database.

What would make sense to me would be to essentially have the decision breakdown in graph form?
For example:
* Overall Decision
* Container Transcodes/Copies
* Audio Transcodes/Copies
* Video Transcodes/Copies
* Subtitle Transcodes/Copies/Burn in

Ultimately, I am not sure what this problem this ask is trying to solve? I am not sure this information in graph form would be beneficial?

**Comment by herby2212** [comment]
> Sure but in a properly working system all video should be HW transcoded?

Yes. This is also why I initially asked for the exact use case. As in a working system the only thing visible with another `line` in the graph would be the day you turned on hardware transcoding😄.

> What would make sense to me would be to essentially have the decision breakdown in graph form?
> For example:
> 
> - Overall Decision
> - Container Transcodes/Copies
> - Audio Transcodes/Copies
> - Video Transcodes/Copies
> - Subtitle Transcodes/Copies/Burn in

Those informations are already present in the history and I'm also questioning if building a new graph with custom queries just to visualize those informations on a different scale is really beneficial.

Also thanks for your posts I enjoyed the discussion about a feature. :)

**Comment by johnmaguire** [comment]
> > IMO you could still use the existing graph and check explicitly if the video got transcoded to count for the new line Transcode (HW). The data for this is present in the Tautulli database.
> 
> Sure but in a properly working system all video should be HW transcoded?

I use an nvidia GPU on a Linux machine, in a Docker container. My experience has definitely not been that all videos are HW transcoded. This is why I'm looking for such a graph.

Are there certain video file types that can be GPU transcoded? Is it breaking when I upgrade the kernel due to a mismatch between kernel version and module versions? ...?

> Those informations are already present in the history and I'm also questioning if building a new graph with custom queries just to visualize those informations on a different scale is really beneficial.

Where can I find whether HW transcoding was used in the History tab?

**Comment by samwiseg0** [comment]
> Those informations are already present in the history and I'm also questioning if building a new graph with custom queries just to visualize those informations on a different scale is really beneficial.

Agreed. I do not think there is much benefit. 

> Also thanks for your posts I enjoyed the discussion about a feature. :)

Same!

@JohnMaguire

> I use an nvidia GPU on a Linux machine, in a Docker container. My experience has definitely not been that all videos are HW transcoded. This is why I'm looking for such a graph.

> Are there certain video file types that can be GPU transcoded? Is it breaking when I upgrade the kernel due to a mismatch between kernel version and module versions? ...?

As far as I know. No. I have been running a NVIDIA Quatro for many years and I do not recall an instance where it did not transcode a certain type of codec? Now if there is an issue with the driver or something else where plex is not able to talk to the GPU properly then yes it will fail to HW transcode but typically that results in none of the video transcodes being transcoded. 

> Where can I find whether HW transcoding was used in the History tab?

Click on the player in the history tab. 
![SCR-20231016-jgcy](https://github.com/Tautulli/Tautulli/assets/2241731/943a3f96-91d4-4aa9-9a93-85868161902c)
![SCR-20231016-jhrt](https://github.com/Tautulli/Tautulli/assets/2241731/204cd62e-aa01-4df8-9449-92cb61b8ae83)


I think an overall better solution would be to create a notifier that sends you a notification when a video transcode is started but it is not hardware. This can be accomplished with the notifier conditions.

**Comment by johnmaguire** [comment]
> As far as I know. No. I have been running a NVIDIA Quatro for many years and I do not recall an instance where it did not transcode a certain type of codec? Now if there is an issue with the driver or something else where plex is not able to talk to the GPU properly then yes it will fail to HW transcode but typically that results in none of the video transcodes being transcoded.

These were hypothetical questions I'm trying to answer. FWIW, I use an NVIDIA Quadro as well. 

> I think an overall better solution would be to create a notifier that sends you a notification when a video transcode is started but it is not hardware. This can be accomplished with the notifier conditions.

This is not at all what I want. I don't want notifications on my phone for Plex streams, period. I want to retroactively find patterns in the data to see why HW transcoding is not always occurring.

> > Those informations are already present in the history and I'm also questioning if building a new graph with custom queries just to visualize those informations on a different scale is really beneficial.
> 
> Agreed. I do not think there is much benefit.

I have to admit this response is a little frustrating when I think I've done a good job of demonstrating the benefit clearly. My server sometimes does HW transcoding, and sometimes it does not. I want to find patterns in the data to see when it is working, and when it isn't. Does it work until a system upgrade, and then stop working? Does it work for some users, but not other users? Without historical data, I can't figure this out.

Clicking on each row in the History tab is not a feasible solution. Maybe I can access the database and pull what I need from there.

**Comment by johnmaguire** [comment]
For example, here are three streams that occured in the last week. Note that one is transocde, one is directplay, and one is transcode (HW).

<img width="603" alt="Screenshot 2023-10-16 at 10 25 03 AM" src="https://github.com/Tautulli/Tautulli/assets/440033/f013a809-ff3e-4f81-b09a-1c7fb5426112">
<img width="602" alt="Screenshot 2023-10-16 at 10 25 12 AM" src="https://github.com/Tautulli/Tautulli/assets/440033/18b1acd3-9cff-4cc5-baa3-e96ce8430177">
<img width="605" alt="Screenshot 2023-10-16 at 10 25 18 AM" src="https://github.com/Tautulli/Tautulli/assets/440033/0d860139-1848-4f1f-ba1c-db43279d440d">

**Comment by JonnyWong16** [comment]
> <img width="625" alt="Screenshot 2023-10-16 at 10 23 39 AM" src="https://github.com/Tautulli/Tautulli/assets/440033/b2f446f6-6238-47b2-840f-cb34a10504da">

This video is being direct streamed (`copy`) so there is no video transcoding, thus no hardware transcoding required.

**Comment by samwiseg0** [comment]
> I have to admit this response is a little frustrating when I think I've done a good job of demonstrating the benefit clearly.

From my understanding of what you are trying to accomplish, is to debug a potential problem that we personally have not seen and there are other tools that can provide what you are looking for such as the DB, API, and notifications.  Secondly, in a normally working system this graph would not add value as all video transcodes are HW transcodes barring no Plex bugs. 

>  I want to find patterns in the data to see when it is working, and when it isn't. Does it work until a system upgrade, and then stop working? Does it work for some users, but not other users? Without historical data, I can't figure this out.

Notifications would help you determine time, place and which stream. Again from my experience and conversations I have had with others over the years, it very much works like an on and off switch. It either is working or not. If you find out otherwise then I would be interested to see the data and it should then be raised as a bug with Plex. 

> Maybe I can access the database and pull what I need from there.

This is a good idea. You can also use the API to pull the history table.

**Comment by johnmaguire** [comment]
> From my understanding of what you are trying to accomplish, is to debug a potential problem that we personally have not seen and there are other tools that can provide what you are looking for such as the DB, API, and notifications. Secondly, in a normally working system this graph would not add value as all video transcodes are HW transcodes barring no Plex bugs.

So there are two parts to this...

If I understand correctly, you're stating Tautulli is not meant to be used for debugging Plex. This is disappointing, as it seems the main reason people install Tautulli (or at least, the reason I did) was to observe, monitor, and understand how Plex is behaving. That makes it inherently a useful debugging tool when Plex isn't behaving how we expect. Therefore, "in a normally working system this graph would not add value" seems to miss the point... not all systems are working as expected! :)

Secondly, regarding "all video transcodes are HW transcodes barring no Plex bugs." ~~I shared screenshots above that seem to prove this is not the case. There have been no system upgrades between these two transcodes.~~ May I ask where you've received this information? Frankly, I think it is in direct contradiction to the [Compatible formats and limitations section of the docs](https://support.plex.tv/articles/115002178853-using-hardware-accelerated-streaming/).

> > I want to find patterns in the data to see when it is working, and when it isn't. Does it work until a system upgrade, and then stop working? Does it work for some users, but not other users? Without historical data, I can't figure this out.
> 
> Notifications would help you determine time and place and which stream. Again from my experience and conversations I have had with others over the years, it very much works like an on and off switch. It either is working or not.

I understand notifications are an option for this, but they are not an ideal option. Notifications would ping me when other users are watching, whether I am available to debug or not, and do not help to see historical trends, unless notifications are piped to a secondary system.

> If you find out otherwise then I would be interested to see the data and it should then be raised as a bug with Plex.

I shared ~~screenshots above, and~~ a link to docs which indicate this is not a bug.

> This is a good idea. You can also use the API to pull the history table.

I will attempt this approach.

It sounds like you've made a decision not to support this feature, so feel free to close the ticket.

**Comment by johnmaguire** [comment]
> This video is being direct streamed (`copy`) so there is no video transcoding, thus no hardware transcoding required.

I saw this as well, but the text in the screenshot shows "transcode." Does this mean it will also appear in the graph as a transcode, or a direct stream?

**Comment by JonnyWong16** [comment]
> I shared screenshots above that seem to prove this is not the case.

You shared a screenshot of _direct stream_ video. Can you share a screenshot of _transcode_ video without hardware transcoding?

**Comment by johnmaguire** [comment]
> > I shared screenshots above that seem to prove this is not the case.
> 
> You shared a screenshot of _direct stream_ video. Can you share a screenshot of _transcode_ video without hardware transcoding?

I removed that part of my comment. Did you give the link a read? Specifically this part:

> When possible, Plex Media Server uses hardware acceleration for both decoding and encoding. Some formats are not compatible with hardware acceleration for decoding. In those cases, normal software decoding without hardware acceleration will automatically be used.

**Comment by samwiseg0** [comment]
> I saw this as well, but the text in the screenshot shows "transcode." Does this mean it will also appear in the graph as a transcode?

Yes. That is the overall plex decision as I stated early on in my first message. Plex decided that the stream is transcode because it is transcoding the audio and changing the container. 

Again the video was not transcoded at all hence why your ask in this case would not show anything on the graph since the video was not touched.

**Comment by johnmaguire** [comment]
> > I saw this as well, but the text in the screenshot shows "transcode." Does this mean it will also appear in the graph as a transcode?
> 
> Yes. That is the overall plex decision as I stated early on in my first message. Plex decided that the stream is transcode because it is transcoding the audio and changing the container.
> 
> Again the video was not transcoded at all hence why your ask in this case would not show anything on the graph since the video was not touched.

I understand that. I'm simply asking how it will appear in the graph today (direct stream or transcode?)

**Comment by samwiseg0** [comment]
> I understand that. I'm simply asking how it will appear in the graph today (direct stream or transcode?)

Transcode.

**Comment by johnmaguire** [comment]
> > I understand that. I'm simply asking how it will appear in the graph today (direct stream or transcode?)
> 
> Transcode.

Thanks. @JonnyWong16 stated above that this is a direct stream. Ultimately, this is what has led to my confusion. I see a transcode occurring in the UI, but `nvidia-smi` doesn't show any processes (indicating a hardware transcode is not occurring.)

If this is a direct stream, but appears in the graph as a transcode, what is the criteria for a video file to show in the graph as a direct stream?

Thanks for all the info so far. I am spot checking my History and so far am unable to find any instances of a non-HW transcode. However, Plex's docs _clearly indicate_ that this is possible depending on the video format. (I just want to reiterate this as it has gone unacknowledged in the thread above.)

edit: Though maybe this is splitting hairs. The encode is still HW-accelerated, but the decode is not. Tautulli of course doesn't make a distinction in the graph.

**Comment by herby2212** [comment]
> Thanks for all the info so far. I am spot checking my History and so far am unable to find any instances of a non-HW transcode. However, Plex's docs _clearly indicate_ that this is possible depending on the video format. (I just want to reiterate this as it has gone unacknowledged in the thread above.)
> 
> edit: Though maybe this is splitting hairs. The encode is still HW-accelerated, but the decode is not. Tautulli of course doesn't make a distinction in the graph.

As you pointed already out it needs to be differentiated between encode and decode when talking about hardware accelaration / hardware transcoding. While Tautulli doesn't make this distinction in the graph the data exists in its `database` which allows you to make a analysis based on that or by using a `API` like plexpy and a custom script.

In my opinion it is a interesting, but very special use case which can be analyzed very good via the tools previously mentioned, but isn't ideal for a generalized graph as I mentioned in my last post.

**Comment by johnmaguire** [comment]
Yeah, that makes sense.

> If this is a direct stream, but appears in the graph as a transcode, what is the criteria for a video file to show in the graph as a direct stream?

If anyone is able to provide an answer to this Q, I think all my questions have been answered and this ticket can be closed. Again, I appreciate all the info shared in this ticket so far.

**Comment by JonnyWong16** [comment]
> If this is a direct stream, but appears in the graph as a transcode, what is the criteria for a video file to show in the graph as a direct stream?

Direct stream video and direct stream audio.

**Comment by johnmaguire** [comment]
> > If this is a direct stream, but appears in the graph as a transcode, what is the criteria for a video file to show in the graph as a direct stream?
> 
> Direct stream video and direct stream audio.

Got it, so the transcode audio is what causes this one to be listed as a transcode?

Thanks for all the help.
