### ISSUE TITLE
View Library contents only

### ISSUE THREAD

**Issue by bevenhall** [JonnyWong16/plexpy#2170]
### What is your feature request?

I'd really like to have a (unauthorized+proxyable) page with the contents of my libraries presented "view only". Currently I'm using [https://github.com/Tensai75/plpp](url) for i.e. [https://plex.bevenhall.se/](url), but it's a bit slow, buggy and limited. I believe tautulli utilizes the API more efficiently. (Purpose is only to show other potential Plex Sharers "I have this to share".)

**Comment by JonnyWong16** [comment]
Sorry, this is outside the scope of Tautulli.
