### ISSUE TITLE
Import Plex Play History for new installations

### ISSUE THREAD

**Issue by fabianschaefer** [JonnyWong16/plexpy#2181]
### Is your feature request related to a problem?

I used Plex for a decade before discovering and installing Tautulli. My purpose in installing Tautulli was to analyze data like "what movies have never been watched." Unfortunately, Tautulli only monitors activities starting from the day of installation and cannot import any of the previous Plex Play History.
It is clear that the Tautulli metadata is much more detailed compared to the Plex Play History. Nevertheless, an import option of Plex Play History metadata would be very useful for setups where Tautulli was not present from the beginning.

### What is your feature request?

It would be great to add a feature that allows importing the Plex Play History back to the date Tautulli was installed. The Plex DB has a table `metadata_item_views` which contains all the historical data. Of course nowhere near as detailed as the Tautulli DB, but it would still allow a lot of analysis. 
A one-time import feature of the Plex play history (perhaps also included by default in the onboarding process) would add a lot of value for users who had been running Plex for many years before they started using Tautulli.

**Comment by JonnyWong16** [comment]
Duplicate #1611, #639, #53.
