### ISSUE TITLE
After update to 2.13.2 ambiguous column name: on_pause

### ISSUE THREAD

**Issue by clara-j** [JonnyWong16/plexpy#2184]
### Describe the Bug

Running through docker-compose with image linuxserver/tautulli

After watchtower auto updated my install to 2.13.2 this morning Tautulli now fails to start up with this in the logs.

No issues prior to the update and I can see my monitoring show it go offline at midnight when the update happened and never came back up.

tautulli                    | 2023-10-27 16:01:47 - INFO :: Thread-1 (startup_refresh) : Tautulli PlexTV :: Requesting resources for server...
tautulli                    | 2023-10-27 16:01:47 - INFO :: MainThread : Tautulli NotificationHandler :: Starting background notification handler (2 threads).
tautulli                    | 2023-10-27 16:01:47 - ERROR :: MainThread : Tautulli Database :: Database error: ambiguous column name: on_pause
tautulli                    | 2023-10-27 16:01:47 - INFO :: Thread-1 (startup_refresh) : Tautulli PlexTV :: Pinging Plex.tv to refresh token.
tautulli                    | 2023-10-27 16:01:47 - ERROR :: MainThread : Uncaught exception: Traceback (most recent call last):
tautulli                    |   File "/app/tautulli/Tautulli.py", line 324, in <module>
tautulli                    |     main()
tautulli                    |   File "/app/tautulli/Tautulli.py", line 247, in main
tautulli                    |     plexpy.start()
tautulli                    |   File "/app/tautulli/plexpy/__init__.py", line 569, in start
tautulli                    |     notifiers.check_browser_enabled()
tautulli                    |   File "/app/tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
tautulli                    |     for n in get_notifiers():
tautulli                    |              ^^^^^^^^^^^^^^^
tautulli                    |   File "/app/tautulli/plexpy/notifiers.py", line 510, in get_notifiers
tautulli                    |     result = db.select(
tautulli                    |              ^^^^^^^^^^
tautulli                    |   File "/app/tautulli/plexpy/database.py", line 455, in select
tautulli                    |     sql_results = self.action(query, args).fetchall()
tautulli                    |                   ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli                    |   File "/app/tautulli/plexpy/database.py", line 433, in action
tautulli                    |     sql_result = c.execute(query, args)
tautulli                    |                  ^^^^^^^^^^^^^^^^^^^^^^
tautulli                    | sqlite3.OperationalError: ambiguous column name: on_pause
tautulli                    | 
tautulli                    | Traceback (most recent call last):
tautulli                    |   File "/app/tautulli/Tautulli.py", line 324, in <module>
tautulli                    |     main()
tautulli                    |   File "/app/tautulli/Tautulli.py", line 247, in main
tautulli                    |     plexpy.start()
tautulli                    |   File "/app/tautulli/plexpy/__init__.py", line 569, in start
tautulli                    |     notifiers.check_browser_enabled()
tautulli                    |   File "/app/tautulli/plexpy/notifiers.py", line 4483, in check_browser_enabled
tautulli                    |     for n in get_notifiers():
tautulli                    |              ^^^^^^^^^^^^^^^
tautulli                    |   File "/app/tautulli/plexpy/notifiers.py", line 510, in get_notifiers
tautulli                    |     result = db.select(
tautulli                    |              ^^^^^^^^^^
tautulli                    |   File "/app/tautulli/plexpy/database.py", line 455, in select
tautulli                    |     sql_results = self.action(query, args).fetchall()
tautulli                    |                   ^^^^^^^^^^^^^^^^^^^^^^^^
tautulli                    |   File "/app/tautulli/plexpy/database.py", line 433, in action
tautulli                    |     sql_result = c.execute(query, args)
tautulli                    |                  ^^^^^^^^^^^^^^^^^^^^^^
tautulli                    | sqlite3.OperationalError: ambiguous column name: on_pause

### Tautulli Version

2.13.2

### Git Branch

master

### Git Commit Hash

c215afbf84baafb1a2020c2dc6e36944a6de1504

### Platform and Version

Linux Ubuntu 22.04

### Python Version

3.11.6

### Browser and Version

Firefox

### Link to Logs

https://gist.github.com/clara-j/af74edcb3f0fd4f9b4adf1c853cbb2db

**Comment by JonnyWong16** [comment]
Duplicate #2183.
