### ISSUE TITLE
Database error: ambiguous column name: on_pause

### ISSUE THREAD

**Issue by dacmcbibs** [JonnyWong16/plexpy#2185]
### Describe the Bug

After upgrading to 2.13.2 Tautulli will not start up with an error of

MainThread : Tautulli Database :: Database error: ambiguous column name: on_pause
This does not occur on 2.13.1 (downgrading to 2.13.1 resolves the issue)

### Steps to Reproduce

Upgrade docker container from 2.13.1 to 2.13.2

### Tautulli Version

2.13.2

### Git Branch

master

### Git Commit Hash

c215afbf84baafb1a2020c2dc6e36944a6de1504

### Platform and Version

[Docker] Linux 6.1.49-Unraid (#1 SMP PREEMPT_DYNAMIC Wed Aug 30 09:42:35 PDT 2023 - Alpine Linux 3.18.4)

### Python Version

3.11.6 (main, Oct 4 2023, 06:22:18) [GCC 12.2.1 20220924]

### Browser and Version

Chrome 117.0.5938.152 

### Link to Logs

https://gist.github.com/dacmcbibs/e0c09da8881d1c3c510c983a95052684

**Comment by JonnyWong16** [comment]
Duplicate #2184, #2183.
