### ISSUE TITLE
Errors with v2.13.2

### ISSUE THREAD

**Issue by ameer1234567890** [JonnyWong16/plexpy#2189]
### Describe the Bug

I am getting the below errors on v2.13.2. I have tried with a fresh install too. The previous version v2.13.1 works for me.

Log here.

```
usermod: no changes
Running Tautulli using user tautulli (uid=1000) and group tautulli (gid=1000)
Traceback (most recent call last):
  File "/app/Tautulli.py", line 39, in <module>
    import plexpy
  File "/app/plexpy/__init__.py", line 86, in <module>
    from plexpy import webstart
  File "/app/plexpy/webstart.py", line 32, in <module>
    from plexpy import webauth
  File "/app/plexpy/webauth.py", line 30, in <module>
    import jwt
  File "/app/lib/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/app/lib/jwt/api_jwk.py", line 7, in <module>
    from .algorithms import get_default_algorithms, has_crypto, requires_cryptography
  File "/app/lib/jwt/algorithms.py", line 12, in <module>
    from .utils import (
  File "/app/lib/jwt/utils.py", line 7, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/primitives/asymmetric/ec.py", line 11, in <module>
    from cryptography.hazmat._oid import ObjectIdentifier
  File "/usr/local/lib/python3.9/site-packages/cryptography/hazmat/_oid.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import (
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
usermod: no changes
Running Tautulli using user tautulli (uid=1000) and group tautulli (gid=1000)
```

### Tautulli Version

v2.13.2

### Git Branch

master

### Git Commit Hash

c215afbf84baafb1a2020c2dc6e36944a6de1504

### Platform and Version

Raspbian GNU/Linux 11 (bullseye)

### Python Version

3.9.2

### Browser and Version

Chrome 119.0.6045.105

### Link to Logs

https://gist.github.com/ameer1234567890/0d4a03aa20ed7f751c36347f0e8d263e

**Comment by JonnyWong16** [comment]
Can you upgrade to Raspbian 12 (bookworm)?

**Comment by ameer1234567890** [comment]
I will be upgrading in the next few weeks. In the meantime, is it relevant since I am running this on docker?

**Comment by hedeon** [comment]
Hello, I have the same error and I think I have found the cause. The reference to debian 12 was the right direction. I changed the tautulli-base image from python:3.9-slim to python:3.9-slim-bullseye and used that to create the tautulli image. Now tautulli v2.13.2 starts normally again.

**Comment by JonnyWong16** [comment]
> I will be upgrading in the next few weeks. In the meantime, is it relevant since I am running this on docker?

To be clear, update to the 64-bit OS.

Alternatively, confirmed on Discord, force installing the 64-bit version seems to works.

1. Delete your Tautulli container and image:
    ```
    docker rm tautulli
    docker rmi ghcr.io/tautulli/tautulli:latest
    ```
2. Pull the `arm64` version:
    ```
    docker pull --platform linux/arm64 ghcr.io/tautulli/tautulli:latest
    ```
3. Recreate your Tautulli container.

**Comment by SuperSpe** [comment]
this is not working on docker. same error even with your hint image

**Comment by SuperSpe** [comment]
> Hello, I have the same error and I think I have found the cause. The reference to debian 12 was the right direction. I changed the tautulli-base image from python:3.9-slim to python:3.9-slim-bullseye and used that to create the tautulli image. Now tautulli v2.13.2 starts normally again.

can you be more specific?

**Comment by hedeon** [comment]
Hello, I just saw your comment.

You can create the Docker image yourself.
First the base image with the Dockerfile from here: https://github.com/Tautulli/tautulli-baseimage
In the Dockerfile you have to change the Python version to python:3.9-slim-bullseye and then create the image.
Then download tautulli from here: https://github.com/Tautulli/Tautulli
Specify the image you just created in the Dockerfile and create the tautulli image.

Now you can use this image for your container.

**Comment by ameer1234567890** [comment]
Since I am using Tautulli on a live environment, I would prefer to avoid manual building. Would you be able to include a build for bullseye? If not, I can use the previous version for the time being and upgrade when I switch to bookworm.

PS: My upgrade schedule of "next few weeks" is being dragged back due to other issues with hardware availability.

**Comment by thunder2k** [comment]
Hi,
Same error here. 

Any solution for docker-compose?

**Comment by ElOledor** [comment]
Same error here
rpi4

```
dxx@raspberrypi:~ $ dpkg --print-architecture
armhf

dxx@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

docker-compose

```
 tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    platform: linux/arm64
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/xxx/config:/config
      - /home/xxx/logs:/logs
    ports:
      - 8181:8181
```

Also I changed in platfom -> platform: linux/armhf and not working

**Comment by JonnyWong16** [comment]
Did you remove the image in between recreating your container?

**Comment by valerioa-amd** [comment]
> Did you remove the image in between recreating your container?

How do you do it with docker-compose?

**Comment by JonnyWong16** [comment]
I _think_ it's `docker-compose down -rmi all`.

**Comment by ElOledor** [comment]
Yes I deleted all images and recreated the container

**Comment by thunder2k** [comment]
Hi,
Any news on this one? I tried to upgrade today to 2.13.14 and got the same error as OP.

Any help would be appreciated, as per the above comment, it doesn't work on Bookworm either, so upgrading is not the solution.

Please let me know if I can provide more info, I didn't post my logs as they're exactly as OP.

**Comment by ameer1234567890** [comment]
I can confirm that it works with bookworm

**Comment by jamie-2bit** [comment]
Still not working for me either after an upgarde today (was previously working fine).

**Here is the error I get:** 
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

**I am running Docker/Portainer on a 64 bit OS on raspberry pi 4:**

pi@Pi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

pi@Pi:~ $ arch
aarch64

I removed any old docker images and pulled the latest using the compose file below:

**Docker Compose:**
version: '3'
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /home/pi/configs/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    ports:
      - 8181:8181

**Comment by jamie-2bit** [comment]
@JonnyWong16 - Is there a docker image you recommend we use in the compose file?

**Comment by JonnyWong16** [comment]
Please see above. Update to bookworm.

**Comment by jamie-2bit** [comment]
> Please see above. Update to bookworm.

Thanks @JonnyWong16 - It's not possible for me to do that at the moment, is there an older version of the Tautulli docker image I can pull / roll back to that would work? (unfortunately, I deleted the old working image in docker)

**Comment by gritaro** [comment]
> > Please see above. Update to bookworm.
> 
> Thanks @JonnyWong16 - It's not possible for me to do that at the moment, is there an older version of the Tautulli docker image I can pull / roll back to that would work? (unfortunately, I deleted the old working image in docker)

As thread starter noted, latest working version is v2.13.1
