### ISSUE TITLE
Notification on Telegram - Too Many Requests

### ISSUE THREAD

**Issue by Basti-RX** [JonnyWong16/plexpy#2190]
### Describe the Bug

Hi.
When I add multiple movies, the notification agent for Telegram stops working because there are too many requests.
The logs show it. Unfortunately, I haven't found the option to set a waiting time in between.
![Screenshot 2023-11-04 at 12-20-28 Tautulli - Log HADES](https://github.com/Tautulli/Tautulli/assets/24960835/bb84a11c-7b3c-4091-9166-3573f21bb8d7)

### Steps to Reproduce

Add more than 20 Movies to Plex

### Tautulli Version

2.13.1

### Git Branch

master

### Git Commit Hash

v2.13.1

### Platform and Version

[Docker] Linux 6.1.49-Unraid

### Python Version

3.11.6 (main, Oct 4 2023, 06:22:18) [GCC 12.2.1 20220924]

### Browser and Version

Firefox 119

**Comment by JonnyWong16** [comment]
No, there is no way to delay notifications. Your best option is to disable notification when mass adding media or use the newsletter feature instead.
