### ISSUE TITLE
Transcoding dashboard 

### ISSUE THREAD

**Issue by L-P-G** [JonnyWong16/plexpy#2197]
### Is your feature request related to a problem?

It would be great if we had a historical section and/or dashboard for transcoding streams.

### What is your feature request?

Having the ability to see what a specific file was transcoded to and for what device/user would be extremely helpful when trying to setup tdarr profiles as well as dealing with the "it's buffering" complaints. It would allow us to retroactively see what was being transcoded at a point in time to rule out hardware issues. 

### Are there any workarounds?

Watch the status dashboard live to catch who is transcoding what and why. However, this is tedious as there could be multiple permutations of files, to devices.

**Comment by JonnyWong16** [comment]
Is this not just filtering by transcode on the history tab? You can also click on the "Player" for any row in the history for details.

**Comment by L-P-G** [comment]
> Is this not just filtering by transcode on the history tab? You can also click on the "Player" for any row in the history for details.

Correct. You can see which devices and files were transcoded.

I should have been clearer in my intent. My apologies.

The end goal was to be able to see avg transcoding speed, source format to streamed format, audio transcoding, subtitles, etc. In other words, data useful to troubleshoot why something buffered.
