### ISSUE TITLE
Add stream buffering as a trigger for notification agents

### ISSUE THREAD

**Issue by qwe304** [JonnyWong16/plexpy#2205]
### Is your feature request related to a problem?

Occasionally, my users for one reason or another, have issues playing back media, whether their device is too slow, they tried burning subs on a 4k bdrip, or whatever. This can cause massive buffering or stuttering, without throwing an error itself.

### What is your feature request?

I think it would be nice to add an option to send a notification when the (transcode) buffer is below a certain threshold and video is paused (some time after initial playback) or if buffering itself could be detected. This would let me proactively look into and notify my users of any potential issues, rather than hearing about it weeks later after they gave up.

**Comment by JonnyWong16** [comment]
There is already a buffer warning notification trigger.
