### ISSUE TITLE
Issue Tautulli after upgrade 2.13.3

### ISSUE THREAD

**Issue by yaya059** [JonnyWong16/plexpy#2210]
### Describe the Bug

Hello ALL,

after upgrade the container tautulli (on unraid ) on the latest version i get some error on the dashboard settings with operand

Thanks in advance

### Screenshots

<img width="1323" alt="Capture d’écran 2023-12-06 à 12 47 59" src="https://github.com/Tautulli/Tautulli/assets/95930467/e45f6809-c080-49e7-a75c-74d8f1737dc2">

### Tautulli Version

2.13.3

### Git Branch

master

### Git Commit Hash

not showed spite of issue

### Platform and Version

Unraid 6.12.5

### Python Version

not showed spite of issue

### Browser and Version

edge 119.0.2151.97 

### Link to Logs

https://gist.github.com/yaya059/35852e00227c433fa4b14e4fbc225806

**Comment by JonnyWong16** [comment]
Your system doesn't have a language. 

```
2023-12-05 21:16:25 - INFO    :: MainThread : Language None / Encoding UTF-8
```

Please try our official Docker container instead.

**Comment by yaya059** [comment]
Thanks a lot effectively with official repo it's better ;-)
