### ISSUE TITLE
Login does not work with Firefox

### ISSUE THREAD

**Issue by MagicalCrib** [JonnyWong16/plexpy#2212]
### Describe the Bug

Can't login in Tautulli in Firefox (120.0.1), neither using Plex login, neither using a username and password. Tested in Chrome and it worked.

Looking at the logs, I see the autenthication is successful. Log using Plex login:
`2023-12-07 10:38:50 - DEBUG   :: CP Server Thread-13 : Tautulli WebAuth :: Admin user 'Pe********s' logged into Tautulli using Plex OAuth login.
`
Log using username and password:
`2023-12-07 10:38:55 - DEBUG   :: CP Server Thread-9 : Tautulli WebAuth :: Admin user 'my login' logged into Tautulli using form login.`

After trying to login the page seems to reload, but does not redirect to the Tautulli interface.

### Expected Behavior

Login should work in Firefox.

### Tautulli Version

v2.13.3

### Git Branch

can't see it

### Git Commit Hash

8cb74f74806863abbc47419d85b002abb600ea00

### Platform and Version

Docker on QNAP

### Python Version

3.11.6

### Browser and Version

Firefox 120.0.1

### Link to Logs

https://gist.github.com/modem/825a472ff8966e9600b0ef34351af2fb

**Comment by JonnyWong16** [comment]
There's a bug when "Remember Me" is unchecked.
