### ISSUE TITLE
Error on Tautulli Help & Info page

### ISSUE THREAD

**Issue by MagicalCrib** [JonnyWong16/plexpy#2213]
### Describe the Bug

When opening the Help & Info page in Tautulli, there's some python errors showing up.

### Screenshots

![image](https://github.com/Tautulli/Tautulli/assets/62859/a07e9137-adcf-42c3-a2fe-90b92520ddf0)

### Tautulli Version

v2.13.3

### Git Branch

can't see it due to the errors

### Git Commit Hash

8cb74f74806863abbc47419d85b002abb600ea00

### Platform and Version

Docker on QNAP NAS

### Python Version

3.11.6

### Browser and Version

Chrome 119.0.6045.200

### Link to Logs

https://gist.github.com/modem/1ee1488e1f5e0cf50208caeb64384a4c

**Comment by JonnyWong16** [comment]
Duplicate #2210.
