### ISSUE TITLE
(Feature Request) Highlight Season Finale or Filter by Season Finale in History

### ISSUE THREAD

**Issue by Paxonator31** [JonnyWong16/plexpy#2217]
### What is your feature request?

When I'm browsing through the history to find fully watched items that I can clear off my server I have to go check and see what the finale episode was for each tv show to verify. Just thought it would be nice for the season finale to be highlighted or be able to filter by season finale to aid with this.

**Comment by JonnyWong16** [comment]
How do I know if an episode is a finale?

The metadata comes from Plex. How does Plex know if an episode is a finale?

**Comment by Paxonator31** [comment]
> How do I know if an episode is a finale?
> 
> The metadata comes from Plex. How does Plex know if an episode is a finale?

Sorry I'm not entirely sure of the inner workings, but sonarr knows the season finale. Maybe there's a way to link it to that, I don't know.

**Comment by JonnyWong16** [comment]
Tautulli only talks to Plex.

This isn't possible, so I'm closing this until Plex provides finale info.
