### ISSUE TITLE
Add 'Recently Removed' as a notification agent trigger

### ISSUE THREAD

**Issue by Feenix3** [JonnyWong16/plexpy#2230]
### What is your feature request?

I would like the option to notify via the Discord agent (and others for benefit of the community) when media items are removed please.  Thank you.

### Additional Context

My scenario is that I use PlayOn Home to add media to my Plex server.  When a recording starts the media item is immediately detected and notified by Tautulli via Discord using the 'Recently Added' trigger.  The trouble is sometimes the recording will fail and the media item is removed with no notification.

**Comment by JonnyWong16** [comment]
Duplicate #1906.
