### ISSUE TITLE
Artist statistics returning track not album artists

### ISSUE THREAD

**Issue by RaunoT** [JonnyWong16/plexpy#2232]
### Describe the Bug

Doesn't make sense for track artist to be returned. Music is organized by album not track artists generally speaking. 

Let's say I want to query my top 5 artists via `get_home_stats`:

<img width="521" alt="image" src="https://github.com/Tautulli/Tautulli/assets/22045687/3027fad3-877f-41c6-86fe-3d2404dad367">

I'm expecting this to be 1. Slash; 2. Johnny Cash. All the featured tracks are from the same album also in this case.
They return the same `rating_key` when queried, so they should be grouped together.

Probably related to https://github.com/Tautulli/Tautulli/issues/600, but that issue was marked completed without any feedback.

### Steps to Reproduce

1. Query Tautulli API for some artist stats, e.g `&cmd=get_home_stats`
2. Observe `top_music` or `popular_music` array, title will contain "featured" for tracks with multiple artists

### Expected Behavior

The album, not track artist is returned.
Items using the same `rating_key` are grouped.

### Tautulli Version

v2.13.4

### Git Branch

master

### Git Commit Hash

d019efcf911b4806618761c2da48bab7d04031ec

### Platform and Version

Windows 10 (10.0.22631)

### Python Version

3.9.13

### Browser and Version

Chrome 120.0.6099.129

### Link to Logs

N/A

**Comment by jackctra** [comment]
The exception are compilations where the album artist typically is ‘Various Artists‘ and where the track artist is the one you‘re looking for. Best would be logic like album artist if not album artist = Various Artists

**Comment by JonnyWong16** [comment]
This is not a bug since it's working as intended. The statistics were changed to track artists becuase of the "Various Artists" issue in #600.
