### ISSUE TITLE
Since of 2 days im getting this error:

### ISSUE THREAD

**Issue by IIIdefconIII** [JonnyWong16/plexpy#2239]
### Describe the Bug

Since of two days im getting a pi key error in my homepage:

I already generated the API key 2 or 3 times, I even edit te one in:
config.infi manually in the API key = line.

I restarted both plex and tautulli it container but i cant find out when its not going up so im wondering if there is a bug in homepage because it says

API Error: Unexpected token 'I', "Internal S"... is not valid JSON

Is someone willing to help me with this?

### Steps to Reproduce

Configure the API key in homepage

### Expected Behavior

Getting the API information to show up in homepage

### Screenshots

![image](https://github.com/Tautulli/Tautulli/assets/9917659/acd92f8e-2734-44dd-86be-2e761d1e868f)

### Relevant Settings

   - Tautulli:
        server: my-docker
        container: tautulli
        description: Media Library (.10:8181)
        ping: http://10.3.10.10:8181
        icon: tautulli.png
        href: https://tautulli.iiidefconiii.info
        widget:
            type: plex
            url: http://10.3.10.10:8181
            key: APIKEY
            
### Tautulli Version

VERSION V2.13.4  Changelog

### Git Branch

ghcr.io/tautulli/tautulli

### Git Commit Hash

d019efcf911b4806618761c2da48bab7d04031ec

### Platform and Version

DSM 7.2.1-69057 Update 3

### Python Version

3.9.18 (main, Nov 29 2023, 05:59:34) [GCC 12.2.0]

### Browser and Version

Chrome latest also trief on Firefox Latest

### Link to Logs

https://gist.github.com/IIIdefconIII/8ad54ea11d9034c2c01577842ebd31ed

**Comment by JonnyWong16** [comment]
I have no idea what that screenshot is. Whatever it is, it is not from Tautulli, so you need to contact whoever created that app.

**Comment by IIIdefconIII** [comment]
Ah that on homepage but I ask them too maybe be something on their end. Thanks for responding so quickly do!!
Hope getting it know which command actually work to close it

!archive
!close
#archive
#close


Met vriendelijke groet,

________________________ _______________________
Thomas van Dalen

E: ***@***.******@***.***>

T: +316 30 929 009

________________________________

**Comment by IIIdefconIII** [comment]
Maybe we can work together to fix it

https://github.com/gethomepage/homepage/discussions/2619

**Comment by IIIdefconIII** [comment]
hi Taut-Team can we reopen this and check my update on the link i have posted in my previous post which i have updated with more information
