### ISSUE TITLE
Add DOVI to stream details from Plex

### ISSUE THREAD

**Issue by sahara101** [JonnyWong16/plexpy#2240]
### Is your feature request related to a problem?

Hi :)

Is it possible to have (or do we already have) the option to set a condition in notification agents by DV profile?

### What is your feature request?

Would like to send a notification to users when playing Profile 5

Thanks!

**Comment by samwiseg0** [comment]
Please stop by the discord server so we can get some more context as to what you would like to do. Thanks!
