### ISSUE TITLE
ListenBrainz submission support

### ISSUE THREAD

**Issue by UnviableFriend** [JonnyWong16/plexpy#2241]
### Is your feature request related to a problem?

Plex supports scrobbling to Last.fm, but [according to a Plex dev](https://forums.plex.tv/t/eavesdrop-fm-sync-plex-music-listens-to-listenbrainz/580467/5) 
> ListenBrainz support has been discussed internally with the Plex team, and isn’t something they’re able to implement at this time.

The dev there created eavesdrop.fm, but it uses web hooks and is apparently limited in the information it can retrieve and submit. Plus you then rely on a 3rd party to forward submissions.

### What is your feature request?

I would love to see Tautulli support submitting Listens to [ListenBrainz](https://listenbrainz.org/). Tautulli is already running and monitoring activity on users servers, and has more direct access to data on the server so it could submit much more [complete listen information](https://listenbrainz.readthedocs.io/en/latest/users/json.html#payload-json-details)

### Are there any workarounds?

[Eavesdrop.fm](https://forums.plex.tv/t/eavesdrop-fm-sync-plex-music-listens-to-listenbrainz/580467/1) is an alternative. But it can't access as much information such as MBIDs, ISRCs, etc. Which means ListenBrainz has lower chances of matching listens to MusicBrainz entries. Users then have to manually link them to correct it which can be tedious and time consuming.

[Last.fm](https://www.last.fm) data can be imported into ListenBrainz, and Plex does have built in support for Last.fm. But again there is a lack of detailed information through this method resulting in similar issues to Eavesdrop.fm.

### Additional Context

[ListenBrainz](https://listenbrainz.org/) is a [MetaBrainz](https://metabrainz.org/) project ([MusicBrainz](https://musicbrainz.org/) is used by Plex as a metadata source, and is where the data comes from when you pick to match an artist or release, and is also MetaBrainz) and is [Open Source](https://github.com/metabrainz) and [Open Data](https://listenbrainz.org/data/). It is also very actively being developed and solves a lot of problems with Last.fm.

An additional benefit of this is more users using ListenBrainz means it has more data and can be a future alternative to Last.fm for things such as Popular Tracks data(And Plex does already work with MusicBrainz so it makes sense since the data is linked with MBIDs).

**Comment by JonnyWong16** [comment]
I'm going to say no, this is outside the scope of Tautulli.

If you want to do this then use a script or webhook notification.
