### ISSUE TITLE
Show client Plex App Version on Tautulli dashboard

### ISSUE THREAD

**Issue by origamiofficial** [JonnyWong16/plexpy#2243]
### Is your feature request related to a problem?

It's not related to any problem.

### What is your feature request?

Currently, Tautulli shows the below details from a stream in the dashboard:
* PRODUCT
* PLAYER
* QUALITY
* STREAM
* CONTAINER
* VIDEO
* AUDIO
* SUBTITLE
* LOCATION
* BANDWIDTH

It'll be nice to see if it shows the client Plex app version. Sometimes clients forget to update their app and face some problems in the long run. But if the server owner can see that the client is running an outdated version then they can notify the user to update their app. It'll be much easier to diagnose streaming issues for the server owners.

### Are there any workarounds?

Right now I need to check the Plex streaming URL for the client's Plex app version. The streaming URL usually look like this:

https://plex.domain.com/library/parts/1757920/1698885091/file.mkv?autoAdjustQuality=0&hasMDE=1&location=wan&mediaBufferSize=74944&X-Plex-Client-Identifier=abc4efg6ij7klm-com-plexapp-android&X-Plex-Client-Platform=Android&X-Plex-Device=RMX3363&X-Plex-DRM=widevine%3Avideo&X-Plex-Platform=Android&X-Plex-Platform-Version=12&X-Plex-Product=Plex%20for%20Android%20(Mobile)&X-Plex-Token=XXXXXXXX&X-Plex-Version=10.6.0.5141

Here the client Plex app version value is located in the `X-Plex-Version=10.6.0.5141`

**Comment by samwiseg0** [comment]
There is another way to check the version of the player. Click on `STREAM`. 

https://github.com/Tautulli/Tautulli/wiki/Debugging#stream-info

Personally I do not think this information should be present in the card and it would make it very cluttered as some plex client versions are really long. I think this is best left up to the server owner/admin to check the details in the stream by using the debug option linked.

**Comment by JonnyWong16** [comment]
Agreed, the card has enough info. Use the stream info if you want all the detailed info.

**Comment by samwiseg0** [comment]
Also please change all your tokens as you leaked your token in the URL above. 

I have edited your post and removed it but out of an abundance of caution please change your password and invalidate all your tokens.

**Comment by origamiofficial** [comment]
That tolen was randomly typed string not a actual token.

**Comment by samwiseg0** [comment]
> That tolen was randomly typed string not a actual token.

Ah ok. It did not appear masked at first glance

**Comment by origamiofficial** [comment]
Thanks for both of your response!! Didn't knew the hidden "Stream"  details menu.

**Comment by origamiofficial** [comment]
@samwiseg0 & @JonnyWong16 first of all sorry for the ping. I want to set an alert in my Telegram if a user is running an outdated version of the Plex App via `Notification Agent`. But under `Conditions` there is no `Parameter` available for `{product_version}` or neither the `{platform_version}`. Possible to add or any other workaround?

**Comment by samwiseg0** [comment]
> @samwiseg0 & @JonnyWong16 first of all sorry for the ping. I want to set an alert in my Telegram if a user is running an outdated version of the Plex App via `Notification Agent`. But under `Conditions` there is no `Parameter` available for `{product_version}` or neither the `{platform_version}`. Possible to add or any other workaround?

You can open another issue requesting that be added to conditions. As for getting it to work today. I would suggest running a script that makes a call back to Tautulli to check the version. Use that script as your notifier and perform the actions you want. You can have the script call another notifier that will send the telegram notification. Some examples can be found in this repo. https://github.com/blacktwin/JBOPS

If you have further questions please use Discord.

Thanks
