### ISSUE TITLE
[Feature Request] Possiblity to merge users.

### ISSUE THREAD

**Issue by xAhlen** [JonnyWong16/plexpy#2247]
### What is your feature request?

I've seen that I'm not the only one who has brought this up. I would love a feature to merge users. 
I have some family that have been using my Plex Home account and they now switched over to their own personal account. But I have 4-5 years of statistics that I would like to merge with the account. Is there any plan even a tiny one that this will be a feature in the future?

**Comment by JonnyWong16** [comment]
Duplicate #2019
