### ISSUE TITLE
Add the ability to run any file as a notification agent

### ISSUE THREAD

**Issue by BenSokol** [JonnyWong16/plexpy#2249]
### What is your feature request?

I have a Debian package i wrote that id like to use as the notification agent.  It doesnt have an extension on it (like most deb packages/commands).  Add the ability for the Notification Agent > Script to select any file as the script, even those with no extension.

Could be as simple as wanting to run /usr/bin/echo with arguments.

### Are there any workarounds?

Not that im aware of for this, besides making a symlink to the command with an extension on the symlink

**Comment by JonnyWong16** [comment]
No.

This opened up an arbitrary code execution vulnerability that I fixed back in 2020.
