### ISSUE TITLE
Meta: #2268 closed as support request but is actually a bug

### ISSUE THREAD

**Issue by fromonesource** [JonnyWong16/plexpy#2269]
### Describe the Bug

Please re-open https://github.com/Tautulli/Tautulli/issues/2268 as it is a bug with notification templates, not a support request.

### Tautulli Version

https://github.com/Tautulli/Tautulli/issues/2268

### Git Branch

https://github.com/Tautulli/Tautulli/issues/2268

### Git Commit Hash

https://github.com/Tautulli/Tautulli/issues/2268

### Platform and Version

https://github.com/Tautulli/Tautulli/issues/2268

### Python Version

https://github.com/Tautulli/Tautulli/issues/2268

### Browser and Version

https://github.com/Tautulli/Tautulli/issues/2268

### Link to Logs

https://github.com/Tautulli/Tautulli/issues/2268

**Comment by JonnyWong16** [comment]
No, it is not a bug. You are using the wrong parameters.
