### ISSUE TITLE
Stream Info Doesn't Update When Audio Stream Is Chnaged During Playback

### ISSUE THREAD

**Issue by AlexKusnezov** [JonnyWong16/plexpy#2318]
### Describe the Bug

The stream snfo doesn't updates when I toggle/switch the audio stream during during pllaybac.k

### Steps to Reproduce

1. play a video on plex desktop app or androidtv apk:
<img width="516" alt="Screenshot 2024-05-02 at 16 33 52" src="https://github.com/Tautulli/Tautulli/assets/33514406/c4297e04-135e-4f3b-afe0-1da835e73f08">

2. select another audio stream:
<img width="304" alt="Screenshot 2024-05-02 at 16 28 26" src="https://github.com/Tautulli/Tautulli/assets/33514406/991ba1ee-a14e-4870-964b-544e8cc8c2ec">

3.Audio Info never gets updated until video is stopped and resumed

### Expected Behavior

The stream info should updated when audio stream is changed.

### Relevant Settings

platform_version: 14.4
product: Plex for Mac
product_version: 1.91.0.129-1cd63c1d
profile: Plex Desktop

### Tautulli Version

V2.13.4

### Git Branch

master

### Git Commit Hash

d019efcf911b4806618761c2da48bab7d04031ec

### Platform and Version

macOS 14.4

### Python Version

3.9.18 (main, Aug 28 2023, 08:38:55) [Clang 13.0.0 (clang-1300.0.29.30)]

### Browser and Version

Chrome Version 124.0.6367.118

### Link to Logs

https://gist.github.com/AlexKusnezov/a8bbe00f565482e083fea4c4bc23437e

**Comment by JonnyWong16** [comment]
This isn't a Tautulli issue. It's a Plex issue when direct playing. Since the entire file is sent to the client, the client can change the audio track at will without affecting the server. You can see this for yourself on the Plex Dashboard.

**Comment by AlexKusnezov** [comment]
@JonnyWong16 yes, I see thanks for clarifying. Just tried via web browser where it forced to transcode and the info got updated immediately
