### ISSUE TITLE
Bandwidth Total

### ISSUE THREAD

**Issue by aidopotatospud** [JonnyWong16/plexpy#2319]
### Is your feature request related to a problem?

No

### What is your feature request?

I'm hoping I can convince y'all to add a bandwidth monitor to include an 'RRD' or 'Cacti' like summary, over time. Maybe it could also be added to the Graphs or Stats section(s)... I know Plex and Tautulli give you real-time, which is great but I'd like to also see the historical record. Thank you for all you do, you are appreciated!

### Are there any workarounds?

Yes, the Cacti/RRD pkgs can be installed on the host and/or remote monitoring can be enabled.

### Additional Context

It'd just be nice to have all the stats in one spot.

**Comment by JonnyWong16** [comment]
Duplicate #1925, #2045.
