### ISSUE TITLE
Windows Security Virus Alert - Beta 2.14.0

### ISSUE THREAD

**Issue by TempestWales** [JonnyWong16/plexpy#2322]
### Describe the Bug

After updating from 2.13.4 to the beta 2.14.0, Windows Security Detects Tautulli.exe as a Trojan (Win32/Phonzy.A!ml) and is deleted.

### Steps to Reproduce

1) Install Beta 2.14.0
2) After install Virus Protection Removed file.

https://www.virustotal.com/gui/file/a098274f3aacd23e553f3404fb909068aa52ade041d06d9f704e585ef40b1b58

### Expected Behavior

No Trojan should be detected and Tautulli.exe should remain,

Reinstalled 2.13.4 and no issue with Virus Protection.

### Screenshots

![Tautulli_2 14 0_Trojan](https://github.com/Tautulli/Tautulli/assets/10633668/1c282326-4fd4-404a-98fc-57ea5be8ed35)
![Tautulli_2 14 0_VirusTotal](https://github.com/Tautulli/Tautulli/assets/10633668/9e053691-a9d6-48eb-82b9-9aafb9ee53f6)

### Relevant Settings

N/A

### Tautulli Version

2.14.0

### Git Branch

Nightly

### Git Commit Hash

N/A

### Platform and Version

Server 2019 Standard x64

### Python Version

N/A

### Browser and Version

Chrome 124

### Link to Logs

N/A

**Comment by JonnyWong16** [comment]
Windows Security with Security Intelligence version 1.411.12.0 does not detect anything for me.

You can report it as a false positive.

**Comment by karasuhebi** [comment]
2.14.2.1 is exhibiting similar behavior but it's reporting it as "Trojan:Script/Wacatac.B!ml". I'm on Security Intelligence version 1.411.440.0.

![image](https://github.com/Tautulli/Tautulli/assets/6857825/f4622cda-5f44-4e6e-80b8-c7c22051d499)

**Comment by Fire69** [comment]
Same trojan detected here just now with V2.14.2.
Updated somewhere last week I think, now all of a sudden Defender quarantined the .exe
 
Security Intelligence version 1.413.24.0

**Comment by JohnRo79** [comment]
hi guys

i have the same for the latest version

![image](https://github.com/Tautulli/Tautulli/assets/93069951/9e713d34-10ec-4b5e-ad11-0647df108be0)

**Comment by StephenCYang** [comment]
I'm also getting this same virus alert on the latest, v2.14.3.

**Comment by jjscaria** [comment]
> hi guys
> 
> i have the same for the latest version
> 
> ![image](https://private-user-images.githubusercontent.com/93069951/341399088-9e713d34-10ec-4b5e-ad11-0647df108be0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjY0MDAsIm5iZiI6MTcxODkyNjEwMCwicGF0aCI6Ii85MzA2OTk1MS8zNDEzOTkwODgtOWU3MTNkMzQtMTBlYy00YjVlLWFkMTEtMDY0N2RmMTA4YmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDIzMjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxM2FlM2YyYjE5MDUyZDA5ODU4NGJiNWRiM2ZlMmQxY2E2ZDQxZTIwNjNlOTMzODdkN2YzOTYwODMxYzc3Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wzDj7rah-vA9O3MG9B_8PQdOBbb7sNRNmpeUJJKdDA8)

same here

**Comment by ThatDumbUser** [comment]
Same error here. Any update on this?

![image](https://github.com/Tautulli/Tautulli/assets/10143278/f6725d5b-7961-4240-a46c-399f574bb3fb)

**Comment by StephenCYang** [comment]
Updated the virus definitions. KB2267602 (Version 1.413.441.0). Works now as expected.

If it's still an issue, force Windows Update to look for new updates.

**Comment by ThatDumbUser** [comment]
> Updated the virus definitions. KB2267602 (Version 1.413.441.0). Works now as expected.
> 
> If it's still an issue, force Windows Update to look for new updates.

EDITED!
Did work for me for a little while, however after about 16 hours the trojan was detected and Tautulli stopped working again. Rolled back to previous Tautilli version. Thinking of just removing this software all together as I never have more than two or three family members streaming at a time and I really don't care what they are watching.

**Comment by TempestWales** [comment]
Have to reinstall this every time my software is auto updated by script. Updating to latest definitions doesn't work. I'm probably going to get rid of it that same as @ThatDumbUser. Max 5 users at any one time, but just not worth the trouble any more. Clearly this won't be fixed.

**Comment by JonnyWong16** [comment]
I submitted it to Microsoft and they didn't detect anything. I'm not sure what else you expect me to do.

![image](https://github.com/Tautulli/Tautulli/assets/9099342/25ad30e6-bbdb-49ca-abc3-6246e8bbe398)

**Comment by ThatDumbUser** [comment]
> I submitted it to Microsoft and they didn't detect anything. I'm not sure what else you expect me to do.
> 
> ![image](https://private-user-images.githubusercontent.com/9099342/342113573-25ad30e6-bbdb-49ca-abc3-6246e8bbe398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTAzNzEsIm5iZiI6MTcxOTU1MDA3MSwicGF0aCI6Ii85MDk5MzQyLzM0MjExMzU3My0yNWFkMzBlNi1iYmRiLTQ5Y2EtYWJjMy02MjQ2ZThiYmUzOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDQ0NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBiZmI5OGIxZTRjMGU3Mzk5YTM0YzEwY2FkZDg5MzIwZmFjNWRhNGRmM2JhYTZhZDU4Y2FiNWEzYmY1MzE5MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tXOugMclFKDlOEnXT_n9M45boJOBSgjCAQmD59cGaog)

Understood BUT clearly they are detecting something or else this issue here #2322 would not exist.

**Comment by jleseane23** [comment]
I'm updated to the latest security intelligence version. (version 1.421.604 updated on 12/3/2024) and i'm getting this error too. Last Tautulli version that isn't flagging for me is 2.14.2

**Comment by bookish1303** [comment]
2.14.6 works fine for me with the latest update of 12/3/2024.

**Comment by nibble4bits** [comment]
Same here with version 2.15.0-x64 and Reported as false positive to Microsoft Edge.
![image](https://github.com/user-attachments/assets/e25c4561-223f-4501-aa68-52b71f4df733)

**Comment by xyzo** [comment]
With the actual version even more detections are reported, it's not an issue with Microsoft Defender only...



[https://www.virustotal.com/gui/file/db556f84ad19109269ea8cd132ee44bdff09af156b1f10b65ca75015e447221a]

<img width="1008" alt="Screenshot_62" src="https://github.com/user-attachments/assets/4db1d9ec-76c2-4a70-8411-d02677b142ff" />

**Comment by rosscarlson** [comment]
Still happening, just went to update to 2.15.1 and got the following:

![Image](https://github.com/user-attachments/assets/33b8823d-5b1e-44ff-b60a-2b9dcdf7bb42)

Seems a new/different trojan is detected: Trojan:Win32/Vigorf.A

While I'm inclined to trust the source it's troubling that the name of the trojan is changing, not sure if that leans more toward false or accurate detection but I suppose for now I'll just stay on the older version I'm running and not update.

Any further updates as to why this is happening??

**Comment by xyzo** [comment]
It seems the creator isn't interested in getting that fixed at all. I switched to the linux version as I don't think anymore that this is a false positive.

**Comment by goozchos** [comment]
I also get the trojan warning on 2.15.1. 
I had to go back to 2.14.3 to avoid it.

**Comment by StephenCYang** [comment]
Windows Defender, Security intelligence version 1.421.1968.0

Got this issue as well when Tautulli.exe was scanned.

My workaround was to make a folder exception for C:\Program Files\Tautulli in Defender's settings, though technically I could have just excluded the .exe file.

**Comment by toxicneo** [comment]
+1 here in Security Intelligence version 1.423.257.0, deleted my whole Tautulli folder and quarantined the file when I downloaded it again
