### ISSUE TITLE
Override for Notification Scripts : Allow Playback Stop Notifications Exceeding Watched Percent

### ISSUE THREAD

**Issue by nopoz** [JonnyWong16/plexpy#2323]
### Is your feature request related to a problem?

I have a custom script that turns off lights when playback starts and turns them back on when playback stops. However there are many conditions where the notification won't trigger on a stopped state if "Allow Playback Stop Notifications Exceeding Watched Percent" is not enabled. When this option is not checked, the playback has to be stopped manually by the user before the watched percent threshold is reached in order to trigger the notification. This means that all other scenarios won't trigger the script like playback naturally ending, clicking the "skip credits" button, manually ending playback with the remote after the watched threshold is reached, etc. 

### What is your feature request?

While this problem can be overcome by enabling "Allow Playback Stop Notifications Exceeding Watched Percent", the concern is that this will mess with tracking user watch states when it's only being enabled to trigger stop notifications. The feature request is to have a similar setting for the notification only rather than being forced to enable it globally. This would allow custom scripts like mine to be tripped and you won't mess up watch state tracking for users. Perhaps a toggle in the "Script Settings -> Configuration" tab. 

### Are there any workarounds?

Enable "Allow Playback Stop Notifications Exceeding Watched Percent" in the "Notifications & Newletters" settings page.

**Comment by JonnyWong16** [comment]
I don't know what you mean by 
> mess up watch state tracking for users

The setting only affects notifications and has nothing to do with history.

**Comment by nopoz** [comment]
Oh okay - I was reading https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions#q-my-playback-stop-notifications-are-not-working and thought it meant that tracking the user watch state would be messed up as well. If not, then I guess this can be closed.
