### ISSUE TITLE
Multiple discord webhooks for single notification agent

### ISSUE THREAD

**Issue by Piddox** [JonnyWong16/plexpy#2366]
### What is your feature request?

I would like to request the ability to add multiple discord webhooks to a single notification agent. For example when I'm in 2 discord servers and I want to push the same notifications to those 2 discord servers, I would currently have to setup 2 different notification agents and keep them in sync manually. This problem would be solved by having the option to add multiple discord webhooks to a single notification agent.

### Are there any workarounds?

Yes, multiple notification agents.

**Comment by JonnyWong16** [comment]
No, use two agents.

**Comment by Piddox** [comment]
Alright, too bad. Can I then request to have the option to link a notification agent to another notification agent? So that if I change a setting in one notification agent, that change will automatically be mirrored to the other notification agent. Would that be feasible?
