### ISSUE TITLE
Display the bitrate in the notification as Mbps instead of the default kbps

### ISSUE THREAD

**Issue by Piddox** [JonnyWong16/plexpy#2367]
### What is your feature request?

Hi, I would like to request a feature to display the bitrate in the notification as Mbps instead of the default kbps. Currently it seems the total bitrate of the video is always displayed in kbps, for example 25678. I would like to request that this bitrate can be shown as 25.7 for example.

### Are there any workarounds?

No, not to yield the desired result.

**Comment by JonnyWong16** [comment]
Click the help text at the top for text modifiers. There's an example in there for Mbps using expressions.
