### ISSUE TITLE
Tautulli failing to start after updating sqlite3 to v3.46.0,1

### ISSUE THREAD

**Issue by subi75** [JonnyWong16/plexpy#2385]
### Describe the Bug

Tautulli fails to load on TrueNAS Core after upgrading sqlite3 to sqlite3-3.46.0,1

### Steps to Reproduce

Have working current version (v2.14.4) of Tautulli hosted in TrueNAS Core jail with following versions installed:
python39 v3.6.18_2
libffi v3.4.4_1
libedit v3.1.20230828_1,1
libnghttp2 v1.61.0
sqlite3 v3.45.1,1
libps1 v0.21.5
py39-sqlite3 v3.9.18_7
python v3.9_3,2
curl v8.7.1

stop tautulli service

Upgrade/install to the following versions using pkg:
python39 v3.6.19
libffi v3.4.6
libedit v3.1.20240517,1
python311-3.11.9
libnghttp2 v1.62.1
sqlite3 v3.46.0,1
libps1 v0.21.5_1
py39-sqlite3 v3.9.19_7
python v3.11_3,2
curl v8.9.1

start tautulli service
receive error as per attached screenshot file "02862ceb-73cd-4af3-8fbb-037308559e0d"

### Expected Behavior

Expect Tautulli service to start successfully and be accessible via url https://192.168.5.12:8181

### Screenshots

![image](https://github.com/user-attachments/assets/02862ceb-73cd-4af3-8fbb-037308559e0d)

### Tautulli Version

2.14.4

### Git Branch

Master

### Git Commit Hash

623a9f291926fd279bc2f15e17d40429e1d78219

### Platform and Version

TrueNAS Core 13.0_U6.2

### Python Version

3.11_3,2

### Browser and Version

Not applicable

### Link to Logs

Not applicable - No Tautulli log entries generated during start

**Comment by JonnyWong16** [comment]
You have `py39-sqlite3` installed for Python 3.9, but your screenshot shows it trying to use Python 3.11 instead of Python 3.9.
