### ISSUE TITLE
Multiple Plex Servers under one Tautulli Dashboard

### ISSUE THREAD

**Issue by moloch2689** [JonnyWong16/plexpy#2393]
### Is your feature request related to a problem?

Good day,  Love the work being done here.   I have two separate PMS running and I was trying to add my second one in Tautulli, however, it's one or the other. 

### What is your feature request?

It would be nice to have the ability to track multiple PMS under your account tracking the activity and statistics.  From the home page, you could click on the name of the server in question, right now it's simply one beside Library Statistics, but you could have boxes for each one. Then deep dive into that server's stats.

### Are there any workarounds?

The only one I can think of at the moment, is to install a second instance of Tautulli for my second PMS.

### Additional Context

Keep up the amazing work.

**Comment by JonnyWong16** [comment]
Duplicate #113
