### ISSUE TITLE
Tautulli 2.14.5 (snap) regression: Fatal Unknown OpenSSL error in pyca/cryptography package

### ISSUE THREAD

**Issue by modest** [JonnyWong16/plexpy#2406]
### Describe the Bug

After updating the Tautulli snap from 2.14.4 to 2.14.5 (on an outdated Ubuntu 18.04.6 LTS install), a fatal error in the included pyca/cryptography lib causes the service to crash on start.  Reverting the snap to 2.14.4 resolved the issue.

```
File "/snap/tautulli/2020/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 77, in _openssl_assert
    raise InternalError(
cryptography.exceptions.InternalError: Unknown OpenSSL error. This error is commonly encountered when another library is not cleaning up the OpenSSL error stack. If you are using cryptography with another library that uses OpenSSL try disabling it before reporting a bug. Otherwise please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=310378599, lib=37, reason=103, reason_text=b'error:12800067:DSO support routines::could not load the shared library'), _OpenSSLErrorWithText(code=126615813, lib=15, reason=786693, reason_text=b'error:078C0105:common libcrypto routines::init fail')])
```

OpenSSL version: 1.1.1-1ubuntu2.1~18.04.23+esm5

Full error is in the linked log.

Appears to be related to the migration of `notifiers.py` from `pycryptodome` to `pyca/cryptography`

(Given that this occurs on an ancient and unsupported Ubuntu LTS release, it's fine to close this as Won't Fix as you wish.)

### Tautulli Version

2.14.5

### Git Branch

master

### Git Commit Hash

6979a4025fbf332694e10c3e264aa4a3cfdda065 (snap)

### Platform and Version

Ubuntu 18.04.6 LTS (...I know...) on kernel 5.4.0-196-generic #216~18.04.1-Ubuntu  (x86_64)

### Python Version

3.8.0

### Browser and Version

n/a

### Link to Logs

https://gist.github.com/modest/25bebf3fd40170190fab05d461e2cf46

**Comment by JonnyWong16** [comment]
Starts fine using Ubuntu 20.04 under WSL.

**Comment by JonnyWong16** [comment]
Closing since Ubuntu 18.04.6 LTS is no longer supported.
