### ISSUE TITLE
Reactivate Sync items as Downloads

### ISSUE THREAD

**Issue by daurpam** [JonnyWong16/plexpy#2424]
### Is your feature request related to a problem?

I know that there were some issues about this implementation that stopped working from the Plex side. And It is not possible with tautulli to get the Download information from the Plex Server.

But I found a repo with a plex exporter for prometheus and an asociated Grafana Dashboard that is able to show this info.
![image](https://github.com/user-attachments/assets/1e7c930a-7f87-42a6-b645-7791032bb719)

Could be possible to check how this guy take the info from Plex and try to implement on Tautulli again?

### What is your feature request?

I would like to see download items implemented again as a substitute for sync items. I wonder if this repo for a plex exporter for prometheus that can get that kind of information from Plex could be useful.
The repo: https://github.com/axsuul/plex-media-server-exporter/tree/master

I'm not a developer, but it seems like this [file](https://github.com/axsuul/plex-media-server-exporter/blob/master/lib/middleware/collector.rb) is used to get information from the server. Maybe it could be somehow an implementation for Python and tautulli.

Thanks in advance.

**Comment by JonnyWong16** [comment]
Duplicate #1451.

Plex does not provide enough details for downloads.

https://forums.plex.tv/t/plex-fireside-in-the-forum-2024/885879/316
