### ISSUE TITLE
[BUG] Cannot fix rating_key matches for "Artist" library type

### ISSUE THREAD

**Issue by polklabs** [JonnyWong16/plexpy#2429]
### Describe the Bug

My Plex library got messed up so I had to import all my media again.
Now all Tautulli media is not linked properly. I was able to use update_all_metadata.py to fix this for my Movie and TV Show library. But now I'm stuck trying to fix my music library.

In the web UI clicking fix match does not actually fixed the match. I also refactored update_all_metadata.py to work for music but when calling the update_metadata_details, nothing happens. The rating key is not changed.

For movies and tv I saw logs saying that Tautulli was updating the rating key. For music I don't see any logs.

Not sure what to do. Other than writing some SQL to try and update the database directly.

### Steps to Reproduce

Get some music with mismatched rating key from plex.
Make sure that music has history in Tautulli.
Open the track from history tab.
Click fix match.
Select the correct match.
Click "Update" in the popup window.
... Nothing happens
Go back to library, play count has not updated and music track is still unmatched.

Same thing happens if I try and call the api

### Expected Behavior

The rating key should be updated for item, parents, and grandparents in the music library

### Screenshots

![image](https://github.com/user-attachments/assets/344d401a-411e-4742-8c57-1cd9a03d4887)

![image](https://github.com/user-attachments/assets/e5550ef3-d93c-4720-9abd-2b1842772eda)

### Tautulli Version

v2.14.6

### Git Branch

master

### Git Commit Hash

940c2ae6cd064817512aa7646386a31fa9f465fa

### Platform and Version

docker:latest

### Python Version

3.11.9

### Browser and Version

Firefox 132.0.1 and http post requests

### Link to Logs

https://gist.github.com/polklabs/148af5fc5b0d4a4cd6434c74574c7da6

**Comment by JonnyWong16** [comment]
Compare [`get_new_rating_keys`](https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference#get_new_rating_keys) and [`get_old_rating_keys`](https://github.com/Tautulli/Tautulli/wiki/Tautulli-API-Reference#get_old_rating_keys). Those are the two dictionaries that Tautulli uses to map the rating keys. The dictionary keys need to match between the two for Tautulli to update the rating keys.

**Comment by polklabs** [comment]
the root dictionary key from get_new_rating_keys is "all artists" but every key under "children" matches perfectly with the correct rating key mappings. 
Not sure where "all artists" is coming from, must be some root/default name plex is returning?
![image](https://github.com/user-attachments/assets/764a154c-918b-4fe0-ba84-986b9208fb65)

**Comment by JonnyWong16** [comment]
Maybe something changed in Plex's API response. I will need to investigate.
