### ISSUE TITLE
Support to multiple editions Movie and TV

### ISSUE THREAD

**Issue by PilaScat** [JonnyWong16/plexpy#2453]
### Is your feature request related to a problem?

Yes, I have Movies and TV with two different formats, 1080p and 4K but in notifications it tells only the better one if present and in media info the library size is very wrong, this is a problem also for other sw that use tautulli api

### What is your feature request?

Support multiple editions, like this:
![image](https://github.com/user-attachments/assets/f1154652-2b6b-49fd-b332-92cbb0eb7e1f)

**Comment by JonnyWong16** [comment]
Duplicate #1728.
