### ISSUE TITLE
Tautulli-windows-v2.15.0-x64.exe / Trojan:Win32/Pomal!rfn

### ISSUE THREAD

**Issue by KurtVanHove** [JonnyWong16/plexpy#2454]
### Describe the Bug

Downloading the Windows installer Tautulli-windows-v2.15.0-x64.exe gives a trojan warning Trojan:Win32/Pomal!rfn

webfile: C:\Users\<account>\Downloads\Tautulli-windows-v2.15.0-x64.exe|https://objects.githubusercontent.com/github-production-release-asset-2e65be/31169720/4d365ec9-280a-403c-9836-8edf88f5e4d1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241204%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241204T100132Z&X-Amz-Expires=300&X-Amz-Signature=f111bbdb510e86bb8c947cb303377bec2957fc1ba181ec3d9398a8ff70bab466&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3DTautulli-windows-v2.15.0-x64.exe&response-content-type=application%2Foctet-stream|pid:9476,ProcessStart:133777801072525435

### Steps to Reproduce

Install Windows Defender Antivirus
Download the latest Windows x64 installer file

### Expected Behavior

I expect the files to be virus-free :)

### Tautulli Version

2.15.0

### Git Branch

master

### Git Commit Hash

n/a

### Platform and Version

Windows Server 2019

### Python Version

n/a

### Browser and Version

Edge Chromium

### Link to Logs

n/a

**Comment by JonnyWong16** [comment]
Add an exception to Windows Defender.

**Comment by Ginsu** [comment]
> Add an exception to Windows Defender.

No. This same issue has persisted for I don't know how many versions now, expecting people to just blindly trust you over Microsoft is not a solution.

**Comment by JonnyWong16** [comment]
It happens every time up update Pyinstaller. I submit it to Microsoft everytime. 

See #2322. 

https://www.reddit.com/r/Tautulli/search?q=virus&restrict_sr=on&sort=relevance&t=all

https://discuss.python.org/t/pyinstaller-false-positive/43171/11

https://www.reddit.com/r/Python/comments/u5m3x5/python_script_exe_detected_as_virus_in_vt/

**Comment by DiegoFleitas** [comment]
Also happening here

![imagen](https://github.com/user-attachments/assets/2e8ae2fd-9eb1-4913-b580-c703ca1a8476)

EDIT: Could this help in any way? https://signpath.org/

**Comment by dshokouhi** [comment]
> Add an exception to Windows Defender.

can we please just bring back auto update for windows? Last time (years ago) we were told this was not happening because of this exact issue with virus scanners and not wanting to tell people to add the exception. Now that we are back to the exception talk it would be great to remove that burden of manual updates. Especially now that we are told to exclude it.

**Comment by JonnyWong16** [comment]
No.

You can trigger a script to run `winget upgrade tautulli`.

**Comment by hobhobuk** [comment]
Been 3 weeks since release and many AV are still flagging this as a trojan..

**Comment by KurtVanHove** [comment]
> No.
> 
> You can trigger a script to run `winget upgrade tautulli`.

Even winget upgrade flags it as malicious, and will not upgrade it. (Note: I haven't added exception yet).

It's understandable that AVs flag applications written with PyInstaller as malicious ofcourse.
Isn't there a permanent solution to this, without paying for a signing license? Must be frustrating to lots of open source devs using this.

Quick google on this topic only gives me workaround-bandaids, like:

- Don't use --onefile but use --one-dir in stead when building. Also use --clean
- Swap out PyInstaller for cx-freeze, Nuitka, or ...
- Try to find that one line of code what's causing this (doable but a lot of work)
- Try submitting each released file to all popular AV suppliers (doable but a lot of work)

**Comment by JonnyWong16** [comment]
The only permanent solution is to stop providing an exe for Windows.

**Comment by DiegoFleitas** [comment]
> The only permanent solution is to stop providing an exe for Windows.

So signing the application code with a free certificate from [Signpath ](https://signpath.org/) won't solve the issue? or is not a permanent solution?
Asking users to ignore antivirus warnings is not a permament solution either IMO
New users will mean the issue will keep being discussed  and old users might not be inclined to update if it means adding an antivirus exception (like me), which could make maintenance harder

those are my 2 cents, I understand keeping this running on Windows is probably a pain point & I'm grateful for your work and this project but I think you are making the wrong choice here

**Comment by JonnyWong16** [comment]
You can install on Windows using an alternate method. Or build the exe yourself. Or install on a different system.

Those can be your permanent solutions.

**Comment by nicholashead** [comment]
> The only permanent solution is to stop providing an exe for Windows.

So is this why the latest release lacks a Windows build anymore? Winget won't update because it's missing as well. Did you intentionally remove the release for Windows? If so, can we please get it back?

**Comment by Fma15** [comment]
Is there a link to the exe? I know it will marked as a false positive, but I trust Tautulli enough.

**Comment by wamasi** [comment]
You can still grab the exe from the [Publish Installers](https://github.com/Tautulli/Tautulli/actions/workflows/publish-installers.yml) action. Just look for the correct version number like [v2.15.0](https://github.com/Tautulli/Tautulli/actions/runs/12000443027) and the exe is under the "Artifacts" section.

**Comment by Fma15** [comment]
Sweet thanks!

**Comment by zgmedia1** [comment]
> You can still grab the exe from the [Publish Installers](https://github.com/Tautulli/Tautulli/actions/workflows/publish-installers.yml) action. Just look for the correct version number like [v2.15.0](https://github.com/Tautulli/Tautulli/actions/runs/12000443027) and the exe is under the "Artifacts" section.

how dont see a way to download

**Comment by moeSizlak** [comment]
Bro.  Fix ur sh!t.

**Comment by srinthe702** [comment]
Same issue just popped on me...

![Image](https://github.com/user-attachments/assets/168fe1f9-8d1f-4c67-9053-1f7338f46285)

**Comment by rosscarlson** [comment]
> You can install on Windows using an alternate method. Or build the exe yourself. Or install on a different system.
> 
> Those can be your permanent solutions.

Wow, that's a, uh, reply.

**Comment by Eagle1337** [comment]
To add to this, defender keeps liking to kill the install directory as well on the name of being a virus.

**Comment by L162LZ** [comment]
Same issue for me, latest version 2.15.1-x64 keeps getting removed by Microsoft AV saying it contains a "Trojan:Win32/Yomal!rfn"
Not sure why this is "closed" when currently the program cannot be safely downloaded or used :-(

**Comment by oSPANNERo** [comment]
Just submitted to Microsoft as a false positive since [VirusTotal](https://www.virustotal.com/gui/file/7d3d710284b3416ae3efa617a64282bd510957f4afc78ed696a6843e11867d2f) says Microsoft is the only one detecting it as malicious.

**Comment by karasuhebi** [comment]
Defender just removed Tautulli from my computer citing it was Trojan:Win32/Yomal!rfn. This is strange as I was not trying to update it, it was already installed and I wasn't even using my computer at the time it got detected and removed. It allowed me to restore it though so that's good. I'm running version 2.15.1

**Comment by aharongrama** [comment]
@oSPANNERo It seems like now 8 other vendors are detecting it as a virus
https://www.virustotal.com/gui/file/3fc2530994538baa9898240f9310505c68a0e4021865d4022d1ce2d51ca5282a

**Comment by darrylhadfield** [comment]
Yeah, I'm out. Not interested in working with a dev who basically says, "I'm not fixing this, just trust that I'm not gonna put funky shit into my code."

**Comment by karasuhebi** [comment]
> Yeah, I'm out. Not interested in working with a dev who basically says, "I'm not fixing this, just trust that I'm not gonna put funky shit into my code."

That's weird. Your post is hidden as spam.

**Comment by darrylhadfield** [comment]
How convenient.

**Comment by Over666** [comment]
Yes it seems like we'l have to use another solution since dev doesnt wanna fix it

**Comment by BillyPrefect** [comment]
I don’t think it’s the dev - it’s the python library it seems. As the dev pointed out above he’s submitted to Microsoft the false positive and now Microsoft is not fixing their end.  Maybe look for the python library issue ? Or use another solution. This isn’t an airport, no need to announce departures.

**Comment by simonsteyn** [comment]
Yeah getting flagged by Chrome also, I really like Tautulli. Hope this gets fixed soon

**Comment by MrInkless** [comment]
Can restore it easily after Windows Defender removes it. Works fine after that just may happen again. If there is any way we can help get Windows to acknowledge it on their end let us know! I know they drag their feet and can be a pain

**Comment by kikosgc** [comment]
+1 Installed via winget, instantly got Windows Defender notification

**Comment by Taelkir** [comment]
Has anyone worked out what previous version of Tautulli we can roll back to in order to avoid this?

**Comment by kribjo** [comment]
This works fine for me, no exclusions made in malware detection. 

Version "v2.15.0 "

Git Branch:	nightly
Git Commit Hash:	**63fe386**057bc315bc97e3cecf622c21ad9f6e6fd
Platform:	Windows 10 (10.0.17763)  (actually Windows Server 2019)

Note that this is later than standard "v2.15.0", but not up to date with "v2.15.1". 
I haven't tried a newer build. 
I did not use the installer.

https://github.com/Tautulli/Tautulli/pkgs/container/tautulli#installation

**Comment by L162LZ** [comment]
> Has anyone worked out what previous version of Tautulli we can roll back to in order to avoid this?

I went back to 2.14.6 and got no Antiivirus issues since. Both 2.15.0 and 2.15.1 woundnt pass Microsoft Antivirus scans

**Comment by JDA88** [comment]
At least give the binaries for people not using defender

**Comment by Eagle1337** [comment]
As a heads up this isn't the only program that virustotal  or Defender hates due to pyinstaller.

**Comment by JDA88** [comment]
I'm not blaming the dev here, but windows user need an alternate way to deal with updates.
Leaving the release with a warning (will fail with defender) or giving an .zip portable install/update would work as a fix for must users

On this [post](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg) they say sticking to version 6.10.0 of pyinstaller might fix the issue, but I have no idea why the latest version of the installer is needed.

**Comment by JonnyWong16** [comment]
> At least give the binaries for people not using defender

https://github.com/Tautulli/Tautulli/actions/runs/12728526817

**Comment by JDA88** [comment]
> > At least give the binaries for people not using defender
> 
> https://github.com/Tautulli/Tautulli/actions/runs/12728526817
Very much appreciated and please apologies my total ignorance of the build an release system on GitHub :)

**Comment by thewriteway** [comment]
Executable file for Tautulli v2.15.2 no longer has any problems with Windows Defender so this issue can be closed.

**Comment by thesammy58** [comment]
Just a thought, perhaps this issue should be added to the FAQ page seeing as it is producing so many repeated reports and is becoming an actual frequently asked question.
