### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by travis-cleary** [JonnyWong16/plexpy#2458]
### Describe the Bug

The latest update Tautulli-windows-v2.15.0-x64.exe is being detected as a virus by Windows Defender.  

### Steps to Reproduce

1. Click to download Tautulli-windows-v2.15.0-x64.exe.   Windows detects this as a virus preventing it from being downloaded or installed.

### Expected Behavior

Not to be detected as a virus.

### Screenshots

![Windows Defendor Smartscreen](https://github.com/user-attachments/assets/08eec622-6436-43de-a800-cde4887a5ce7)

### Tautulli Version

v2.15.0

### Git Branch

na

### Git Commit Hash

na

### Platform and Version

Windows 11 Pro

### Python Version

na

### Browser and Version

Microsoft Edge Version 131.0.2903.86 (Official build) (64-bit)

### Link to Logs

na

**Comment by Chirping-Cat** [comment]
https://www.virustotal.com/gui/file/db556f84ad19109269ea8cd132ee44bdff09af156b1f10b65ca75015e447221a

![image](https://github.com/user-attachments/assets/4e59c4e5-4826-47a4-b348-856e9a52de4f)

**Comment by JonnyWong16** [comment]
Duplicate #2454.
