### ISSUE TITLE
False Popup from Upgrade or Install

### ISSUE THREAD

**Issue by Warren-Gee** [JonnyWong16/plexpy#2459]
### Describe the Bug

I'm not sure what's going on, I've never had an issue using Tautuili.
Windows Security User Account Control states it's infected, and AVG states it's infected with Malware.
I'm assuming it's a false positive.

Regards
WG

### Steps to Reproduce

No Issues here, please read the top statement and check the images

### Expected Behavior

No Issues here, please read the top statement and check the images

### Screenshots

![AVG Proof](https://github.com/user-attachments/assets/6ba81c71-9f39-4091-beb6-42f5d754e03f)
![Windows UAC Proof](https://github.com/user-attachments/assets/57b54e8e-fd14-4df2-81d7-2f246c2d27b9)

### Relevant Settings

No Issues here, please read the top statement and check the images

### Tautulli Version

v2.15.0

### Git Branch

Windows EXE

### Git Commit Hash

This is not the issue...

### Platform and Version

Win 10 64 Bit UEFI

### Python Version

3.120.00 - Not the Issue

### Browser and Version

I use Chrome

### Link to Logs

No logs, it's and upgrade or install issue...

**Comment by JonnyWong16** [comment]
Duplicate #2454.
