### ISSUE TITLE
v2.15.0 download reported as virus by Chrome and MS Defender

### ISSUE THREAD

**Issue by SIMAV8** [JonnyWong16/plexpy#2460]
### Describe the Bug

Chrome displays "Virus Detected" at end of download,   Windows Defender shows contains Trojan:Win32/Pomal!rfn and deletes the downloaded file.   Might just be me, but happens on three different machines (two are Win 10 Pro 22H2, one is Win 10 Enterprise LTSC 21H2).

### Steps to Reproduce

Download file "Tautulli-windows-v2.15.0-x64.exe" from github repo, alert fires in Chrome then Defender and file removed from system.

### Expected Behavior

to download and install successfully

### Screenshots

![20241207_193915-4675](https://github.com/user-attachments/assets/4b941f2b-c800-4ced-ac87-facd9b17d9ed)

![20241207_193837-4674](https://github.com/user-attachments/assets/7f673bbd-672e-4496-8b21-bf122f88c885)

### Relevant Settings

none, just basic download attempted

### Tautulli Version

2.15.0

### Git Branch

master

### Git Commit Hash

can't get that far

### Platform and Version

Windows 10

### Python Version

doesn't matter

### Browser and Version

Chrome 131.0.6778.109 (Official Build) (64-bit)

### Link to Logs

 SIMAV8/gist:dee8970b9b2f1f0980a625bf9ef3fcda

**Comment by JonnyWong16** [comment]
Duplicate #2454.
