### ISSUE TITLE
Windows flags installer as malicious

### ISSUE THREAD

**Issue by Ginsu** [JonnyWong16/plexpy#2461]
### Describe the Bug

Cannot install without Windows flagging the installer as malicious

### Steps to Reproduce

1. Attempt to run Tautulli-windows-v2.15.0-x64.exe
2. 
![image](https://github.com/user-attachments/assets/7e873633-a80f-4514-a3e9-95ca58df1153)

### Expected Behavior

The installer runs without being detected as malicious

### Screenshots

![image](https://github.com/user-attachments/assets/c310527d-76ed-4127-bbca-2df10bf009ff)
![image](https://github.com/user-attachments/assets/12e1ebb1-cd67-4e2b-b943-80f1655bdab2)

### Tautulli Version

2.15.0

### Git Branch

n/a

### Git Commit Hash

n/a

### Platform and Version

Windows 11

### Python Version

n/a

### Browser and Version

irrelevant

### Link to Logs

why

**Comment by Ginsu** [comment]
First time I've tried updating in months because this happened last time, at some point I'm going to write off this project entirely.

**Comment by JonnyWong16** [comment]
Duplicate #2454.
