### ISSUE TITLE
2.15.00: virus reported

### ISSUE THREAD

**Issue by guilamu** [JonnyWong16/plexpy#2469]
### Describe the Bug

Can't install on Windows, virus reported by defender and multiple others avs: https://www.virustotal.com/gui/file/db556f84ad19109269ea8cd132ee44bdff09af156b1f10b65ca75015e447221a

### Steps to Reproduce

Can't install on Windows, virus reported by defender and multiple others avs: https://www.virustotal.com/gui/file/db556f84ad19109269ea8cd132ee44bdff09af156b1f10b65ca75015e447221a

### Tautulli Version

2.15.0

### Git Branch

master

### Git Commit Hash

n/a

### Platform and Version

Windows 11

### Python Version

n/a

### Browser and Version

n/a

### Link to Logs

Can't install on Windows, virus reported by defender and multiple others avs: https://www.virustotal.com/gui/file/db556f84ad19109269ea8cd132ee44bdff09af156b1f10b65ca75015e447221a

**Comment by JonnyWong16** [comment]
Duplicate #2454.
