### ISSUE TITLE
virus detected

### ISSUE THREAD

**Issue by E6WeB** [JonnyWong16/plexpy#2470]
### Describe the Bug

When doing an update microsoft antivirus detects a virus and removes the exe. Please update this.

### Steps to Reproduce

download
try to install

### Expected Behavior

MS antivirus block the install

### Screenshots

na

### Relevant Settings

na

### Tautulli Version

v2.15.0 (2024-11-24)

### Git Branch

master

### Git Commit Hash

na

### Platform and Version

windows 11

### Python Version

na

### Browser and Version

chrome 

### Link to Logs

131

**Comment by JonnyWong16** [comment]
Duplicate #2454.
