### ISSUE TITLE
Notification on tautulli remote app doesn't work on iOS

### ISSUE THREAD

**Issue by kraaas** [JonnyWong16/plexpy#2471]
### Describe the Bug

Notifications on iOS remote tautulli app are not working with last tautulli 2.15.0.
Tried everything, re-register server, uninstall / install app- nothing.
Revert back to version 2.14.6- everything works perfect.

### Tautulli Version

2.15.0

### Git Branch

master

### Git Commit Hash

940c2ae6cd064817512aa7646386a31fa9f465fa

### Platform and Version

Windows Server 2022

### Python Version

3.11.9 (tags/v3.11.9:de54cf5, Apr 2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]

### Browser and Version

Edge 131

### Link to Logs

i did not get them before downgrade to 2.14.6

**Comment by JonnyWong16** [comment]
Logs please. The log file will include everything from the last few days.

**Comment by kraaas** [comment]
this is full \logs directory
edit: removed zip file with logs.

**Comment by JonnyWong16** [comment]
Please upload the `tautulli.log` file to https://gist.github.com so I don't need to download a file.

**Comment by kraaas** [comment]
https://gist.github.com/kraaas/5457e4896d75597cf46bbf0d544784dc

**Comment by JonnyWong16** [comment]
Do you have logs that go back further than Dec 26?

**Comment by kraaas** [comment]
yes, here they are: https://gist.github.com/kraaas/11a2d53dbaba33fb6f85ce5e5ed1dc40

**Comment by JonnyWong16** [comment]
v2.15.0 updated the notification from `onesignal.com` to `api.onesignal.com`. Your logs show that Tautulli cannot connect to that URL. Do you have something on your network blocking that URL? Like PiHole or similar.

**Comment by kraaas** [comment]
Definitely api.onesignal.com was blocked on my pihole. For some reason onesignal.com was whitelisted on pihole. Now I add api.onesignal.com to whitelist. I did not test it yet, but this is the reason for the problem. Thank you for you quick response and troubleshooting.

**Comment by kraaas** [comment]
I was able to test it, and whitelisting api.onesignal.com do the trick. Thank you.
